### ISSUE TITLE
JS driver - packaging - >= 1.7.0 fails

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#1207]
Running `npm install` with a package.json with `rethinkdb: >= 1.7.0` somehow fails with this error:

```
michel@xone:~/projects/thinky$ npm install rethinkdb
npm http GET https://registry.npmjs.org/rethinkdb
npm http 304 https://registry.npmjs.org/rethinkdb
npm ERR! Error: No compatible version found: rethinkdb@'>=1.7.0'
npm ERR! Valid install targets:
npm ERR! ["1.2.0-0","1.2.5-0","1.2.6-0","1.2.6-1","1.4.0-0","1.4.0-1","1.4.0-2","1.4.0-3","1.5.0-0","1.6.0-0","1.7.0-1","1.7.0-2"]
npm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:698:17)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.9.9-1-ARCH
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "rethinkdb"
npm ERR! cwd /home/michel/projects/thinky
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/michel/projects/thinky/npm-debug.log
npm ERR! not ok code 0
```

According to https://npmjs.org/doc/json.html, it should work fine...
I'm using node 0.10.13

Writing `rethinkdb: >= 1.7.0-2` works fine though...

**Comment by danielmewes** [comment]
We changed the versioning scheme for the JS driver https://github.com/rethinkdb/rethinkdb/issues/3281
I believe this will now work.
