### ISSUE TITLE
Interrupted system call in python driver

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#1322]
I'm getting:

```Python
Traceback (most recent call last):  
  File "<input>", line 1, in <module>  
  File "rethinkdb/ast.py", line 106, in run  
    return c._start(self, **global_opt_args)  
  File "rethinkdb/net.py", line 159, in _start  
    return self._send_query(query, term, global_opt_args)  
  File "rethinkdb/net.py", line 192, in _send_query  
    chunk = self.socket.recv(4)  
error: [Errno 4] Interrupted system call  
```

constantly when I try to do any query using the python driver.

**Comment by Tryneus** [comment]
Closing this issue - the relevant pull request was merged and we have not heard anything else about this in a long time.  Doing a visual inspection of the python driver shows that the socket read/write system calls are EINTR-wrapped.
