### ISSUE TITLE
Cannot find module 'node-protobuf' in CasperJS

### ISSUE THREAD

**Issue by Micka33** [rethinkdb/rethinkdb#1956]
Mac OSX `10.8.5`
node `v0.10.25`
npm `1.3.24`
rethinkdb `1.11.3 (CLANG 4.2 (clang-425.0.28))` installed via `rethinkdb.pkg`

```shell
➜  npm install rethinkdb
npm http GET https://registry.npmjs.org/rethinkdb
...
rethinkdb@1.11.0-4 node_modules/rethinkdb
└── protobufjs@2.0.5 (ascli@0.3.0, bytebuffer@2.3.1)
➜  
```
My casperjs script
```javascript
var casper  = require('casper').create({
                viewportSize: {width: 1224, height: 1000000},
                pageSettings: {loadImages:  true, loadPlugins: true, localToRemoteUrlAccessEnabled: true},
                verbose: true,
                logLevel: "debug"
              }),
    redb    = require('rethinkdb');

casper.start('http://www.google.com/');
casper.run(function()
{
  this.exit();
});
```
When I run my script I get this error
```shell
➜  casperjs rethinkdb.js
Error: Cannot find module 'node-protobuf'                                       
  /Users/micka/Documents/Work/project/phantomjs:/bootstrap.js:289
  /Users/micka/Documents/Work/project/phantomjs:/bootstrap.js:254 in require
  /Users/micka/Documents/Work/project/node_modules/rethinkdb/native-protobuf.js:8
  /Users/micka/Documents/Work/project/node_modules/rethinkdb/native-protobuf.js:21
➜  
```
So I decided to install the missing module, and this is what I get
```shell
➜  checkItBaby git:(master) npm install node-protobuf
npm http GET https://registry.npmjs.org/node-protobuf
npm http 200 https://registry.npmjs.org/node-protobuf
npm http GET https://registry.npmjs.org/node-protobuf/-/node-protobuf-1.0.10.tgz
npm http 200 https://registry.npmjs.org/node-protobuf/-/node-protobuf-1.0.10.tgz

> node-protobuf@1.0.10 install /Users/micka/Documents/Work/project/node_modules/node-protobuf
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.25/node-v0.10.25.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.25/node-v0.10.25.tar.gz
  CXX(target) Release/obj.target/protobuf/protobuf.o
../protobuf.cpp:7:10: fatal error: 'google/protobuf/dynamic_message.h' file not found
#include <google/protobuf/dynamic_message.h>
         ^
1 error generated.
make: *** [Release/obj.target/protobuf/protobuf.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/micka/Documents/Work/project/node_modules/node-protobuf
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! node-protobuf@1.0.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-protobuf@1.0.10 install script.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/Cellar/node/0.10.25/bin/node" "/usr/local/bin/npm" "install" "node-protobuf"
npm ERR! cwd /Users/micka/Documents/Work/project
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/micka/Documents/Work/project/npm-debug.log
npm ERR! not ok code 0
➜  
```

I get the exact same problems when installing rehtinkdb using brew instead.
What can I do ?

EDIT
---
I realized it works just fine when I require it in the node shell, but it breaks when I try to require it into a casperjs script.
So I opened an issue at CasperJS as well.
Here is the link for cross-reference n1k0/casperjs/issues/836.

**Comment by danielmewes** [comment]
We no longer rely on protobuf.
