### ISSUE TITLE
Node build fails: "Option --version passed to ld" if cc is not GNU

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#2001]
Tried to build `next` on Ubuntu 12.04 today:
```
    [290/313] BUILD node_0.10.15
cc: Warning: Option --version passed to ld, if ld is invoked, ignored otherwise
usage: cc [ options] files.  Use 'cc -flags' for details
cc: Warning: Option -dumpversion passed to ld, if ld is invoked, ignored otherwise
usage: cc [ options] files.  Use 'cc -flags' for details
Traceback (most recent call last):
  File "./configure", line 641, in <module>
    configure_node(output)
  File "./configure", line 461, in configure_node
    cc_version, is_clang = compiler_version()
  File "./configure", line 421, in compiler_version
    version = tuple(map(int, proc.communicate()[0].split('.')))
ValueError: invalid literal for int() with base 10: ''

Full error log: ./build/external/node_0.10.15_install.log
make[1]: *** [build/external/node_0.10.15/install.witness] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [make] Error 2
```

I think the problem is that `cc` on my system is not GNU cc. It is Oracle's compiler and takes different command line options (and probably wouldn't be compatible in general). `gcc` would be needed to invoke GNU CC.

**Comment by danielmewes** [comment]
This doesn't really matter in practice. Closing.
