### ISSUE TITLE
Python driver - eq_join doesn't properly handle r.args

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#2567]
`eq_join` doesn't seem to work with `r.args` with the python driver.

```
>>> r.expr([1, 2, 3]).eq_join(r.args([r.row, r.db("b9d6584dca2c5129539dc8bd9c65922c").table("0cc19ce919ed840596e98a20d4894cd1")]), {
...     'index': "val"
... }).run()
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "rethinkdb/ast.py", line 75, in run
    return c._start(self, **global_optargs)
  File "rethinkdb/net.py", line 212, in _start
    return self._send_query(query, global_optargs)
  File "rethinkdb/net.py", line 313, in _send_query
    self._check_error_response(response, query.term)
  File "rethinkdb/net.py", line 286, in _check_error_response
    raise RqlRuntimeError(message, term, frames)
rethinkdb.errors.RqlRuntimeError: Expected type TABLE but found DATUM:
{
    "index":    "val"
} in:
r.expr([1, 2, 3]).eq_join(lambda var_2: r.args([r.row, r.db('b9d6584dca2c5129539dc8bd9c65922c').table('0cc19ce919ed840596e98a20d4894cd1')]), r.expr({'index': 'val'}))
                                                                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^ 
```

Ping @Tryneus

**Comment by danielmewes** [comment]
@Tryneus @mlucy I know it has been a while, but what sort of server work does this need?

**Comment by mlucy** [comment]
I don't remember what server work we talked about.  At the very least we should re-do the driver fixes that I reverted.

**Comment by danielmewes** [comment]
Preliminarily scheduling for 2.1 then (polish I think, once I've created that milestone)
