### ISSUE TITLE
Explore a connection pool API in client drivers

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#281]
We should explore various connection pool designs here and see if implementing one might be beneficial.

**Comment by mlucy** [comment]
Moriau Joris mentioned to me in an email that we should consider using https://github.com/mperham/connection_pool in Ruby.  Posting the idea here so it doesn't get lost when we come back to this.

**Comment by internalfx** [comment]
Just throwing in my opinion...

So far rethinkdbdash has been everything I wanted from the original driver. Before I was opening and closing connections for every query.
I'm using coffeescript so everything is async anyway. I just want the driver to run my queries as fast as possible.

Run a query, get a response. Simple.

**Comment by hamiltop** [comment]
I'm working on https://github.com/hamiltop/exrethinkdb , a driver for Elixir. Due to Elixir's concurrency model, sharing a connection works perfectly fine (it's wrapped in an "actor"). Parallel queries and pipelining seem to work perfectly fine.

As such, I have a few questions:

1. Are there performance gains to be had with a connection pool? It's my understanding that rethinkdb distributes the queries throughout the cluster regardless of which node is queried.
2. Is there an api on rethinkdb that will allow a smart client to choose the correct node for the table being queried?

**Comment by mlucy** [comment]
1) Yes.  We push as much work as possible to the shards, but some work has to be done on the machine that accepted the connection, and you'll also be limited by network bandwidth on that machine if all your clients are connecting to it.  (Also, if you have an unsharded table, you can drastically reduce intracluster traffic by connecting the only node hosting the table.)
2) `r.table('whatever').config()` should tell you what nodes are acting as shards for the table.

**Comment by PeterKnego** [comment]
HI, I created a connection pool implementation for Java driver. It wraps connections and provides them in a round-robin fashion, creating new connections as needed. It supports connecting to multiple cluster nodes.
```
query.run() // use the global pool
query.run(pool) // use the pool and automatically lease/return the connection when done
query.run(connection) // the legacy way
```

This is the basic test: https://github.com/PeterKnego/rethinkdb/blob/connection_pool/drivers/java/src/test/java/com/rethinkdb/FixedConnectionPoolTest.java

**Comment by coffeemug** [comment]
:+1:

**Comment by prashaantt** [comment]
I'm exploring RethinkDB and would like to settle on the best Node driver. It appears pooling is now the main differentiator between this and `rethinkdbdash`. Although this thread talks about pooling to be in the works for the official driver as well since 2014, there doesn't seem to be a recent update on it. Can somebody please help me choose, depending on what's on the current roadmap?

**Comment by internalfx** [comment]
@prashaantt If you use [rethinkdbdash](https://github.com/neumino/rethinkdbdash), you will not be disappointed.

**Comment by thomasmodeneis** [comment]
hey guys any update here ? connection pool and reconnection strategy is must have for javascript driver.

**Comment by chrisvariety** [comment]
@thomasmodeneis #3771 would be the best solution for a JS connection pool. 

But it isn't as much of a "must have" as you'd think. For Postgresql, a connection pool is definitely a must have, but that's not true for Rethinkdb which automatically closes connections after 60 seconds if I recall correctly. (citation needed)

We utilize Rethinkdb very heavily without a connection pool and everything works smoothly, but if you're just starting off I'd recommend using rethinkdbdash right off the bat.

**Comment by raffi-minassian** [comment]
Like @chrisvariety , we too utilize Rethinkdb heavily (from node.js) without a connection pool and everything works extremely well. 

Also, we have some node.js based applications that pull data from a number of different RethinkDB databases depending on a number of properties on the incoming request. That kind of situation gets messy if you try to pool connections.

**Comment by thomasmodeneis** [comment]
Hi @chrisvariety and @raffi-minassian 
You are saying that connection pool and reconnection strategy is not a must have, so how do you deal with this ?
It happens everytime rethinkdb instance need to be restarted or crashes, and right now I have to restart the whole app.
You are saying for me to use rethinkdbdash but I'm not sure I have the time to (once again) refactor all the api methods and implement it with rethinkdash having in mind that people are now focusing on thinky.

I don't need any of the "goods" of rethinkdash for this particular api method. I just want this thing to reconnect, any ideas ?

Cheers.

```
     info:  ReqlDriverError: Connection is closed.
     at ReqlDriverError.ReqlError [as constructor] (/app/node_modules/rethinkdb/errors.js:23:13)
     at new ReqlDriverError (/app/node_modules/rethinkdb/errors.js:68:50)
     at TcpConnection.Connection._start (/app/node_modules/rethinkdb/net.js:417:13)
     at /app/node_modules/rethinkdb/ast.js:146:29
     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
     at Promise._resolveFromResolver (/app/node_modules/bluebird/js/main/promise.js:483:31)
     at new Promise (/app/node_modules/bluebird/js/main/promise.js:71:37)
     at Limit.TermBase.run (/app/node_modules/rethinkdb/ast.js:135:12)
     at getOneBySecondaryIndex (/app/app/server/_api.js:96:10)
     ReqlDriverError: Connection is closed.
     at Command.callback (/app/app/server/server.js:617:9)
     at ReqlDriverError.ReqlError [as constructor] (/app/node_modules/rethinkdb/errors.js:23:13)
     at normal_reply (/app/node_modules/redis/index.js:714:21)
     at new ReqlDriverError (/app/node_modules/rethinkdb/errors.js:68:50)
     at RedisClient.return_reply (/app/node_modules/redis/index.js:816:9)
     at TcpConnection.Connection._start (/app/node_modules/rethinkdb/net.js:417:13)
     at JavascriptRedisParser.Parser.returnReply (/app/node_modules/redis/index.js:188:18)
     at /app/node_modules/rethinkdb/ast.js:146:29
     at JavascriptRedisParser.execute (/app/node_modules/redis-parser/lib/parser.js:415:12)
     at tryCatcher (/app/node_modules/bluebird/js/main/util.js:26:23)
     at Socket.<anonymous> (/app/node_modules/redis/index.js:267:27)
     at Promise._resolveFromResolver (/app/node_modules/bluebird/js/main/promise.js:483:31)
     at new Promise (/app/node_modules/bluebird/js/main/promise.js:71:37)
     at emitOne (events.js:90:13)
     at Limit.TermBase.run (/app/node_modules/rethinkdb/ast.js:135:12)
     at Socket.emit (events.js:182:7)
     at readableAddChunk (_stream_readable.js:153:18)
     at getOneBySecondaryIndex (/app/app/server/_api.js:96:10)
     at Socket.Readable.push (_stream_readable.js:111:10)
     at TCP.onread (net.js:534:20)
     at Command.callback (/app/app/server/server.js:617:9)
     at normal_reply (/app/node_modules/redis/index.js:714:21)
     at RedisClient.return_reply (/app/node_modules/redis/index.js:816:9)
     at JavascriptRedisParser.Parser.returnReply (/app/node_modules/redis/index.js:188:18)
     at JavascriptRedisParser.execute (/app/node_modules/redis-parser/lib/parser.js:415:12)
     at Socket.<anonymous> (/app/node_modules/redis/index.js:267:27)
     at emitOne (events.js:90:13)
     at Socket.emit (events.js:182:7)
     at readableAddChunk (_stream_readable.js:153:18)
     at Socket.Readable.push (_stream_readable.js:111:10)
     at TCP.onread (net.js:534:20)
```

**Comment by chrisvariety** [comment]
@thomasmodeneis If you already have an existing app then no need to rewrite everything in Rethinkdbdash (though it should be mostly drop-in)

You shouldn't have to restart your whole app after encountering an error like that, just a retry should make the problem go away. Happy to look at your code if you paste it here.

**Comment by thomasmodeneis** [comment]
Ye right I could code the retry myself, but there are dozens of api methods in use and I would have to spend time doing a reconnection strategy just for me. That does not seem constructive for the community.

My question is rather going straight to the point of this ticket:
"We should explore various connection pool designs here and see if implementing one might be beneficial." from  Feb 2, 2013 and still today Nov 8 2016, the problem still unresolved.

Correct me if I'm wrong, but this ticket is a must have in any database driver, and the fact that this is the official JS driver and lack of reconnection strategy after +3 years of discussion worries me a little bit.

Cheers.

**Comment by raffi-minassian** [comment]
@thomasmodeneis I don't know the details around your layout but in the few apps that we have running against rethinkdb we either open a new connection when we need it, use it, then close it ... OR ... if keeping connections around we have some functions we pass them through before use to make sure they are still good and if not act accordingly, etc.

I don't know your layout so either style may not be a good approach. Also, either approach would require you to refactor a bunch I guess. So in the end I guess I agree with you that having a connection pool would be nice as it could solve some cases like yours easily. But I also think that it should always be possible to use the driver while managing the connections manually. From what I understand about Rethinkdbdash it is all or nothing in that you have to use the built in pooling.

**Comment by marshall007** [comment]
@raffi-minassian you can initialize rethinkdbdash with `pool: false` and just pass your connection to `.run()` like you would in the official driver.

**Comment by raffi-minassian** [comment]
@marshall007 Sweet. I missed that ... should have looked more carefully....

**Comment by GeoffreyPlitt** [comment]
Without rethinkdbdash, I found a trick: hard-crash on connection errors, and hopefully your server process is wrapped in ```while(true)``` or ```forever``` or ```pm2```, etc.

Basically:
```
if(err.name==='ReqlDriverError') {
    console.log("Connection error. Crashing and restarting.")
    process.exit(1)
  }
```
Hoping somebody has a better suggestion
