### ISSUE TITLE
ReQL tests failing on next since at least 5facb14

### ISSUE THREAD

**Issue by gchpaco** [rethinkdb/rethinkdb#3538]
I'm getting a lot of weird issues running ReQL tests on `next`; a lot of "server is closed" type stuff.  This dates back at least as far as 5facb14.

**Comment by gchpaco** [comment]
Sample test result:
```
>>> Failed polyglot/regression/2399.rb2.0 with exit code 1 after 1.6 sec (T+ 295.5 sec)

Server crashed while runningTraceback (most recent call last):
  File "./test-runner", line 1252, in run
    self.server.check()
  File "/Users/graham/wd/rethinkdb/test/rql_test/../common/driver.py", line 576, in check
    raise RuntimeError("Process stopped unexpectedly with return code %d" % self.process.poll())
RuntimeError: Process stopped unexpectedly with return code -5

TEST FAILURE: polyglot/regression/2399.rb2.0/1
	BODY: t.update({:a => {:b => r.literal({})}})
	VALUE: <RqlDriverError "Connection closed by server.">
	EXPECTED: "nope"
```

**Comment by danielmewes** [comment]
This seems to be fixed by @mlucy 's CR 2448.
