### ISSUE TITLE
`connections/cursor.rb` occasionally run as JavaScript test

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3551]
For some reason `connections/cursor.rb` is occasionally failing with the message: 

```
>>> Failed connections/cursor.rb1.9 with exit code 8 after 0.1 sec (T+ 0.6 sec)


/home/ssd2/larkost/rethinkdb/test/rql_test/connections/cursor.rb:3
# -- import the rethinkdb driver
^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

<<< end Failed: connections/cursor.rb1.9
```
This shows that the `cursor.rb` is being called from `cursor.rb.test` file as if it were a JavaScript (node) program. This would indicate that the latter is being called with the wrong setting for `INTERPRETER_PATH` env variable.

Thus far I have been unable to get this to show up for any other test, or when I run just the one test. It only shows up when I run with about `-j 10`, and not always then. In those cases it is of the first round of tests, so there should not be leftover from another test.

**Comment by larkost** [comment]
This looks like it was related to #3595 since this also depends on `ENV` variables.
