### ISSUE TITLE
Test failures in ReQL tests on `next` on MacOS X

### ISSUE THREAD

**Issue by gchpaco** [rethinkdb/rethinkdb#3609]
I've been experiencing these failures for some time on OS X, and folks bugged me to open an issue about it.

```
$ ./test-runner connections/connection.js connections/http.js connections/connection.py2.6 connections/http.rb2.0 server_test.rb2.0
Using rethinkdb binary /Users/graham/wd/rethinkdb/build/debug_clang/rethinkdb
	javascript interpreter: /usr/local/bin/node, driver: /Users/graham/wd/rethinkdb/drivers/javascript
	python 2.6 interpreter: /usr/bin/python2.6, driver: /Users/graham/wd/rethinkdb/drivers/python
	ruby 2.0 interpreter: /usr/bin/ruby, driver: /Users/graham/wd/rethinkdb/drivers/ruby
== Starting: connections/connection.js (T+ 0.9 sec)
== Starting: connections/connection.py2.6 (T+ 1.0 sec)
>>> Failed connections/connection.js with exit code 2 after 5.5 sec (T+ 6.6 sec)

Using RethinkDB client from: /Users/graham/wd/rethinkdb/build/packages/js


  Javascript connection API
    ✓ times out with a server that doesn't do the handshake correctly (1008ms)
    With no server
      1) fails when trying to connect
      ✓ empty run
RethinkDB warning: This syntax is deprecated. Please use `run(connection[, options      ✓ run with an object
    With a server
      2) "before each" hook


  3 passing (5s)
  2 failing

  1) Javascript connection API With no server fails when trying to connect:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/Users/graham/node_modules/mocha/lib/runnable.js:157:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  2) Javascript connection API With a server "before each" hook:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/Users/graham/node_modules/mocha/lib/runnable.js:157:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)




<<< end Failed: connections/connection.js
== Starting: connections/http.js (T+ 7.1 sec)
>>> Failed connections/http.js with exit code 1 after 2.2 sec (T+ 9.4 sec)

/usr/local/lib/python2.7/site-packages/twisted/internet/_sslverify.py:184: UserWarning: You do not have the service_identity module installed. Please install it from <https://pypi.python.org/pypi/service_identity>. Without the service_identity module and a recent enough pyOpenSSL tosupport it, Twisted can perform only rudimentary TLS client hostnameverification.  Many valid certificate/hostname mappings may be rejected.
  verifyHostname, VerificationError = _selectVerifyImplementation()
Using RethinkDB client from: /Users/graham/wd/rethinkdb/build/packages/js


  Javascript HTTP test -
    GET
      ✓ check basic GET result
    params
      ✓ with null
      ✓ with existing url params
    header
      ✓ object
      ✓ array
    HEAD
      ✓ with text resultFormat
      ✓ with json resultFormat
    POST
      ✓ form-encoded object
      ✓ json object
      ✓ form-encoded string
      ✓ arbitrary string
    PUT
      ✓ object
      ✓ arbitrary string
    PATCH
      ✓ object
      ✓ arbitrary string
    DELETE
      ✓ object
      ✓ arbitrary string
    redirect
      ✓ with no redirects allowed
      ✓ with not enough redirects allowed
      ✓ with enough redirects allowed
    gzip
      ✓ check decompression
    errors -
      ✓ failed json parse
    basic auth
      ✓ wrong password
      ✓ wrong username
      ✓ wrong auth type
      ✓ correct credentials
      ✓ default auth type
    digest auth
      ✓ wrong password
      ✓ wrong username
      ✓ wrong auth type
      ✓ correct credentials
    verify
      ✓ HTTP (74ms)
AssertionError: Expected an error, but got nullAssertionError: Expected an error, but got null
    at expect_error (/Users/graham/wd/rethinkdb/test/rql_test/connections/http.js:48:5)
    at /Users/graham/wd/rethinkdb/test/rql_test/connections/http.js:396:17
    at tryCatch2 (/Users/graham/wd/rethinkdb/build/packages/js/node_modules/bluebird/js/main/util.js:51:21)
    at Function.Promise$_successAdapter (/Users/graham/wd/rethinkdb/build/packages/js/node_modules/bluebird/js/main/nodeify.js:47:11)
    at tryCatch1 (/Users/graham/wd/rethinkdb/build/packages/js/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (/Users/graham/wd/rethinkdb/build/packages/js/node_modules/bluebird/js/main/promise.js:649:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/graham/wd/rethinkdb/build/packages/js/node_modules/bluebird/js/main/promise.js:663:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/graham/wd/rethinkdb/build/packages/js/node_modules/bluebird/js/main/promise.js:826:14)
    at Promise$_settlePromises [as _settlePromises] (/Users/graham/wd/rethinkdb/build/packages/js/node_modules/bluebird/js/main/promise.js:969:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/graham/wd/rethinkdb/build/packages/js/node_modules/bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (/Users/graham/wd/rethinkdb/build/packages/js/node_modules/bluebird/js/main/async.js:38:14)
    at process._tickCallback (node.js:442:13)

<<< end Failed: connections/http.js
== Starting: connections/http.rb2.0 (T+ 10.0 sec)
>>> Failed connections/http.rb2.0 with exit code 1 after 2.2 sec (T+ 12.3 sec)

/usr/local/lib/python2.7/site-packages/twisted/internet/_sslverify.py:184: UserWarning: You do not have the service_identity module installed. Please install it from <https://pypi.python.org/pypi/service_identity>. Without the service_identity module and a recent enough pyOpenSSL tosupport it, Twisted can perform only rudimentary TLS client hostnameverification.  Many valid certificate/hostname mappings may be rejected.
  verifyHostname, VerificationError = _selectVerifyImplementation()
/Users/graham/wd/rethinkdb/test/rql_test/connections/http.rb:39:in `expect_error': Expected an error, but got success with result:  (RuntimeError)
	from /Users/graham/wd/rethinkdb/test/rql_test/connections/http.rb:226:in `test_part'
	from /Users/graham/wd/rethinkdb/test/rql_test/connections/http.rb:234:in `test_verify'
	from /Users/graham/wd/rethinkdb/test/rql_test/connections/http.rb:269:in `call'
	from /Users/graham/wd/rethinkdb/test/rql_test/connections/http.rb:269:in `block in <main>'
	from /Users/graham/wd/rethinkdb/test/rql_test/connections/http.rb:267:in `each'
	from /Users/graham/wd/rethinkdb/test/rql_test/connections/http.rb:267:in `<main>'
RethinkDB Driver Port: 64861
Running test test_get
 - PASS
Running test test_params
 - PASS
Running test test_headers
 - PASS
Running test test_head
 - PASS
Running test test_post
 - PASS
Running test test_put
 - PASS
Running test test_patch
 - PASS
Running test test_delete
 - PASS
Running test test_redirects
 - PASS
Running test test_gzip
 - PASS
Running test test_failed_json_parse
 - PASS
Running test test_basic_auth
 - PASS
Running test test_digest_auth
 - PASS
Running test test_verify

<<< end Failed: connections/http.rb2.0
== Starting: server_test.rb2.0 (T+ 12.9 sec)
>>> Failed server_test.rb2.0 with exit code 1 after 15.7 sec (T+ 28.8 sec)

Run options:

# Running tests:

...F

Finished tests in 15.253228s, 0.2622 tests/s, 18.4879 assertions/s.

  1) Failure:
test_malformed_queries(ClientTest) [/Users/graham/wd/rethinkdb/test/rql_test/server_test.rb:133]:
<{"t"=>16, "b"=>[], "r"=>["Protocol error, connection closed."]}> expected but was
<{"t"=>16, "r"=>["Client is buggy (failed to deserialize query)."], "b"=>[]}>.

4 tests, 282 assertions, 1 failures, 0 errors, 0 skips

ruby -v: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

<<< end Failed: server_test.rb2.0
>>> Failed connections/connection.py2.6 with exit code 1 after 74.4 sec (T+ 75.5 sec)

test_auth_key (__main__.TestNoConnection) ... Not testing default port ok
test_connect (__main__.TestNoConnection) ... Not testing default port ok
test_connect_host (__main__.TestNoConnection) ... ok
test_connect_port (__main__.TestNoConnection) ... ok
Test that we get a ReQL error if we connect to a non-responsive port ... FAIL
test_empty_run (__main__.TestNoConnection) ... ok
test_connect_correct_auth (__main__.TestAuthConnection) ... ok
test_connect_long_auth (__main__.TestAuthConnection) ... ok
test_connect_no_auth (__main__.TestAuthConnection) ... ok
test_connect_wrong_auth (__main__.TestAuthConnection) ... ok
test_close_does_not_wait_if_requested (__main__.TestConnection) ... ok
test_close_waits_by_default (__main__.TestConnection) ... ok
test_connect_close_expr (__main__.TestConnection) ... ok
test_connect_close_reconnect (__main__.TestConnection) ... ok
test_db (__main__.TestConnection) ... ok
test_noreply_wait_waits (__main__.TestConnection) ... ok
test_port_conversion (__main__.TestConnection) ... ok
test_reconnect_does_not_wait_if_requested (__main__.TestConnection) ... ok
test_reconnect_waits_by_default (__main__.TestConnection) ... ok
test_repl (__main__.TestConnection) ... ok
test_use_outdated (__main__.TestConnection) ... ok
runTest (__main__.TestPrinting) ... ok
runTest (__main__.TestBatching) ... ok
runTest (__main__.TestGetIntersectingBatching) ... Running py connection tests
Random seed: 11340336524665664616 ok
runTest (__main__.TestGroupWithTimeKey) ... ok
runTest (__main__.TestSuccessAtomFeed) ... ok
test_shutdown (__main__.TestShutdown) ... ok

======================================================================
FAIL: Test that we get a ReQL error if we connect to a non-responsive port
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/graham/wd/rethinkdb/test/rql_test/connections/connection.py", line 170, in test_connnect_timeout
    self.assertRaisesRegexp(r.RqlDriverError, "Timed out during handshake with localhost:%d." % port, r.connect, port=port, timeout=2)
  File "/Users/graham/wd/rethinkdb/test/rql_test/connections/connection.py", line 99, in replacement_assertRaisesRegexp
    self.assertTrue(re.search(regexp, str(e)), '%s did not raise the expected message "%s", but rather: %s' % (repr(callable_func), str(regexp), str(e)))
AssertionError: <function connect at 0x101bf37d0> did not raise the expected message "Timed out during handshake with localhost:64673.", but rather: Interrupted connection while receiving from localhost:64673 - timed out

----------------------------------------------------------------------
Ran 27 tests in 73.181s

FAILED (failures=1)

<<< end Failed: connections/connection.py2.6

== Failed 5 tests (of 5) in 76.31 seconds!
	connections/connection.js
	connections/http.js
	connections/http.rb2.0
	server_test.rb2.0
	connections/connection.py2.6
```

**Comment by larkost** [comment]
First: please separate things into their own issues unless you have reason to believe that they are related.

- `connections/connection.js` error is #2649
- `connections/http.js` error is a byproduct of #3540
- `connections/http.rb` looks like a bad setup of twisted on your system. Are you using a non-standard Python setup? This is working on stock Pythons on 10.7, 10.9, and 10.10.
- `server_test.rb` error is #3375
- `connections/connection.py` is straightforward, and is a new issue (we need to catch the new errors coming in line 182 of `/drivers/python/rethinkdb/net.py`

So the one Issue that actually needs to be written up is: `connections/connection.py`, which is done in #3622.
