### ISSUE TITLE
Point changefeed query crashes `node.js`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3670]
From the `test/rql_test/` directory first up node, and then:

```javascript
var r = require('./importRethinkDB.js').r;
var conn = null;
r.connect({}, function (err, connection) { conn = connection; });
r.tableCreate('bob').run(conn);
r.db("test").table('bob').get(1).changes().run(conn);
```

This is crashing `node` (but not the server) with:
```javascript
r.db("test").table('bob').get(1).changes().run(conn)
{ _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _settledValue: undefined,
  _boundTo: undefined }
> 
/Users/larkost/Projects/rethinkdb/build/packages/js/net.js:191
            feed = new cursors.AtomFeed(this, token, opts, root);
                   ^
TypeError: undefined is not a function
    at TcpConnection.Connection._processResponse (/Users/larkost/Projects/rethinkdb/build/packages/js/net.js:191:20)
    at TcpConnection.Connection._data (/Users/larkost/Projects/rethinkdb/build/packages/js/net.js:105:12)
    at Socket.<anonymous> (/Users/larkost/Projects/rethinkdb/build/packages/js/net.js:495:32)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
```

I am missing the function to call, and not using this as a Promise, but it should not be crashing `node.js`

**Comment by danielmewes** [comment]
At the last lines of `cursors.coffee`, we have the following lines:
```
module.exports.Cursor = Cursor
module.exports.Feed = Feed
module.exports.makeIterable = ArrayResult::makeIterable
```

Note that `AtomFeed` is missing there. Wonder if that is related.

**Comment by danielmewes** [comment]
Yeah adding that line seems to fix it. Going to prepare a CR.

**Comment by danielmewes** [comment]
Also: Shouldn't our polyglot tests have caught this?

**Comment by danielmewes** [comment]
CR 2538

**Comment by gchpaco** [comment]
As the probable guilty party, you would think that the polyglot tests would have caught it.

**Comment by larkost** [comment]
Actually. the polyglot tests did catch it, but not until I made some changes in the JavaScript test "driver" that cleaned up the testing so some things did not go missing. So the test was good, the test framework had (more) issues (than it will have once I finish working out all the kinks).

**Comment by danielmewes** [comment]
Fixed in https://github.com/rethinkdb/rethinkdb/commit/184d982e9433ce71903727f8e000eccb99fb2f8f
