### ISSUE TITLE
JS driver throws an error during the socket read callback

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#3684]
Found when writing some changefeed tests:

```js
r.db("foo").table("bar").changes().map(r.row("dummy"))
```

The map function should error on any row.  This ends up throwing the error during the socket read callback rather than from the user's context (where they can catch and handle it).

Stack trace:
```
RqlRuntimeError: No attribute `dummy` in object [...]
    at RqlRuntimeError.RqlServerError (/home/ssd2/grey/rethinkdb/build/packages/js/errors.js:39:13)
    at new RqlRuntimeError (/home/ssd2/grey/rethinkdb/build/packages/js/errors.js:51:50)
    at mkErr (/home/ssd2/grey/rethinkdb/build/packages/js/util.js:173:10)
    at Feed.IterableResult._promptNext (/home/ssd2/grey/rethinkdb/build/packages/js/cursor.js:169:16)
    at Feed.IterableResult._addResponse (/home/ssd2/grey/rethinkdb/build/packages/js/cursor.js:83:12)
    at TcpConnection.Connection._processResponse (/home/ssd2/grey/rethinkdb/build/packages/js/net.js:126:14)
    at TcpConnection.Connection._data (/home/ssd2/grey/rethinkdb/build/packages/js/net.js:105:12)
    at Socket.<anonymous> (/home/ssd2/grey/rethinkdb/build/packages/js/net.js:495:32)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:736:14)
```

The cursor code should be appending the error to its list of responses and silently terminating the cursor.  The user should receive an error callback once they get to that response in the cursor's queue.

**Comment by Tryneus** [comment]
I put this in the 1.15.x milestone as I believe this is an existing problem - but it's a little late to fit into the 1.16.0 release.  This will just get moved over to 1.16.x once it exists, and that should be fine.

**Comment by Tryneus** [comment]
Nevermind, I misunderstood this error.  The driver is doing the right thing, the problem is our polyglot test framework not handling errors mid-stream.  Moving this to `tests`.

**Comment by Tryneus** [comment]
Fix for this is up in review 2556.
