### ISSUE TITLE
interface.cache_size tests failing in next

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3845]
```
FAIL interface.artificial_table
    self.test.run()
  File "/home/ssd3/daniel/rethinkdb/test/common/shelltest.py", line 31, in run
    check_call(self.command, shell=True, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '$RETHINKDB/test/interface/artificial_table.py' returned non-zero exit status 1


Traceback (most recent call last):
  File "/home/ssd3/daniel/rethinkdb/test/interface/artificial_table.py", line 47, in <module>
    subprocess.check_call(command_line, stdout=f, stderr=f)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ssd3/daniel/rethinkdb/test/rql_test/test-runner', '--cluster-port', '55389', '--driver-port', '40839', '--table', 'rethinkdb._debug_scratch', 'polyglot/control', 'polyglot/joins', 'polyglot/match', 'polyglot/mutation/atomic_get_set', 'polyglot/mutation/delete', 'polyglot/mutation/insert', 'polyglot/mutation/replace', 'polyglot/mutation/update', 'polyglot/polymorphism', 'polyglot/regression/309', 'polyglot/regression/453', 'polyglot/regression/522', 'polyglot/regression/545', 'polyglot/regression/568', 'polyglot/regression/678', 'polyglot/regression/1155', 'polyglot/regression/1179', 'polyglot/regression/1468', 'polyglot/regression/2399', 'polyglot/regression/2697', 'polyglot/regression/2709', 'polyglot/regression/2838', 'polyglot/regression/2930']' returned non-zero exit status 1
Command '$RETHINKDB/test/interface/artificial_table.py' returned non-zero exit status 1

FAIL interface.cache_size
    self.test.run()
  File "/home/ssd3/daniel/rethinkdb/test/common/shelltest.py", line 31, in run
    check_call(self.command, shell=True, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '$RETHINKDB/test/interface/cache_size.py' returned non-zero exit status 1


Traceback (most recent call last):
  File "/home/ssd3/daniel/rethinkdb/test/interface/cache_size.py", line 67, in <module>
    check_cache_usage(low_cache_mb)
  File "/home/ssd3/daniel/rethinkdb/test/interface/cache_size.py", line 42, in check_cache_usage
    assert expect_mb * 0.9 <= actual_mb <= expect_mb * 1.01, "Measured cache usage at %.2f MB (expected %.2f MB)" % (actual_mb, expect_mb)
AssertionError: Measured cache usage at 19.88 MB (expected 10.00 MB)
Command '$RETHINKDB/test/interface/cache_size.py' returned non-zero exit status 1
```

**Comment by danielmewes** [comment]
@larkost do you know more about these?

**Comment by larkost** [comment]
The `interface.cache_size` size one looks legitimate, my guess is that something is wrong with the cache size reporting. For the record that is getting the `0` from `rethinkdb.stats["storage_engine"]["cache"]["in_use_bytes"]`.

`interface.artificial_table` looks like it needs a little tweaking, some of which is done already in `larkost/3157-changefeed-tests`, but I will finish the job.

**Comment by danielmewes** [comment]
I could reproduce the cache_size problem manually. That's definitely a server bug. It looks like if you change the cache size a few times, it's sometimes effectively reduced to 0 (or the `stats` are displaying it as 0).

**Comment by larkost** [comment]
I have renamed this problem, as #3862 will now handle the `interface.artificial_table` problem.

**Comment by danielmewes** [comment]
Fix in CR 2683

**Comment by danielmewes** [comment]
Fixed in `next` as of https://github.com/rethinkdb/rethinkdb/commit/0db001cd35fbba8a3bc74042f73d105b2c5d961f
