### ISSUE TITLE
Python driver: invalid syntax

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#3996]
```
>>> r.set_loop_type('tornado')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssd1/atnnn/delme/async/local/lib/python2.7/site-packages/rethinkdb/net.py", line 545, in set_loop_type
    mod = import_module('.net_%s' % library, package=__package__)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ssd1/atnnn/delme/async/local/lib/python2.7/site-packages/rethinkdb/net_tornado.py", line 63
    raise gen.Return(!isinstance(self.error, RqlCursorEmpty))
                     ^
SyntaxError: invalid syntax
```

Ping @Tryneus

**Comment by Tryneus** [comment]
Fixed in `next` in commit 502045a, and `v2.0.x` in commit 07fe398.  Review was 2757.  Will be in release 2.0.
