### ISSUE TITLE
Tornado driver's .order_by returns List Object instead of TornadoCursor object.

### ISSUE THREAD

**Issue by v3ss0n** [rethinkdb/rethinkdb#4052]
``` python
    @gen.coroutine
    def get(self):
        curs = yield self.evt.order_by(r.desc('id')).run()
        messages = []
        logging.info(curs)
        while (yield curs.fetch_next()):
            item = yield curs.next()
            messages.append(item)

        self.render("event.html", messages=messages)
```

```python
Traceback (most recent call last):
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/web.py", line 1348, in _execute
    result = yield result
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/gen.py", line 807, in run
    value = future.result()
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/gen.py", line 812, in run
    yielded = self.gen.send(value)
  File "event_rechat.py", line 89, in get
    while (yield curs.fetch_next()):
AttributeError: 'list' object has no attribute 'fetch_next'
ERROR:tornado.access:500 GET / (::1) 236.52ms
```

**Comment by v3ss0n** [comment]
This is what i should be expecting? Why r.table("tblname").run() gives Cursor but adding a ordering gives a list?

**Comment by chrisvariety** [comment]
An orderBy without an index loads the entire table into memory, so it returns a List instead of a Cursor. If you do `.orderBy(r.desc({index: 'id'}))` RethinkDB will return a Cursor.

Similar to #3912 where this is explained much more eloquently.

**Comment by v3ss0n** [comment]
Thanks @chrisvariety  This should be documented clearly in http://rethinkdb.com/api/python/order_by/
 manual so we can expect what its coming.

**Comment by v3ss0n** [comment]
So i will close this for now.

**Comment by danielmewes** [comment]
It would be nice if we could make array results behave like cursors within Tornado. I'm not sure what that would look like though.

**Comment by v3ss0n** [comment]
I will see about it
