### ISSUE TITLE
test-runner reports a server as crashed when it is still running

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#4077]
When running against an external server, e.g. `./test-runner polyglot -c 60436 -d 59436 -i py -j10`, I noticed errors like this:

```
Using rethinkdb binary /home/ssd2/grey/rethinkdb/build/debug/rethinkdb
    python 2.6 interpreter: /usr/bin/python2.6, driver: /home/ssd2/grey/rethinkdb/drivers/python
== Starting: polyglot/arity.py2.6 (T+ 0.3 sec)
== Starting: polyglot/aggregation.py2.6 (T+ 0.3 sec)
== Starting: polyglot/changefeeds/edge.py2.6 (T+ 0.3 sec)
== Starting: polyglot/arraylimits.py2.6 (T+ 0.4 sec)
== Starting: polyglot/changefeeds/include_states.py2.6 (T+ 0.4 sec)
== Starting: polyglot/changefeeds/idxcopy.py2.6 (T+ 0.4 sec)
== Starting: polyglot/changefeeds/point.py2.6 (T+ 0.4 sec)
== Starting: polyglot/changefeeds/sindex.py2.6 (T+ 0.4 sec)
== Starting: polyglot/changefeeds/squash.py2.6 (T+ 0.4 sec)
== Starting: polyglot/changefeeds/table.py2.6 (T+ 0.4 sec)
>>> Crashed server polyglot/arity.py2.6 after 1.0 sec (T+ 1.0 sec)

Server crashed during testing

<<< end Crashed server: polyglot/arity.py2.6
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "./test-runner", line 1464, in run
    self.clean_server()
  File "./test-runner", line 1282, in clean_server
    raise ValueError('clean_server called when there was no connection')
ValueError: clean_server called when there was no connection
```

The server was still running, but the client connection had been closed by the server (due to an `interrupted_exc_t`, still investigating the cause).  I'm not sure if there's a better way for `test-runner` to check the status of the server, but it was a little confusing.

**Comment by gabor-boros** [comment]
This is not an issue anymore
