### ISSUE TITLE
UnicodeDecodeError with Python

### ISSUE THREAD

**Issue by no1youknowz** [rethinkdb/rethinkdb#4095]
This is very similar to UnicodeDecodeError - Python #3211.

I'm getting results from mysql and importing them into rethinkdb.

The column data in question contains _â€“_

The code im using is:

    r.db("platform").table("tracking_click").insert([
    {
        "click_referer" : row['click_referer'].encode('utf-8')
    }
    ]).run()

The error message I'm getting is:

	Traceback (most recent call last):
	  File "import_rethinkdb.py", line 186, in <module>
	    main()
	  File "import_rethinkdb.py", line 149, in main
	    "click_referer" : row['click_referer'].encode('utf8'),
	UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 57: ordinal not in range(128)

Thanks

**Comment by no1youknowz** [comment]
Resolved the issue.  I used ftfy and I had to use guess_bytes as fix_text would complain due to having valid text 99% of the time.
