### ISSUE TITLE
rebuilding the index - incorrect auth key

### ISSUE THREAD

**Issue by ianjuma** [rethinkdb/rethinkdb#4212]
Rebuilding the index with  ```rethinkdb index-rebuild -c localhost:29019 --auth pass```  fails.

even with the pass set on the web-ui ```r.db('rethinkdb').table('cluster_config').update({auth_key: "pass"})```

```python
Traceback (most recent call last):
  File "/usr/local/bin/rethinkdb-index-rebuild", line 9, in <module>
    load_entry_point('rethinkdb==1.14.0-0', 'console_scripts', 'rethinkdb-index-rebuild')()
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/_index_rebuild.py", line 228, in main
    rebuild_indexes(options)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/_index_rebuild.py", line 144, in rebuild_indexes
    conn_store = [r.connect(options['host'], options['port'])]
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 356, in connect
    return Connection(host, port, db, auth_key, timeout)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 126, in __init__
    self.reconnect(noreply_wait=False)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 159, in reconnect
    raise RqlDriverError("Server dropped connection with message: \"%s\"" % decodeUFTPipe(response).strip())
rethinkdb.errors.RqlDriverError: Server dropped connection with message: "ERROR: Incorrect authorization key."
```
tried with quotes as well ```"pass"```
reinstalled the python driver from pip as well.

**Comment by danielmewes** [comment]
Hi @ianjuma, thanks for the issue report.

Do you have any special characters in your password? Wonder if those might be causing the issue.

**Comment by ianjuma** [comment]
yes, I had a special character but with quotes ```"pass"``` that is fine. Upgraded the pip package, following an earlier issue. I just pip reinstalled it. 
Maybe improve error reporting, require python driver version higher than ```2.X.X```

**Comment by danielmewes** [comment]
Ah sorry for the inconvenience. Happy to hear it's working now.
I'm not sure why the auth key part wasn't working with the old version of the driver. Probably we just used to have a bug in there that we fixed in a later version.
