### ISSUE TITLE
JS driver throwing exception when closing connection

### ISSUE THREAD

**Issue by Timer** [rethinkdb/rethinkdb#4250]
```
  /app/node_modules/rethinkdb/net.js:571 
                _this.rawSocket.removeAllListeners(); 
                               ^ 
  TypeError: Cannot read property 'removeAllListeners' of null 
      at Socket.<anonymous> (/app/node_modules/rethinkdb/net.js:571:30) 
      at Socket.g (events.js:260:16) 
      at emitOne (events.js:82:20) 
      at Socket.emit (events.js:169:7) 
      at TCP._onclose (net.js:456:12) 
```

**Comment by danielmewes** [comment]
Thanks for the issue report @Timer .

Pinging @deontologician

**Comment by Timer** [comment]
For some context, it seems to only happen when (1) a listener is added to the connection, and (2) close is invoked after the connection is already closed. I don't have time to replicate it right now.
This should (hopefully) reproduce it.
```javascript
var connection;// ... actual connection from somewhere
connection.on('close', function(){});
connection.close();
connection.close();
```

**Comment by deontologician** [comment]
Thanks @Timer that's helpful

**Comment by Timer** [comment]
@deontologician I've saved you the trouble and tracked down the issue.

Basically, due to the asynchronous nature of the code, calling a second close on the connection before the [nodejs/iojs] event loop has a chance to loop results in it registering a duplicate event listener (small bug).
```javascript
          if (_this.rawSocket != null) {
            _this.rawSocket.once("close", function() {
              closeCb();
              _this.rawSocket.removeAllListeners();
              return _this.rawSocket = null;
            });
            return _this.rawSocket.end();
          } else {
            return process.nextTick(closeCb);
          }
```
The first event listener invokes a method on the rawSocket, then nulls it. Then the second (duplicate) listener then attempts to perform the same actions, but finds itself with a null object! I've presented two solutions, choose which you prefer.
p.s. I use the term duplicate and bug because there is a check (`if @rawSocket?`), but it doesn't account for the asynchronous execution.

## Short and sweet ##
```diff
diff --git a/drivers/javascript/net.coffee b/drivers/javascript/net.coffee
index 540735b..6f07365 100644
--- a/drivers/javascript/net.coffee
+++ b/drivers/javascript/net.coffee
@@ -1133,7 +1133,8 @@ class TcpConnection extends Connection
                         # called in response to the rawSocket 'close'
                         # event, we need to additionally clean up the
                         # rawSocket.
-                        @rawSocket.removeAllListeners()
+                        if @rawSocket?
+                          @rawSocket.removeAllListeners()
                         @rawSocket = null
                     )
                     @rawSocket.end()
```

#### A more round-about way of fixing the problem ####
```diff
diff --git a/drivers/javascript/net.coffee b/drivers/javascript/net.coffee
index 540735b..8b86c9a 100644
--- a/drivers/javascript/net.coffee
+++ b/drivers/javascript/net.coffee
@@ -1127,16 +1127,18 @@ class TcpConnection extends Connection
                     else
                         resolve result
                 if @rawSocket?
-                    @rawSocket.once("close", =>
+                    localSocket = @rawSocket
+                    @rawSocket = null
+                    localSocket.once("close", =>
                         closeCb()
                         # In the case where we're actually being
                         # called in response to the rawSocket 'close'
                         # event, we need to additionally clean up the
                         # rawSocket.
-                        @rawSocket.removeAllListeners()
-                        @rawSocket = null
+                        localSocket.removeAllListeners()
+                        return
                     )
-                    @rawSocket.end()
+                    localSocket.end()
                 else
                     # If the rawSocket is already closed, there's no
                     # reason to wait for a 'close' event that will
```

**Comment by deontologician** [comment]
Woot! Thanks. I'll make this change tomorrow

**Comment by Timer** [comment]
@deontologician I just added another diff using the stream state which may be an even better solution. :)

**Comment by deontologician** [comment]
OK, fix is up in CR 2913 by @AtnNn
