### ISSUE TITLE
JavaScript: ChangeFeed on .filter(...).orderBy(...).limit(...) error

### ISSUE THREAD

**Issue by rclai** [rethinkdb/rethinkdb#4266]
```
$ rethinkdb --version
rethinkdb 2.0.1~0trusty (GCC 4.8.2)
```

```js
// Using 2.0.0 driver
var r = require('rethinkdb');

r.connect({ host: 'localhost',
  port: 28015,
  db: 'test' },
function(err, conn) { 
  r.table('cities').filter({ c: 3 }).orderBy('a').limit(3).changes().run(conn, function(err, cursor) {
    if (err) {
      throw new Error(err)
    } else {
      cursor.each(console.log)
    }
  });
});
```

Error:
```
Error: RqlRuntimeError: Cannot call `changes` on an eager stream in:
r.table("cities").filter({c: 3}).orderBy("a").limit(3).changes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                   
    at /root/rethink-node-app/index.js:9:13
    at tryCatcher (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:24:31)
    at Promise.errorAdapter (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/nodeify.js:35:34)
    at Promise._settlePromiseAt (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:528:21)
    at Promise._settlePromises (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

I have a secondary index on `a`.

However, if I change `orderBy('a')` to `orderBy({ index: 'a'})` it gives me this error:

```
Error: RqlRuntimeError: Indexed order_by can only be performed on a TABLE or TABLE_SLICE in:
r.table("cities").filter({c: 3}).orderBy({index: "a"}).limit(3).changes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                   
    at /root/rethink-node-app/index.js:9:13
    at tryCatcher (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:24:31)
    at Promise.errorAdapter (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/nodeify.js:35:34)
    at Promise._settlePromiseAt (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:528:21)
    at Promise._settlePromises (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/rethink-node-app/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by thejsj** [comment]
`filter` is not yet supported by changefeeds and `orderBy` is only supported with indexes. 

You can write the same query by using `getAll` and indexes.

```
// First, create the indexes on `a` and `c`: 
// r.table('cities').indexCreate('c')
// r.table('cities').indexCreate('a')
r.table('cities').getAll(3, { index: 'c' }).orderBy({ index: 'a' }).limit(3).changes()
```

**Comment by thejsj** [comment]
Currently, `orderBy` is only supported with indexes. You can get your query working again if you create an index on `a` and then use that index with `orderBy`

First, create the index on `a`:
```
r.table('cities').indexCreate('a');
```
And now you can write the same changefeed like this: 

```
r.table('cities').filter({ c: 3 }).orderBy({ index: 'a' }).limit(3).changes()
```

**Comment by rclai** [comment]
Thanks! It works!

**Comment by rclai** [comment]
But it is weird, that the sequence of the expressions has to be like that.

**Comment by rclai** [comment]
Wouldn't it need to do more work if it has to sort before it has to filter?

**Comment by mlucy** [comment]
@rclai -- when you use an index, your data is already sorted (this sorting is stored on disk), so it isn't doing any work during the `order_by` step -- you're just telling it which index to read from for the future steps.

**Comment by rclai** [comment]
Oh okay cool.

**Comment by marshall007** [comment]
@mlucy I didn't realize the sorting was stored on disk, but that makes sense. So generally speaking would it be faster to do `.orderBy({ index: ... }).filter({ ... })` instead of `.getAll(..., { index: ... }).orderBy(...)` or does it just depend on the underlying data?

**Comment by rclai** [comment]
Question though, what if you do:

```js
.orderBy({ index: r.desc('fieldName') }).filter({ ... }).limit( ... );
```

Would this then cause more work to be done?

**Comment by mlucy** [comment]
The index is stored on disk in a certain order, but you can traverse it either forward or backward, so ascending or descending shouldn't affect performance.

**Comment by rclai** [comment]
Okay sweet.
