### ISSUE TITLE
static_cluster.append-stress test failing

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4405]
```
FAIL static_cluster.append-stress
  File "/home/ssd3/daniel/rethinkdb/test/common/shelltest.py", line 31, in run
    check_call(self.command, shell=True, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '$RETHINKDB/test/scenarios/static_cluster.py '$RETHINKDB/test/memcached_workloads/append_stress.py --address $HOST:$PORT --table $DB_NAME.$TABLE_NAME'' returned non-zero exit status 1


Traceback (most recent call last):
  File "/home/ssd3/daniel/rethinkdb/test/memcached_workloads/append_stress.py", line 36, in <module>
    raise ValueError("Incorrect value.")
ValueError: Incorrect value.
workload '$RETHINKDB/test/memcached_workloads/append_stress.py --address $HOST:$PORT --table $DB_NAME.$TABLE_NAME' failed with error code 1
Command '$RETHINKDB/test/scenarios/static_cluster.py '$RETHINKDB/test/memcached_workloads/append_stress.py --address $HOST:$PORT --table $DB_NAME.$TABLE_NAME'' returned non-zero exit status 1
```

Looking into it.

**Comment by danielmewes** [comment]
Turns out the test was using noreply writes, which are no longer guaranteed to be executed in order.

@larkost @VeXocide mentioned that you had recently added the noreply to speed up the test. Unfortunately it doesn't work in this case, since the test assumes that the updates are performed in order. I added soft durability instead, though the test is still taking about 4 minutes on newton.
In general this test is really old (from 2010) and comes from a time where appending to a value was actually using a different code path than other modifications. We should strongly consider trimming it down to fewer appends or even removing it altogether. The only thing I'd like to make sure is that we have at least some test that tests writing large documents.
