### ISSUE TITLE
Javascript Invalid Date causes Query to hang.

### ISSUE THREAD

**Issue by weshoke** [rethinkdb/rethinkdb#4413]
With a table indexed on a Date value, trying to insert a document with an "Invalid Date" causes the query to hang.  An Invalid Date can happen when you convert a unix timestamp that has NaN value to a Date object.

**Comment by mlucy** [comment]
Thanks for the bug report @weshoke !  Ping @deontologician (this sounds like a client bug to me).

**Comment by danielmewes** [comment]
@weshoke do you have an example query that reproduces this? How do you create the invalid date object exactly?

**Comment by mlucy** [comment]
@danielmewes -- I assume he meant this:

```
> new Date(NaN)
Invalid Date
```

**Comment by weshoke** [comment]
Yes, exactly.

**Comment by danielmewes** [comment]
I see, thanks.
@mlucy May I ask why you think that this is a Data Explorer problem? Isn't the bug that we allow a NaN value to get inserted in the first place?

**Comment by danielmewes** [comment]
(Edit: Data Explorer -> JS client)

**Comment by danielmewes** [comment]
Oh wait the error happened exactly when trying to insert the value. Never mind. I didn't read carefully.

I'm getting an exception by the way when trying this:
```js
var r = require("rethinkdb");
var inv = new Date(NaN);
r.connect(function(err, c) { r.table("t1").insert({ts: inv}).run(c, function(err, res) {console.log(res);} ); } );

RangeError: Invalid time value
    at Date.toISOString (native)
    at Function.<anonymous> (/tmp/node_modules/rethinkdb/ast.js:3865:32)
    at Function.expr (/tmp/node_modules/rethinkdb/util.js:39:16)
    at new MakeObject (/tmp/node_modules/rethinkdb/ast.js:1524:37)
    at Function.<anonymous> (/tmp/node_modules/rethinkdb/ast.js:3886:12)
    at Function.expr (/tmp/node_modules/rethinkdb/util.js:39:16)
    at Table.<anonymous> (/tmp/node_modules/rethinkdb/ast.js:1053:45)
    at Table.insert (/tmp/node_modules/rethinkdb/util.js:60:16)
    at repl:1:65
    at tryCatcher (/tmp/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:24:31)
    at Promise.successAdapter (/tmp/node_modules/rethinkdb/node_modules/bluebird/js/main/nodeify.js:22:30)
    at Promise._settlePromiseAt (/tmp/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:528:21)
    at Promise._settlePromises (/tmp/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/tmp/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:182:16)
    at Async._drainQueues (/tmp/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:192:10)
    at Async.drainQueues (/tmp/node_modules/rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
```

**Comment by weshoke** [comment]
That sounds like proper behavior.  I probably lost the error in a chain of promises.  Next time I'll try it in the Data Explorer.

**Comment by danielmewes** [comment]
@weshoke Ok that would explain it.
 
The fact that we throw the exception when constructing the query rather than when running it isn't ideal I think, but I'm not sure if we can easily solve this.

**Comment by weshoke** [comment]
No worries.  It's on me this one.  Thanks for following through.

**Comment by danielmewes** [comment]
@weshoke Ok, let me close this for now. Please let us know if you think we could improve something about the driver's behavior though.
