### ISSUE TITLE
recent change in JavaScript driver causing error

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4558]
After 95d0fe84d038b039bc12c910000bcd25ee8338be the JavaScript driver is not working in tests (e.g.: `./test/rql_test/test-runner -v connections/connection.js`). The specific error is:
```
/Users/larkost/projects/rethinkdb/build/packages/js/ast.js:1410
    self.args = (function() {
              ^
TypeError: Cannot set property 'args' of undefined
    at ImplicitVar.RDBOp (/Users/larkost/projects/rethinkdb/build/packages/js/ast.js:1410:15)
    at new ImplicitVar (/Users/larkost/projects/rethinkdb/build/packages/js/ast.js:1747:46)
    at Object.<anonymous> (/Users/larkost/projects/rethinkdb/build/packages/js/ast.js:4030:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/larkost/projects/rethinkdb/build/packages/js/net.js:30:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/larkost/projects/rethinkdb/build/packages/js/rethinkdb.js:4:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/larkost/projects/rethinkdb/test/rql_test/importRethinkDB.js:12:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/larkost/projects/rethinkdb/test/rql_test/connections/connection.mocha:19:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Reverting the change from that commit fixes the problem.

**Comment by deontologician** [comment]
OK I reverted the change
