### ISSUE TITLE
Connection issues to rethink DB from a node.js application

### ISSUE THREAD

**Issue by vyerukon** [rethinkdb/rethinkdb#4561]
Hi,

We have installed rethink db in oracle Linux hosts and when there is call from this application it is very sporadic in behavior and sometime the request goes fine and some times if fails with an error as 

2015-07-21 12:05:29 -04:00: error: Failed to listen 'entry' table changes Error: The connection was closed before the query could be completed.
    at /apps/XXX/XXX/instances/vm4/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:570:28
    at Object.loopKeys (/apps/xxxx/xxxx/instances/vm4/node_modules/thinky/node_modules/rethinkdbdash/lib/helper.js:45:14)
    at Connection._flush (/apps/xxxx/xxxx/instances/vm4/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:568:10)
    at Socket.<anonymous> (/apps/xxxx/xxxx/instances/vm4/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:65:10)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:466:12)
2015-07-21 12:13:35 -04:00: error: Failed to save Entry. Error: This socket is closed.
    at Socket._write (net.js:638:19)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Socket.Writable.write (_stream_writable.js:183:11)
    at Socket.write (net.js:616:40)
    at /apps/xxxx/xxxx/instances/vm1/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:495:21
    at Object.tryCatch (/apps/xxxx/xxxx/instances/vm1/node_modules/thinky/node_modules/rethinkdbdash/lib/helper.js:156:3)
    at Connection._send (/apps/xxxx/xxxx/instances/vm1/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:494:10)
    at /apps/xxxx/xxxx/instances/vm1/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:199:32
    at tryCatch1 (/apps/xxxx/xxxx/instances/vm1/node_modules/thinky/node_modules/bluebird/js/main/util.js:43:21)

Can some please help me on getting this figured out the cause and solve the problem.
Thinky.io is used for connections.

**Comment by danielmewes** [comment]
The follow-up issue is https://github.com/rethinkdb/rethinkdb/issues/4562 I assume.

**Comment by vyerukon** [comment]
Hi Daniel, 

Yes it's the similar issue with #4562.
We didn't want o get duplicated hence closed it.

Thank you.


Regards
Venkata Ramana
