### ISSUE TITLE
Socket closed and read errors on oracle linux

### ISSUE THREAD

**Issue by nayan9** [rethinkdb/rethinkdb#4562]
We are getting intermittent socket is closed and read errors to our rethinkdb on our oracle linux host.  I have 3 stack trace below:  two from our node app and another from a java test driver.

rethinkdb 2.0.3
thinky 2.0.10
node 0.10
rethink-java-driver 0.3

We do **not** experience these when we connect to our rtdb instance running on ubuntu (which is running rethinkdb 2.0.1).

1. **Error with a query from thinky client**

        Error: This socket is closed.
                at Socket._write (net.js:638:19)
                at doWrite (_stream_writable.js:226:10)
            at writeOrBuffer (_stream_writable.js:216:5)
            at Socket.Writable.write (_stream_writable.js:183:11)
            at Socket.write (net.js:616:40)
            at /apps/*****/instances/vm3/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:528:21
            at Object.tryCatch (/apps/*****/instances/vm3/node_modules/thinky/node_modules/rethinkdbdash/lib/helper.js:156:3)
            at Connection._send (/apps/*****/instances/vm3/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:527:10)
            at /apps/*****/instances/vm3/node_modules/thinky/node_modules/rethinkdbdash/lib/term.js:199:32
            at tryCatch1 (/apps/*****/instances/vm3/node_modules/thinky/node_modules/bluebird/js/main/util.js:43:21)
            at Promise$_callHandler [as _callHandler] (/apps/*****/instances/vm3/node_modules/thinky/node_modules/bluebird/js/main/promise.js:627:13)
            at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/apps/*****/instances/vm3/node_modules/thinky/node_modules/bluebird/js/main/promise.js:641:18)
            at Promise$_settlePromiseAt [as _settlePromiseAt] (/apps/*****/instances/vm3/node_modules/thinky/node_modules/bluebird/js/main/promise.js:800:14)
    
2. **Error with a changefeed from thinky client**

        Error: The connection was closed before the query could be completed.
            at /apps/*****/instances/vm2/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:603:28
            at Object.loopKeys (/apps/*****/instances/vm2/node_modules/thinky/node_modules/rethinkdbdash/lib/helper.js:45:14)
            at Connection._flush (/apps/*****/instances/vm2/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:601:10)
            at Socket.<anonymous> (/apps/*****/instances/vm2/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:65:10)
            at Socket.emit (events.js:95:17)
            at TCP.close (net.js:466:12)

3. **Error with query from Java client**  

        Error receiving data, expected 11098 bytes but received 4376
        com.rethinkdb.RethinkDBException: Error receiving data, expected 11098 bytes but received 4376
        	at com.rethinkdb.SocketChannelFacade._read(SocketChannelFacade.java:43)
        	at com.rethinkdb.SocketChannelFacade.read(SocketChannelFacade.java:88)
        	at com.rethinkdb.RethinkDBConnection.run(RethinkDBConnection.java:82)
        	at com.rethinkdb.ast.query.RqlQuery.run(RqlQuery.java:95)
        	at com.rethinkdb.ast.query.gen.Table.run(Table.java:91)
        	at *****.Save_Check.CompareValueDBAndDS(Save_Check.java:196)
        	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        	at java.lang.reflect.Method.invoke(Method.java:601)
        	at com.parasoft.scripting.java.JavaCode$JavaMethodRunnable.run(JavaCode.java:193)
        	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        	at java.lang.Thread.run(Thread.java:722)

**Comment by danielmewes** [comment]
@nayan9 Thank you for the report. We have not seen this before.

A few questions so we can try to reproduce this locally:
Which version of Oracle Linux are you running? Could you also post the output of `uname -a`?

Is the client running on the same machine as the RethinkDB server or remotely? Is it connecting through IPv4 or IPv6?

Are there any suspicious messages in the RethinkDB server log? Could you maybe send me the full server log by email (daniel@rethinkdb.com)?

How frequently / reliably does this happen?

**Comment by danielmewes** [comment]
@nayan9 / @vyerukon One more question: Is there anything special about your network setup? Any IP-level routers or firewalls between the servers or things like that? Any non-default configuration options for the network stack (e.g. the flags in /proc/sys/net/ipv4/) that might be relevant?

**Comment by nayan9** [comment]
> A few questions so we can try to reproduce this locally:
> Which version of Oracle Linux are you running? Could you also post the output of uname -a?

$ uname -a 
Linux ******.com 2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 07:57:22 PST 2014 x86_64 x86_64 x86_64 GNU/Linux


> Is the client running on the same machine as the RethinkDB server or remotely? 

Remotely

> Is it connecting through IPv4 or IPv6?

IPv4

> Are there any suspicious messages in the RethinkDB server log? 

No.

> Could you maybe send me the full server log by email (daniel@rethinkdb.com)?

Email is on the way.

> How frequently / reliably does this happen?

I can't put a firm number on it.  The way we have been reproducing it is by submitting a series of queries, waiting for a few minutes and then submitting another set.  In the second set, we will see one or two failures.  A guess: 10% failure rate with this scenario.

> Is there anything special about your network setup?

Nothing specific with few folks that I was able to check with.

> Any IP-level routers or firewalls between the servers or things like that? 

None

> Any non-default configuration options for the network stack (e.g. the flags in /proc/sys/net/ipv4/) that might be relevant?

Email is on the way.

**Comment by neumino** [comment]
Not sure about the Java stacktrace, but I can give some insights on the stacktraces 1 and 2:
- The error in 1 should not happen in theory, but then it happened. Rethinkdbdash 2.0.14 used a workaround for some events in the `net` library that were not properly fired (or fired too early). Maybe there's something else laying around. You could try to print the error here (in the rethinkdbdash driver used by thinky) to see what error the connection get
https://github.com/neumino/rethinkdbdash/blob/master/lib/pool.js#L201
- The stacktrace in 2 means that the connection used by the changefeed generated an error, and the driver close the feed and is basically just a consequence of the connection getting closed.

I believe printing the error in `pool.js` should give a pretty good explanation on what's happening here since it will bubble up errors happening on the TCP connections.

I'll track down how 1 can happen in rethinkdbdash in https://github.com/neumino/rethinkdbdash/issues/116

**Comment by danielmewes** [comment]
My current suspicion is that something is terminating TCP connections that have been inactive for a while, but the client only notices that the connection has been terminated when it tries to send some new data.

This might also be at the source for https://github.com/rethinkdb/rethinkdb/issues/4572 , though that's all still somewhat speculative. We are currently thinking about adding "keepalive" heartbeats to the protocol that would make sure that the connections don't remain inactive for too long.

I haven't been able to reproduce the problem on an Oracle Linux 6 VM so far, but will investigate  more.

**Comment by neumino** [comment]
@danielmewes -- That would make sense. In rethinkdbdash, the driver uses one connection per query. So if you open a changefeed on a connection, nothing else is going to be run on this connection. And maybe something (the OS, a router etc.) decides to kill the connection since nothing is happening?

**Comment by danielmewes** [comment]
(Status update: Waiting for update data from @nayan9 . This currently looks like a networking issue outside of RethinkDB)

**Comment by nayan9** [comment]
@danielmewes - your suspicion is correct so we are closing this as a networking issue.  Thanks for your support.

**Comment by danielmewes** [comment]
Thanks for the update @nayan9 ! Please let us know if you run into any other issues.
