### ISSUE TITLE
Trapping Connection Errors

### ISSUE THREAD

**Issue by weshoke** [rethinkdb/rethinkdb#4627]
When a connection is lost, I get a stream of these errors.  I'd like to be able to trap them and log them through my own system as opposed to having them end up on the console.  The Rethink driver has a connection.on("error", ...) event.  Is there a way to do this with rethinkdbdash?

```
ReqlDriverError: Failed to connect to localhost:28015
Full error:
{
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect"
}.
    at Socket.<anonymous> (../node_modules/rethinkdbdash/lib/connection.js:89:12)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickDomainCallback (node.js:381:11)
From previous event:
    at r.connect ../node_modules/rethinkdbdash/lib/index.js:78:11)
    at Pool.createConnection (../node_modules/rethinkdbdash/lib/pool.js:177:18)
    at null._onTimeout (../node_modules/rethinkdbdash/lib/pool.js:279:14)
    at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by weshoke** [comment]
Sorry.  Wrong project!
