### ISSUE TITLE
Errors when creating many tables fast

### ISSUE THREAD

**Issue by freiksenet** [rethinkdb/rethinkdb#4673]
Hello!

In our testing code we create a database, several tables (about 6), insert data and create some indexes. With javascript client version < 2, it worked fine, but after upgrading to version 2, we are having weird errors. They were solved by waiting ~2 seconds after creating tables and inserting data. It seems that the tables are no longer ready on the tableCreate promise resolve. I also get weird errors that connection is closed from tableCreate promises, even though the operation clearly succeeded. (tables *are* created, data *is* inserted, but index creation fails)

```js
export async function createTestDatabase(conn, dbName) {
  await RethinkDB.dbCreate(dbName).run(conn);
  await* TEST_DATA.get('tables').map(async function (data, table) {
    await RethinkDB.db(dbName).tableCreate(table).run(conn);
    await RethinkDB.db(dbName)
      .table(table)
      .insert(data.toJS())
      .run(conn);
  });
  // With this pause it works fine
  await new Promise((resolve) => {
    setTimeout(() => resolve(), 2000);
  });
  await* TEST_DATA.get('tables').get(TYPE_TABLE).map(async function (type) {
    const table = type.get('name');
    const indexes = type.get('indexes') || List();
    await* indexes.map(async function (index) {
      const name = index.get('name');
      const fields = index.get('fields');
      const indexDefinition = fields.rest().reduce(
        (acc, field) => acc(field),
        RethinkDB.row(fields.first())
      );
      await RethinkDB
        .db(dbName)
        .table(table)
        .indexCreate(name, indexDefinition)
        .run(conn);
      await RethinkDB
        .db(dbName)
        .table(table)
        .indexWait(name)
        .run(conn);
    });
  });
}
```

## Errors:

From tableCreate promises:

```
Unhandled rejection ReqlRuntimeError: Connection is closed in:
r.db("testdb0dab7ebe_ddc5_4fab_a426_2e88d250e487").tableCreate("User")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    at new ReqlRuntimeError (/home/freiksenet/Work/functo/reindex-api/node_modules/rethinkdb/errors.js:72:13)
    at mkErr (/home/freiksenet/Work/functo/reindex-api/node_modules/rethinkdb/util.js:177:10)
    at TcpConnection.<anonymous> (/home/freiksenet/Work/functo/reindex-api/node_modules/rethinkdb/net.js:323:18)
    at TcpConnection.cancel (/home/freiksenet/Work/functo/reindex-api/node_modules/rethinkdb/util.js:26:16)
    at TcpConnection.cancel (/home/freiksenet/Work/functo/reindex-api/node_modules/rethinkdb/net.js:603:43)
    at wrappedCb (/home/freiksenet/Work/functo/reindex-api/node_modules/rethinkdb/net.js:262:17)
    at tryCatcher (/home/freiksenet/Work/functo/reindex-api/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/home/freiksenet/Work/functo/reindex-api/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/home/freiksenet/Work/functo/reindex-api/node_modules/bluebird/js/main/promise.js:575:21)
    at Promise._settlePromises (/home/freiksenet/Work/functo/reindex-api/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/freiksenet/Work/functo/reindex-api/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/freiksenet/Work/functo/reindex-api/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Asy

In our testing code we create a database, several tables (about 6), insert data and create some indexes. With javascript client version < 2, it worked fine, but after upgrading to version 2, we are having weird errors. They were solved by waiting ~2 seconds after creating tables and inserting data. It seems that the tables are no longer ready on the tableCreate promise resolve. I also get weird errors that connection is closed from nc.drainQueues [as _onImmediate] (/home/freiksenet/Work/functo/reindex-api/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

From index creation

```
 ReqlRuntimeError: Table `testdb0dab7ebe_ddc5_4fab_a426_2e88d250e487.Micropost` does not exist in:
r.db("testdb0dab7ebe_ddc5_4fab_a426_2e88d250e487").table("Micropost").indexCreate("author", r.row("author")("value"))
```
```

**Comment by danielmewes** [comment]
Hi Mikhail, thanks for the report. Quick question: which version of the RethinkDB server are you using?

**Comment by freiksenet** [comment]
2.0.4

**Comment by freiksenet** [comment]
It's broken completely even with the pause on 2.1.

**Comment by freiksenet** [comment]
Ok, so this is embarassing. We were `await*` (`Promise.all`) not on an Object, but on Immutable.Map. Mea culpa. We converted it to object and it all works now.

**Comment by danielmewes** [comment]
Thanks for the update, glad it's working now @freiksenet .
