### ISSUE TITLE
Please consider more (or less) verbose message when driver connects to intercluster port

### ISSUE THREAD

**Issue by mscook** [rethinkdb/rethinkdb#4684]
I'm connecting to 2.1.0 running in a container (hence the port)

```
>>> import rethinkdb as r
>>> r.connect( "localhost", 32768).repl()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mscook/.virtualenvs/RethinkDB_2.1.0/local/lib/python2.7/site-packages/rethinkdb/net.py", line 597, in connect
    return conn.reconnect(timeout=timeout)
  File "/home/mscook/.virtualenvs/RethinkDB_2.1.0/local/lib/python2.7/site-packages/rethinkdb/net.py", line 527, in reconnect
    return self._instance.connect(timeout)
  File "/home/mscook/.virtualenvs/RethinkDB_2.1.0/local/lib/python2.7/site-packages/rethinkdb/net.py", line 410, in connect
    self._socket = SocketWrapper(self, timeout)
  File "/home/mscook/.virtualenvs/RethinkDB_2.1.0/local/lib/python2.7/site-packages/rethinkdb/net.py", line 313, in __init__
    (message, ))
rethinkdb.errors.ReqlDriverError: Server dropped connection with message: "RethinkDB cluster
"
>>> r.connect( "localhost", 32769).repl()
<rethinkdb.net.DefaultConnection object at 0x76af2d70>
```

I would probably prefer not to broadcast that it's a RethinkDB cluster... Thoughts?

**Comment by danielmewes** [comment]
> I would probably prefer not to broadcast that it's a RethinkDB cluster... Thoughts?

Can you explain a bit more why you think that's bad? What message would you like to see instead?

**Comment by danielmewes** [comment]
Closing since we haven't heard back from @mscook for a while.
