### ISSUE TITLE
interface.server_config and interface.emergency_repair intermittently failing on v2.1.x

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4733]
On newton in debug mode running with `-j 4`:
```
FAIL interface.emergency_repair
    return c._start(self, **global_optargs)
  File "/home/ssd3/daniel/rethinkdb/build/drivers/python/rethinkdb/net.py", line 575, in _start
    return self._instance.run_query(q, global_optargs.get('noreply', False))
  File "/home/ssd3/daniel/rethinkdb/build/drivers/python/rethinkdb/net.py", line 450, in run_query
    raise res.make_error(query)
rethinkdb.errors.ReqlOpFailedError: The server(s) hosting table `test.erase` are currently unreachable. The table was not repaired. At least one of a table's replicas must be accessible in order to repair it in:
r.table('erase').reconfigure(emergency_repair='unsafe_rollback_or_erase', dry_run=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Command '$RETHINKDB/test/interface/emergency_repair.py' returned non-zero exit status 1

[...]
FAIL interface.server_config
    check_call(self.command, shell=True, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '$RETHINKDB/test/interface/server_config.py' returned non-zero exit status 1


Traceback (most recent call last):
  File "/home/ssd3/daniel/rethinkdb/test/interface/server_config.py", line 127, in <module>
    assert res == 234, res
AssertionError: 123
Command '$RETHINKDB/test/interface/server_config.py' returned non-zero exit status 1
```

(pinging @larkost )

**Comment by danielmewes** [comment]
Running the tests individually seems to make them pass pretty reliably, so I guess there might be a timing issue here.
