### ISSUE TITLE
polyglot/changefeeds/edge.js failing in next

### ISSUE THREAD

**Issue by encryptio** [rethinkdb/rethinkdb#4880]
Looks like pull request #4784 broke the `polyglot/changefeeds/edge.js` test, with a few new "Changefeed aborted (table unavailable)" errors, and a few errors being eaten and turned into empty successes.

Full transcript:

```
rethinkdb/test/rql_test $ git rev-parse HEAD
faf8d557abdbc7214d6aa0ccd40ec197d5ac1174
rethinkdb/test/rql_test $ ./test-runner polyglot/changefeeds/edge.js
Warning: did not find any tests for Python 2.6
Warning: did not find any tests for Ruby 1.9
Using rethinkdb binary /home/ckastorff/rethinkdb/build/release_clang/rethinkdb
        JavaScript interpreter: /usr/local/bin/node, driver: /home/ckastorff/rethinkdb/drivers/javascript
== Starting: polyglot/changefeeds/edge.js (T+ 1.0 sec)
>>> Failed polyglot/changefeeds/edge.js with exit code 1 after 8.9 sec + 0.0 sec setup (T+ 10.2 sec)

Using RethinkDB client from: /home/ckastorff/rethinkdb/build/packages/js
TEST FAILURE:    line 120
     SOURCE:     postmap_changes1
     EXPECTED:   ReqlNonExistenceError: No attribute `dummy` in object:
     RESULT:     []

TEST FAILURE:    line 123
     SOURCE:     postmap_changes2
     EXPECTED:   ReqlNonExistenceError: Index out of bounds: 1
     RESULT:     []

TEST FAILURE:    line 126
     SOURCE:     postmap_changes3
     EXPECTED:   ReqlUserError: dummy
     RESULT:     []

Failed 3 tests
Cleaning up
Failed 3 tests
Cleaning up
TEST FAILURE:    line 135
     SOURCE:     postfilter_changes1
     EXPECTED:   bag(["0","1","10","11","12","13","14","15","16","17","18","19","100"])
     RESULT:     ReqlOpFailedError: Changefeed aborted (table unavailable).
     BACKTRACE:
<<<<<<<<<
ReqlOpFailedError: Changefeed aborted (table unavailable) in:
r.db("test").table("polyglot_changefeeds_edge_js").changes({squash: false}).filter(r.branch(r.row("new_val")("value").lt("2"), true, r.row("dummy"))).limit(13)("new_val")("value")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              
    at ReqlOpFailedError.ReqlRuntimeError (/home/ckastorff/rethinkdb/build/packages/js/errors.js:72:13)
    at ReqlOpFailedError.ReqlAvailabilityError (/home/ckastorff/rethinkdb/build/packages/js/errors.js:150:56)
    at new ReqlOpFailedError (/home/ckastorff/rethinkdb/build/packages/js/errors.js:161:52)
    at mkErr (/home/ckastorff/rethinkdb/build/packages/js/util.js:177:10)
    at Feed.IterableResult._promptNext (/home/ckastorff/rethinkdb/build/packages/js/cursor.js:167:16)
    at Feed.IterableResult._addResponse (/home/ckastorff/rethinkdb/build/packages/js/cursor.js:86:12)
    at TcpConnection.Connection._processResponse (/home/ckastorff/rethinkdb/build/packages/js/net.js:134:16)
    at TcpConnection.Connection._data (/home/ckastorff/rethinkdb/build/packages/js/net.js:118:12)
    at Socket.<anonymous> (/home/ckastorff/rethinkdb/build/packages/js/net.js:511:32)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:736:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
>>>>>>>>>

Failed 4 tests
Cleaning up
TEST FAILURE:    line 138
     SOURCE:     postfilter_changes2
     EXPECTED:   bag(["0","1","10","11","12","13","14","15","16","17","18","19","100"])
     RESULT:     ReqlOpFailedError: Changefeed aborted (table unavailable).
     BACKTRACE:
<<<<<<<<<
ReqlOpFailedError: Changefeed aborted (table unavailable) in:
r.db("test").table("polyglot_changefeeds_edge_js").changes({squash: false}).filter(r.branch(r.row("new_val")("value").lt("2"), true, r([]).nth(1))).limit(13)("new_val")("value")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              
    at ReqlOpFailedError.ReqlRuntimeError (/home/ckastorff/rethinkdb/build/packages/js/errors.js:72:13)
    at ReqlOpFailedError.ReqlAvailabilityError (/home/ckastorff/rethinkdb/build/packages/js/errors.js:150:56)
    at new ReqlOpFailedError (/home/ckastorff/rethinkdb/build/packages/js/errors.js:161:52)
    at mkErr (/home/ckastorff/rethinkdb/build/packages/js/util.js:177:10)
    at Feed.IterableResult._promptNext (/home/ckastorff/rethinkdb/build/packages/js/cursor.js:167:16)
    at Feed.IterableResult._addResponse (/home/ckastorff/rethinkdb/build/packages/js/cursor.js:86:12)
    at TcpConnection.Connection._processResponse (/home/ckastorff/rethinkdb/build/packages/js/net.js:134:16)
    at TcpConnection.Connection._data (/home/ckastorff/rethinkdb/build/packages/js/net.js:118:12)
    at Socket.<anonymous> (/home/ckastorff/rethinkdb/build/packages/js/net.js:511:32)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:736:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
>>>>>>>>>

Failed 5 tests
Cleaning up
TEST FAILURE:    line 135
     SOURCE:     postfilter_changes1
     EXPECTED:   bag(["0","1","10","11","12","13","14","15","16","17","18","19","100"])
     RESULT:     ["0","1","10","11","13"]

Failed 6 tests
Cleaning up
TEST FAILURE:    line 138
     SOURCE:     postfilter_changes2
     EXPECTED:   bag(["0","1","10","11","12","13","14","15","16","17","18","19","100"])
     RESULT:     ["0","1","10","11","13"]

Failed 7 tests
Cleaning up
<<< end Failed: polyglot/changefeeds/edge.js
Traceback (most recent call last):
  File "./test-runner", line 2035, in <module>
    main()
  File "./test-runner", line 2032, in main
    sys.exit('\n== Failed %d test%s (of %d) in %.2f seconds!\n\t%s\n\n' % (len(failedTests), plural, len(testList), time.time() - startTime, '\n\t'.join(failedTestNames)))
TypeError
```

The last `TypeError` from `test-runner` is unrelated.

**Comment by larkost** [comment]
The same change also broke `./test/rql_test/test-runner -v connections/cursor.js`. Specifically this is trying to directly use the `Promise` object from the `bluebird` module... but with out ever importing it. This is on both lines [https://github.com/rethinkdb/rethinkdb/blob/41af74029a542434fafb00ac54bf54e068a6ecc9/test/rql_test/connections/cursor.mocha#L214](line 214) and [https://github.com/rethinkdb/rethinkdb/blob/41af74029a542434fafb00ac54bf54e068a6ecc9/test/rql_test/connections/cursor.mocha#L234](line 234).

**Comment by marshall007** [comment]
Sorry about that! I tested under `node@v0.12.x` which exports the native `Promise` object as a global, so that explains the `connections` tests. I have no idea why the `polyglot/changefeeds/edge` tests are failing though, that seems unrelated to the `Promise` issue. Will try to dig into it further.

**Comment by marshall007** [comment]
@deontologician it appears the issue is with the refactoring of [these lines](https://github.com/marshall007/rethinkdb/blob/07197781e47b01e6ab81749dfc72da9002df7ff3/drivers/javascript/cursor.coffee#L221-L227). If you change the definition of `nextCb` to the following, the `polyglot/changefeeds/edge` tests pass again:

```js
nextCb = (err, data) =>
    if err?
        if err.message is 'No more rows in the cursor.'
            onFinished?()
        else 
            cb(err)
    else if cb(null, data) isnt false
        @_next nextCb
    else
        onFinished?()
```

Basically, my refactored version was continuing iteration even after encountering an error. I can throw the fix in a new PR if you'd like. Just let me know!

**Comment by deontologician** [comment]
OK, sorry for getting back to this late. @marshall007 I tried out your change and it indeed makes the test pass

**Comment by marshall007** [comment]
@deontologician no problem! Are you planning on pushing up the fix or do you want me to create a PR?

**Comment by deontologician** [comment]
I'm fixing the import issue as well, and I think there are a couple more failures exposed by that

**Comment by deontologician** [comment]
OK, review for this is up in CR 3281 by @larkost
