### ISSUE TITLE
Wrapping API methods throws circular JSON error

### ISSUE THREAD

**Issue by panganibanpj** [rethinkdb/rethinkdb#4890]
Noticed something while simplifying references to all my queries
```
var UserTable = rethinkdb.table('user');
var queries = {
    getById: UserTable.get
};
console.log(UserTable.get === queries.getById); // true
UserTable.get('70c63817-1802-49e1-8d32-b3e83069c522').run(connection); // Works!
queries.getById('70c63817-1802-49e1-8d32-b3e83069c522').run(connection); // Throws :(
```
`queries.getById` throws:
```
Unhandled rejection TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at TcpConnection.Connection._sendQuery (node_modules/rethinkdb/net.js:446:47)
    at TcpConnection.Connection._start (node_modules/rethinkdb/net.js:407:10)
    at node_modules/rethinkdb/ast.js:142:29
    at Get.TermBase.run (node_modules/rethinkdb/ast.js:131:12)
```

Worked around by:
```
function getById(id) { return UserTable.get(id); }
queries.getById = getById;
```

Seems unnecessary

**Comment by coffeemug** [comment]
Thanks for reporting. There is a bunch of trickery going on in the JS driver to make chaining work, and I'm not sure what exactly is going on here. @deontologician -- do you know if this is fixable?

**Comment by deontologician** [comment]
It's possible we aren't using the double arrow for `.get` etc, so `this` is being dynamically determined (the default in js). This is a guess of the top of my head, I can check it for sure monday

**Comment by deontologician** [comment]
Yeah, so definitions like:

```coffee
get: (args...) -> new Get {}, @, args...
```

in the js driver are to blame. js `this` strikes again. Luckily it's a simple fix
