### ISSUE TITLE
Segmentation fault in changefeed code

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4912]
I was running the table fuzzer with the following modification:
```
diff --git a/test/interface/table_fuzzer.py b/test/interface/table_fuzzer.py
index 3ee85da..0464a02 100755
--- a/test/interface/table_fuzzer.py
+++ b/test/interface/table_fuzzer.py
@@ -300,7 +300,7 @@ class insert(TableQuery):
     def __init__(self, conn):
         TableQuery.__init__(self, conn)
         self.start = self.table.count
-        self.num_rows = random.randint(1, 500)
+        self.num_rows = random.randint(1000, 50000)
         self.table.count = self.start + self.num_rows
     def sub_query(self, q):
         return q.insert(r.range(self.start, self.start + self.num_rows).map(lambda x: {'id': x}))
```
and these parameters:
```
table_fuzzer.py --changefeeds --servers 4 --threads 64 --duration 1800
```
on next commit 4bdbcfa57b6cf00bed4d9ebefc83d1a89fef984b .

One server then crashed with:
```
error: Error in src/arch/runtime/thread_pool.cc at line 359:
error: Segmentation fault from reading the address 0x1.
error: Backtrace:
```

and oddly without a backtrace.

GDB gives me the following backtrace from the core file:
```
#0  0x00007f0433ba8066 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007f0433ba8d7d in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007f04336c7548 in backtrace () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00000000016e955b in rethinkdb_backtrace (buffer=0x7f03647f0380, size=100) at src/rethinkdb_backtrace.cc:100
#4  0x000000000220047b in backtrace_t::backtrace_t (this=0x7f041783e1c0) at src/backtrace.cc:203
#5  0x0000000002200f65 in lazy_backtrace_formatter_t::lazy_backtrace_formatter_t (this=0x7f041783e1c0) at src/backtrace.cc:283
#6  0x0000000002200107 in format_backtrace (use_addr2line=true) at src/backtrace.cc:197
#7  0x00000000017f26ee in report_fatal_error (file=0x2962c4a "src/arch/runtime/thread_pool.cc", line=359, msg=0x2963780 "Segmentation fault from reading the address %p.")
    at src/errors.cc:83
#8  0x000000000160aeb4 in linux_thread_pool_t::fatal_signal_handler (signum=11, info=0x7f041783e570, data=0x7f041783e440) at src/arch/runtime/thread_pool.cc:359
#9  <signal handler called>
#10 0x0000000000000001 in ?? ()
#11 0x00000000020c5591 in operator() (this=0x7f0417010040, sub=0x7f03fbe24c00) at src/rdb_protocol/changefeed.cc:2308
#12 0x00000000020c5232 in std::_Function_handler<void (ql::changefeed::range_sub_t *), <lambda at src/rdb_protocol/changefeed.cc:2306:37> >::_M_invoke(const std::_Any_data &, ql::changefeed::range_sub_t *) (__functor=..., __args=0x7f03fbe24c00) at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:1778
#13 0x00000000020b35b8 in std::function<void (ql::changefeed::range_sub_t *)>::operator()(ql::changefeed::range_sub_t *) const (this=0x7f03a77efd08, __args=0x7f03fbe24c00)
    at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:2160
#14 0x00000000020b3312 in ql::changefeed::each_sub_in_vec_cb<ql::changefeed::range_sub_t>(std::function<void (ql::changefeed::range_sub_t *)> &, std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > &, std::vector<int, std::allocator<int> > &, int) (this=0x7f0390ffc100, f=..., 
    vec=std::vector of length 25, capacity 25 = {...}, subscription_threads=std::vector of length 1, capacity 1 = {...}, i=0) at src/rdb_protocol/changefeed.cc:2933
#15 0x00000000020b4149 in std::_Mem_fn<void (ql::changefeed::feed_t::*)(const std::function<void (ql::changefeed::range_sub_t *)> &, const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > &, const std::vector<int, std::allocator<int> > &, int)>::operator()(ql::changefeed::feed_t *, const std::function<void (ql::changefeed::range_sub_t *)> &, const std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > &, const std::vector<int, std::allocator<int> > &, int) const (this=0x7f03a77ef668, __object=0x7f0390ffc100, __args=0, __args=0, __args=0, __args=0)
    at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:550
#16 0x00000000020b406d in std::_Bind<std::_Mem_fn<void (ql::changefeed::feed_t::*)(const std::function<void (ql::changefeed::range_sub_t *)> &, const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > &, const std::vector<int, std::allocator<int> > &, int)> (ql::changefeed::feed_t *, std::reference_wrapper<const std::function<void (ql::changefeed::range_sub_t *)> >, std::reference_wrapper<const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > >, std::reference_wrapper<const std::vector<int, std::allocator<int> > >, std::_Placeholder<1>)>::__call_c<void, long&, 0, 1, 2, 3, 4>(<unknown type in /home/ssd3/daniel/rethinkdb/build/debug_clang/rethinkdb, CU 0x567e6f1, DIE 0x578de39>) const (this=0x7f03a77ef668, 
    __args=<unknown type in /home/ssd3/daniel/rethinkdb/build/debug_clang/rethinkdb, CU 0x567e6f1, DIE 0x578de39>)
    at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:1154
#17 0x00000000020b3f5d in std::_Bind<std::_Mem_fn<void (ql::changefeed::feed_t::*)(const std::function<void (ql::changefeed::range_sub_t *)> &, const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > &, const std::vector<int, std::allocator<int> > &, int)> (ql::changefeed::feed_t *, std::reference_wrapper<const std::function<void (ql::changefeed::range_sub_t *)> >, std::reference_wrapper<const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > >, std::reference_wrapper<const std::vector<int, std::allocator<int> > >, std::_Placeholder<1>)>::operator()<long &, void>(long &) const (this=0x7f03a77ef668, __args=@0x7f03a77ef518) at /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/functional:1217
#18 0x00000000020b3ee4 in pmap_runner_one_arg_t<std::_Bind<std::_Mem_fn<void (ql::changefeed::feed_t::*)(const std::function<void (ql::changefeed::range_sub_t *)> &, const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > &, const std::vector<int, std::allocator<int> > &, int)> (ql::changefeed::feed_t *, std::reference_wrapper<const std::function<void (ql::changefeed::range_sub_t *)> >, std::reference_wrapper<const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > >, std::reference_wrapper<const std::vector<int, std::allocator<int> > >, std::_Placeholder<1>)>, long>::operator()(void) (this=0x7f03a77ef518) at ./src/concurrency/pmap.hpp:20
#19 0x00000000020b3e19 in pmap<std::_Bind<std::_Mem_fn<void (ql::changefeed::feed_t::*)(const std::function<void (ql::changefeed::range_sub_t *)> &, const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > &, const std::vector<int, std::allocator<int> > &, int)> (ql::changefeed::feed_t *, std::reference_wrapper<const std::function<void (ql::changefeed::range_sub_t *)> >, std::reference_wrapper<const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > >, std::reference_wrapper<const std::vector<int, std::allocator<int> > >, std::_Placeholder<1>)> >(int64_t, int64_t, const std::_Bind<std::_Mem_fn<void (ql::changefeed::feed_t::*)(const std::function<void (ql::changefeed::range_sub_t *)> &, const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > &, const std::vector<int, std::allocator<int> > &, int)> (ql::changefeed::feed_t *, std::reference_wrapper<const std::function<void (ql::changefeed::range_sub_t *)> >, std::reference_wrapper<const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > >, std::reference_wrapper<const std::vector<int, std::allocator<int> > >, std::_Placeholder<1>)> &) (begin=0, end=1, c=...)
    at ./src/concurrency/pmap.hpp:47
#20 0x00000000020b30ba in pmap<std::_Bind<std::_Mem_fn<void (ql::changefeed::feed_t::*)(const std::function<void (ql::changefeed::range_sub_t *)> &, const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > &, const std::vector<int, std::allocator<int> > &, int)> (ql::changefeed::feed_t *, std::reference_wrapper<const std::function<void (ql::changefeed::range_sub_t *)> >, std::reference_wrapper<const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > >, std::reference_wrapper<const std::vector<int, std::allocator<int> > >, std::_Placeholder<1>)> >(int64_t, const std::_Bind<std::_Mem_fn<void (ql::changefeed::feed_t::*)(const std::function<void (ql::changefeed::range_sub_t *)> &, const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > &, const std::vector<int, std::allocator<int> > &, int)> (ql::changefeed::feed_t *, std::reference_wrapper<const std::function<void (ql::changefeed::range_sub_t *)> >, std::reference_wrapper<const std::vector<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> >, std::allocator<std::set<ql::changefeed::range_sub_t *, std::less<ql::changefeed::range_sub_t *>, std::allocator<ql::changefeed::range_sub_t *> > > > >, std::reference_wrapper<const std::vector<int, std::allocator<int> > >, std::_Placeholder<1>)> &) (count=1, c=...) at ./src/concurrency/pmap.hpp:53
#21 0x000000000208cbb9 in ql::changefeed::feed_t::each_sub_in_vec<ql::changefeed::range_sub_t>(std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > &, rwlock_in_line_t *, auto_drainer_t::lock_t &, std::function<void (ql::changefeed::range_sub_t *)> &) (this=0x7f0390ffc100, 
    vec=std::vector of length 25, capacity 25 = {...}, spot=0x7f03a77ef708, lock=..., f=...) at src/rdb_protocol/changefeed.cc:2921
#22 0x0000000002081434 in ql::changefeed::feed_t::each_range_sub(auto_drainer_t::lock_t &, std::function<void (ql::changefeed::range_sub_t *)> &) (this=0x7f0390ffc100, 
    lock=..., f=...) at src/rdb_protocol/changefeed.cc:2942
#23 0x00000000020c21f4 in ql::changefeed::msg_visitor_t::operator() (this=0x7f03a77f0098, change=...) at src/rdb_protocol/changefeed.cc:2306
#24 0x00000000020c2133 in boost::detail::variant::invoke_visitor<ql::changefeed::msg_visitor_t>::internal_visit<ql::changefeed::msg_t::change_t const> (this=0x7f03a77effa8, 
    operand=...) at /usr/local/include/boost/variant/variant.hpp:858
#25 0x00000000020c20fc in boost::detail::variant::visitation_impl_invoke_impl<boost::detail::variant::invoke_visitor<ql::changefeed::msg_visitor_t>, void const*, ql::changefeed::msg_t::change_t> (visitor=..., storage=0x7f03daa96020) at /usr/local/include/boost/variant/detail/visitation_impl.hpp:129
#26 0x00000000020c0a2f in boost::detail::variant::visitation_impl_invoke<boost::detail::variant::invoke_visitor<ql::changefeed::msg_visitor_t>, void const*, ql::changefeed::msg_t::change_t, boost::variant<ql::changefeed::msg_t::stop_t, ql::changefeed::msg_t::change_t, ql::changefeed::msg_t::limit_start_t, ql::changefeed::msg_t::limit_change_t, ql::changefeed::msg_t::limit_stop_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>::has_fallback_type_> (
    internal_which=1, visitor=..., storage=0x7f03daa96020, t=0x0) at /usr/local/include/boost/variant/detail/visitation_impl.hpp:170
#27 0x00000000020c05e5 in boost::detail::variant::visitation_impl<mpl_::int_<0>, boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_item<mpl_::long_<5>, ql::changefeed::msg_t::stop_t, boost::mpl::l_item<mpl_::long_<4>, ql::changefeed::msg_t::change_t, boost::mpl::l_item<mpl_::long_<3>, ql::changefeed::msg_t::limit_start_t, boost::mpl::l_item<mpl_::long_<2>, ql::changefeed::msg_t::limit_change_t, boost::mpl::l_item<mpl_::long_<1>, ql::changefeed::msg_t::limit_stop_t, boost::mpl::l_end> > > > > >, boost::mpl::l_iter<boost::mpl::l_end> >, boost::detail::variant::invoke_visitor<ql::changefeed::msg_visitor_t>, void const*, boost::variant<ql::changefeed::msg_t::stop_t, ql::changefeed::msg_t::change_t, ql::changefeed::msg_t::limit_start_t, ql::changefeed::msg_t::limit_change_t, ql::changefeed::msg_t::limit_stop_t, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>::has_fallback_type_> (internal_which=1, logical_which=1, visitor=..., storage=0x7f03daa96020, 
    no_backup_flag=...) at /usr/local/include/boost/variant/detail/visitation_impl.hpp:256
...
```

**Comment by danielmewes** [comment]
Core file, data directory and rethinkdb image are in `/home/daniel/4912_core` on newton.

**Comment by danielmewes** [comment]
Assigning @mlucy.

I took a very quick look at the core file, and it looks like the virtual `active()` method is resolved to address 0x1, which would suggest that the `range_sub_t` was in the middle of being either destructed or constructed.
At the same time it looks like we were holding a read lock on the `range_subs_lock` though, which I think should stop that from happening (I checked that the read signal was actually pulsed on the `rwlock_in_line_t`).

**Comment by mlucy** [comment]
I looked at the core file, and right now I'm thinking this might be memory corruption.

There are only 3 lines where we read from or write to `range_subs`.  In all three of those places we seem to be acquiring the lock correctly.  (We also have a drainer lock in the `msg_visitor_t`, so it isn't being destroyed by the `feed_t` being destroyed.)

Also, when I look at the core dump, the `env_t` pointer seems in the `range_sub_t` seems to have garbage in it (it has an invalid `return_empty_normal_batches` field and an `interruptor` of `0x4`).  That means we either have memory corruption, we aren't done constructing it, are we have already destructed it.

I'm mostly sure we aren't partway through constructing it because we only insert `range_sub_t`s into `range_subs` after they're done being constructed (we call `add_sub_with_lock`).

I'm less sure it hasn't been destructed, but the `drainer` on the `range_sub_t` isn't pulsed.  (It's possible, of course, that the object was destroyed and then garbage data written to where the drainer is, but the drainer looks otherwise valid.)

@danielmewes -- do we ever run the fuzzer against the server under valgrind?

**Comment by danielmewes** [comment]
@mlucy 
> do we ever run the fuzzer against the server under valgrind?

I don't think we have. I can try to get that running.

**Comment by danielmewes** [comment]
For the record: it looks like these are the steps required for running it in Valgrind:
```
$ ./configure --with-system-malloc
$ make VALGRIND=1
$ cd some directory to store the data directories in
$ table_fuzzer.py --valgrind --valgrind-options "--suppressions=/home/daniel/rethinkdb/scripts/rethinkdb-valgrind-suppressions.supp"
```

**Comment by mlucy** [comment]
This might be caused by https://github.com/rethinkdb/rethinkdb/issues/5074 .

**Comment by danielmewes** [comment]
We haven't seen this again. I'm going to close it as a duplicate of #5074 in the hope that fixing #5074 will also fix the cause of this..
