### ISSUE TITLE
Unexpected unicode error while insert [ Python , tornado driver]

### ISSUE THREAD

**Issue by v3ss0n** [rethinkdb/rethinkdb#4915]
```            
yield self.cache.insert(dict(id=path, response=response.body,
                                         code=response.code, headers=response.headers, 
```
the data (response) is http response and it can contain mixed unicode data , that is python's biggest enemies.
```time_taken=response.request_time)).run()
Traceback (most recent call last):
  File "/home/v3ss/pypy/site-packages/tornado-4.2-py2.7.egg/tornado/web.py", line 1415, in _execute
    result = yield result
  File "/home/v3ss/pypy/site-packages/tornado-4.2-py2.7.egg/tornado/gen.py", line 870, in run
    value = future.result()
  File "/home/v3ss/pypy/site-packages/tornado-4.2-py2.7.egg/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/home/v3ss/pypy/site-packages/tornado-4.2-py2.7.egg/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/v3ss/workspace/connectover/handlers/proxies.py", line 123, in get
    code=response.code, headers=response.headers, time_taken=response.request_time)).run()
  File "/home/v3ss/pypy/site-packages/tornado-4.2-py2.7.egg/tornado/gen.py", line 870, in run
    value = future.result()
  File "/home/v3ss/pypy/site-packages/tornado-4.2-py2.7.egg/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/home/v3ss/pypy/site-packages/tornado-4.2-py2.7.egg/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "build/bdist.linux-x86_64/egg/rethinkdb/net_tornado.py", line 256, in _start
    res = yield ConnectionBase._start(self, *args, **kwargs)
  File "/home/v3ss/pypy/site-packages/tornado-4.2-py2.7.egg/tornado/gen.py", line 870, in run
    value = future.result()
  File "/home/v3ss/pypy/site-packages/tornado-4.2-py2.7.egg/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/home/v3ss/pypy/site-packages/tornado-4.2-py2.7.egg/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "build/bdist.linux-x86_64/egg/rethinkdb/net_tornado.py", line 177, in run_query
    yield self._stream.write(query.serialize())
  File "build/bdist.linux-x86_64/egg/rethinkdb/net.py", line 77, in serialize
    query_str = json.dumps(message, ensure_ascii=False, allow_nan=False).encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2269: ordinal not in range(128)
```

**Comment by danielmewes** [comment]
@v3ss0n Can you verify separately that the data is valid UTF-8 / Unicode?

Does it work if you use `r.binary` for the data?

**Comment by v3ss0n** [comment]
Going to test with r.binary.

**Comment by danielmewes** [comment]
@v3ss0n Did this work with `r.binary`?
I'm closing the issue for now, but feel free to re-open if there's still an issue.
