### ISSUE TITLE
Python Driver ReqlDriverError: Connection Closed using Changefeeds

### ISSUE THREAD

**Issue by jyapayne** [rethinkdb/rethinkdb#4961]
I have been experiencing this issue on and off and it's a really annoying one because it happens on a background task that is supposed to be running forever in order to rate calls.

Basically, when using Tornado and the Python driver to have multiple changefeeds running at the same time in one python module, every so often this error will occur:

```
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7f4dccc53310>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 592, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 598, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/merged_octo/octopod/callrating/call_rating_feed.py", line 46, in check_historic_calls_rating
    yield self.rate_call(not_rated_call)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/merged_octo/octopod/callrating/call_rating_feed.py", line 317, in rate_call
    rated_calls = yield other_leg_query.run(conn, **DB_RUN_ARGS)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "build/bdist.linux-x86_64/egg/rethinkdb/net_tornado.py", line 256, in _start
    res = yield ConnectionBase._start(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "build/bdist.linux-x86_64/egg/rethinkdb/net_tornado.py", line 183, in run_query
    res = yield response_future
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
ReqlDriverError: Connection is closed (Unexpected response received.).
```

The error is random and happens at a random point in my code every time, so I don't think this is an issue with my code. I'm running the latest 2.1.5 release on a Ubuntu 14.04 server.

**Comment by danielmewes** [comment]
Thanks for reporting this @jyapayne and sorry you have to deal with this issue.

That sounds like either something gets messed up in the driver when it's reading from the socket, or the server somehow is sending an invalid response.

We'll look into it.

(mentioning @Tryneus, who might have some ideas)

**Comment by danielmewes** [comment]
@jyapayne Sorry we haven't made any progress on this yet. Are you still experiencing the issue?
You might also want to make sure that you're not using the same connection from multiple threads.

@Tryneus Can you think of any race conditions that could happen in the Python Tornado backend? Maybe if the read of a response requires multiple reads from the socket or something like that?

**Comment by kukoman** [comment]
i've got the same issue... it seems like intermittent problem when I occasionally get that error, using python and nodejs, not sure if the error comes from node or python though :(

**Comment by AtnNn** [comment]
Is your python code multithreaded? The "Unexpected response received" error may indicate that you are using the RethinkDB connection simultaneously on multiple threads.

**Comment by srh** [comment]
Closing because it's old and I'm not going to solve it with the info here.  Feel free to reopen if you experience this again or have more information, or if you want it open.

**Comment by Ekwinder** [comment]
Did anyone find a solution for this? have been facing this issue a lot recently.

**Comment by gabor-boros** [comment]
>Did anyone find a solution for this? have been facing this issue a lot recently. ...

@Ekwinder is this still an issue for you if you still use RethinkDB? I mean with the latest driver and DB. 

If not (using it or not reproducible), I’ll close the issue since it is hrs to reproduce even if still exists.
