### ISSUE TITLE
ReqlRuntimeError: Index out of bounds

### ISSUE THREAD

**Issue by llambda** [rethinkdb/rethinkdb#5021]
Am I doing something wrong in my query? My query is below. It works for certain data but not others...I am guessing there is a null entry somewhere.

```
return r.table('vehicles').orderBy('name').filter({orgid: orgid})
	.limit(40)
	.merge(function (vehicle) {
		return {
			last: r.table('vehiclehistory').getAll(vehicle('id'), {index:'vid'}).orderBy(r.desc('id')).limit(1).coerceTo('array').nth(0)
		}
	})
```

```
 ReqlRuntimeError: Index out of bounds: 0 in:
  r.table("vehicles").orderBy("name").filter({
      orgid: "default"
  }).limit(40).merge(function(var_1) {
      return {
          last: r.table("vehiclehistory").getAll(var_1("id"), {
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              index: "vid"
              ^^^^^^^^^^^^
          }).orderBy(r.desc("id")).limit(1).coerceTo("array").nth(0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      }
  })
  
      at Connection._processResponse (/home/u/agilegps/node_modules/rethinkdbdash/lib/connection.js:229:19)
      at Socket.<anonymous> (/home/u/agilegps/node_modules/rethinkdbdash/lib/connection.js:150:14)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
  From previous event:
      at Object.<anonymous> (/home/u/agilegps/app/web/lib/app.js:284:39)
      at next (native)
      at onFulfilled (/home/u/agilegps/node_modules/co/index.js:65:19)
      at /home/u/agilegps/node_modules/co/index.js:54:5
      at Object.co (/home/u/agilegps/node_modules/co/index.js:50:10)
      at Object.toPromise (/home/u/agilegps/node_modules/co/index.js:118:63)
      at next (/home/u/agilegps/node_modules/co/index.js:99:29)
      at onFulfilled (/home/u/agilegps/node_modules/co/index.js:69:7)
      at /home/u/agilegps/node_modules/co/index.js:54:5
      at Object.co (/home/u/agilegps/node_modules/co/index.js:50:10)
      at Object.toPromise (/home/u/agilegps/node_modules/co/index.js:118:63)
      at next (/home/u/agilegps/node_modules/co/index.js:99:29)
      at onFulfilled (/home/u/agilegps/node_modules/co/index.js:69:7)
      at process._tickCallback (node.js:366:9)
```

**Comment by llambda** [comment]
Oh i need .default({}) at the end...never mind.
