### ISSUE TITLE
rethinkdb.ast.RqlQuery in (nonempty container) is always True

### ISSUE THREAD

**Issue by jab** [rethinkdb/rethinkdb#5079]
```
Python 3.5.0 (default, Sep 14 2015, 00:19:46)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rethinkdb as r
>>> r.uuid() in ('foo', 'bar', 'baz')
True
>>> r.now() in [False]
True
```
Without looking at the code I'm guessing this is because RqlQuery overrides `__eq__` to return some ast syntax. Python calls `__eq__` against the first member of the container, and when it gets a truthy value, it considers them equivalent and so the containment check returns True.

Ideally we could get this to behave as expected without messing up the ast magic.

**Comment by danielmewes** [comment]
Ah interesting catch.
@Tryneus @larkost any ideas for avoiding this behavior?

**Comment by deontologician** [comment]
We could override `__contains__` to customize the `in` operator's behavior to avoid the ast-returning `__eq__` implementation

This is a weird operation though, since I don't think we really worry about what equality for a reql ast is. We should probably just override `__contains__` to throw an error since it shouldn't be used like that.

**Comment by jab** [comment]
Consider something like:
```python
def create_user(**kw):
    kw.setdefault('created', r.now())
    kw.setdefault('authtoken', r.uuid())
    r.table('user').insert({k: v for (k, v) in kw.items() if v not in (None, False, '')}).run(conn)
```
This code wants to be able to check values like `r.now()` for containment in `(None, False, '')`. (This application treats a field with value `None`, `False`, or `''` as equivalent to the field being absent, and prefers to normalize using the latter. However fields with values like `[]` or `{}` should be preserved, hence the containment check rather than `{k: v for (k, v) in kw.items() if v}`.)

Making `__contains__` throw an error would prevent this construction. Would you prefer to support this?

**Comment by deontologician** [comment]
Well the issue here is what kind of equality to support (object or value) and whether we should only support it for the `in` operator, since we don't support it for the `==` operator. In other words, even if we did this, you still couldn't write code like this:

```python
def create_user(**kw):
    kw.setdefault('created', r.now())
    kw.setdefault('authtoken', r.uuid())
    r.table('user').insert({k: v for (k, v) in kw.items() if v != '' ).run(conn)
```

The workaround would be to strip out the keys you don't want before adding reql terms to the dict

```python
def create_user(**kw):
    stripped = {k: v for k, v in kw.items() if v not in ('', None, False)}
    stripped.setdefault('created', r.now())
    stripped.setdefault('authtoken', r.uuid())
    r.table('user').insert(stripped).run(conn)
```

I would say in the vast majority of cases where someone invokes `__contains__` it would probably be when they're trying to write a query like `r.table(foo).map(r.row['bar'] in [1,2,3])` or something like it, and they'll run into the fact that we don't translate `__contains__` into the reql term `.contains()` (because it doesn't allow you to return arbitrary objects like the arithmetic and comparison methods do). In that case, it would be nice to get a helpful warning that you should use `.contains()` instead.

**Comment by jab** [comment]
FWIW, this particular user would have known to write `.contains()` instead of `in` in your example, but got bit by the above (and ended up with the same workaround you proposed). In any case, raising an error sounds like a more principled fix, and even though it wouldn't allow the code I quoted, at least it would fail loudly, so +1 on the error. Thanks for taking a look at this :)

**Comment by AtnNn** [comment]
This could be solved using `__bool__` in Python 3 and `__nonzero__` in Python 2:

```
class C:
 def __bool__(self):
  raise Exception("Nope!")
 def __eq__(self, x):
  return C()
```

```
>>> C() in [1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __bool__
Exception: Nope!
```

**Comment by danielmewes** [comment]
+1 on erroring for `in` tests, and probably for other thruthness tests on RqlQuery as well (like in @AtnNn's solution).
