### ISSUE TITLE
Ensure PartialLst is implemented correctly in Java driver's TestingCommon

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5152]
See @bchavez 's comment [here](https://github.com/rethinkdb/rethinkdb/commit/a4bc218cf0ebafb928338aa492e77e4c46061bee#commitcomment-14629333)

**Comment by bchavez** [comment]
Also, protocol wise, the test seems a bit strange. I can't get back any error response from the server with this particular test... The driver sends a `CONTINUE` and the server happily sends back **197** changes.

```
{
  "t": 3,
  "r": [ //197 changes// ],
  "n": [
    1
  ]
}
```

No error that I can see anywhere in the response. **"Changefeed cache over array size limit, skipped..."** Maybe this is a **vnext** thing?

**Comment by deontologician** [comment]
Is the `changefeed_queue_size` option being passed to run on the subscription?

**Comment by bchavez** [comment]
Oh thanks... I missed a change in `templates\Test.java`. Also, I did some extra testing with Java, the regex does seem to hit `.equals`.
```
java.lang.RuntimeException: FOOBAR
	at gen.TestingCommon$Regex.equals(TestingCommon.java:253)
	at java.util.AbstractMap.equals(AbstractMap.java:472)
	at java.util.ArrayList.indexOf(ArrayList.java:317)
	at gen.TestingCommon$PartialLst.equals(TestingCommon.java:89)
	at org.junit.Assert.isEquals(Assert.java:131)
	at org.junit.Assert.equalsRegardingNull(Assert.java:127)
	at org.junit.Assert.assertEquals(Assert.java:111)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at gen.ChangefeedsTable.test(ChangefeedsTable.java:322)
```
Sorry for the noise. :X

**Comment by deontologician** [comment]
@bchavez so you don't think this is an issue then?

**Comment by bchavez** [comment]
correct, the java driver test is okay :)

**Comment by deontologician** [comment]
thanks!
