### ISSUE TITLE
unable-to-build-android-project-with-rethinkdb-java-driver

### ISSUE THREAD

**Issue by vijayakumarn** [rethinkdb/rethinkdb#5253]
RethinkDB java driver : compile (group: 'com.rethinkdb', name: 'rethinkdb-driver', version: '2.2-beta-1')

I created a simple Android studio project & included the above mentioned gradle dependency.
The project doesn't build at all. The project builds successfully IF i remove the rethinkdb dependency.
In short rethinkdb driver is NOT usable in android studio/device.

This is the exception I get:
:app:transformClassesWithDexForDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
    at com.android.dx.command.dexer.Main.processClass(Main.java:752)
    at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
    at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
    at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
    at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    at com.android.dx.command.dexer.Main.processOne(Main.java:672)
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
    at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
    at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
    at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
    at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
    at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
    at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
    at com.android.dx.command.dexer.Main.processClass(Main.java:749)
    ... 12 more
1 error; aborting

**Comment by vijayakumarn** [comment]
I tried building the android grade project using both Java 6 and 7 , but it fails.
Note: Java 8 is not supported in Android Studio.

**Comment by bchavez** [comment]
Currently, the Java driver is only compatible with Java 8. See this blog post:

https://www.rethinkdb.com/blog/official-java-driver/

Additionally, the GitHub issue on the subject:

https://github.com/rethinkdb/rethinkdb/issues/3930#issuecomment-94911187

The primary reason is the official Java 8 requirement is lambda support. There was enthusiasm for additional Java 7 (or lower) support. 

However, as Daniel suggests, you could try this Java (unofficial) driver for now:

https://github.com/dropbox/rethink-java-driver

**Comment by deontologician** [comment]
The drop box driver won't work with RethinkDB 2.2+, since we removed protocol buffer support

**Comment by danielmewes** [comment]
I opened https://github.com/rethinkdb/rethinkdb/issues/5266 to give Java 7 support another consideration. I'll mark this as `notabug` in favor of the new Java 7 issue.

@vijayakumarn Can you share a bit more about your use case for this?
It's not common to access a RethinkDB database server directly from an Android app, since that will mean having to expose the RethinkDB server to the public. I can see this being useful for internal applications though, or when being in a VPN.
