### ISSUE TITLE
Error: No JSON object could be decoded

### ISSUE THREAD

**Issue by muriloventuroso** [rethinkdb/rethinkdb#5630]
RethinkDB installed on a Debian, but I'm getting an error message when connecting by Python 2.7:

`>>> import rethinkdb as r
>>> r.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 661, in connect
    return conn.reconnect(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 572, in reconnect
    return self._instance.connect(timeout)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 427, in connect
    self._socket = SocketWrapper(self, timeout)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 322, in __init__
    (self.host, self.port, ex))
rethinkdb.errors.ReqlDriverError: Could not connect to localhost:28015. Error: No JSON object could be decoded`

The web interface can access and manipulate the data normally.

**Comment by NeckBeardPrince** [comment]
The problem was the rethinkdb driver. The installed driver was 2.3.0 but the server installed was 2.2.5.
Doing this fixed my issue.

`sudo pip uninstall rethinkdb`
`sudo pip install 'rethinkdb==2.2.0.post5'`

**Comment by muriloventuroso** [comment]
It worked. Thanks buddy
