### ISSUE TITLE
NameError: global name 'options' is not defined when importing from file

### ISSUE THREAD

**Issue by JasonSoares** [rethinkdb/rethinkdb#5637]
Running the following command, results in an error producing the following stacktrace:

**command (example)**
`$ rethinkdb import -f data/bars.json --table foo.bar`

**stacktrace**
Traceback (most recent call last):
  File "/usr/local/bin/rethinkdb-import", line 9, in <module>
    load_entry_point('rethinkdb==2.3.0', 'console_scripts', 'rethinkdb-import')()
  File "/usr/local/lib/python2.7/site-packages/rethinkdb/_import.py", line 929, in main
    import_file(options)
  File "/usr/local/lib/python2.7/site-packages/rethinkdb/_import.py", line 904, in import_file
    pkey = rdb_call_wrapper(conn_fn, "table check", table_check, db, table, options["create_args"], options["force"])
  File "/usr/local/lib/python2.7/site-packages/rethinkdb/_backup.py", line 78, in rdb_call_wrapper
    return fn(progress, conn, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rethinkdb/_import.py", line 885, in table_check
    if not options["quiet"]:
NameError: global name 'options' is not defined`

**Comment by JasonSoares** [comment]
PR submitted: #5638.

**Comment by mlucy** [comment]
Thanks for the report / PR @JasonSoares !

@Tryneus, you maintain the import script, right?
