### ISSUE TITLE
Java Driver: Connection is lost during changes(), never times out.

### ISSUE THREAD

**Issue by mschurr** [rethinkdb/rethinkdb#5660]
My code is essentially:

```java
try (Connection conn = dbp.getConnection()) {
  Cursor<HashMap<String, ?>> cursor = r.table("messages").changes().run(conn);
  for (HashMap<String, ?> item : cursor) {
    .. do stuff ...
  }
}
```

I connected to the server and was successfully listening to changes. Then, I killed the database server (only a single instance was running). As far as I can tell, the Java driver does not break the for loop when the connection is lost it just keeps sitting there expecting more data forever. There doesn't appear to be any timeout period. And, obviously, if I restart the database server then changes don't start coming in again on that old cursor.

So my question is: how are we supposed to detect connection losses and recover from them if the driver just sits there in the loop?

**Comment by mlucy** [comment]
ping @deontologician .

**Comment by deontologician** [comment]
I am not actually sure why it wouldn't raise an exception if the socket is closed. Maybe it's swallowing the error.

**Comment by mschurr** [comment]
I'm not entirely sure. I wrapped the loop in a try-catch block that catches and logs all exceptions and I'm definitely not getting any exceptions. I waited ~5 minutes after I terminated the server to see if it would eventually time out and throw an exception, but I got nothing.

I'm using the latest version of the drivers (through Maven) and the latest version of the server (on Ubuntu installed through apt-get).

**Comment by bchavez** [comment]
Hi @mschurr , is it possible for you to enable debug driver logging? If you could provide the full log and after about 5 minutes the disconnection happens, maybe the logs could reveal some clues. :mag:

**Comment by mschurr** [comment]
Sure. What do I need to do in order to enable that?

**Comment by mschurr** [comment]
Sure, I have attached the debug logs. I inserted an item from the web UI before terminating the server and you can see that change shows up in the logs, so the change feed was working initially. The server was terminated roughly at `04:47:00`. I waited until roughly `04:57:00` (10 minutes) before capturing the logs - as you can see, nothing happened in the logs between when I terminated the server and then.

The logs:

```
04:45:31.251 [main] DEBUG d.SimpleTest - Channel opening...
04:45:31.900 [main] DEBUG c.r.a.Query - JSON Send: Token: 1 [1,[152,[[15,["messages"]]]],{"db":[14,["chatapp"]]}]
04:45:31.918 [pool-1-thread-1] DEBUG c.r.a.Query - JSON Recv: Token: 1 {"t":3,"r":[],"n":[1]}
04:45:32.059 [main] DEBUG c.r.a.Query - JSON Send: Token: 1 [2]
04:46:57.058 [pool-1-thread-1] DEBUG c.r.a.Query - JSON Recv: Token: 1 {"t":3,"r":[{"new_val":{"id":"8a1ae685-ef92-4219-b053-6b0d06a8670f","message":"Hello!","name":"Bob","time":0},"old_val":null}],"n":[1]}
04:46:57.065 [main] DEBUG d.SimpleTest - Channel received {new_val={name=Bob, id=8a1ae685-ef92-4219-b053-6b0d06a8670f, time=0, message=Hello!}, old_val=null}
04:46:57.065 [main] DEBUG c.r.a.Query - JSON Send: Token: 1 [2]
```

The complete code of my test:

```java
package demo;

import static com.rethinkdb.RethinkDB.r;

import java.util.HashMap;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.rethinkdb.RethinkDB;
import com.rethinkdb.net.Connection;
import com.rethinkdb.net.Cursor;

public class SimpleTest {
  private static final Logger logger = LoggerFactory.getLogger(SimpleTest.class);
  
  public static void main(String[] args) throws Exception {    
    logger.debug("Channel opening...");
    try (Connection conn = 
        RethinkDB.r.connection().hostname("localhost").port(28015).db("chatapp").connect()) {
      Cursor<HashMap<String, ?>> cursor = null;
      try {
        cursor = r.table("messages").changes().run(conn);
        
        for (HashMap<String, ?> item : cursor) {
          logger.debug("Channel received {}", item);            
        }
      } finally {
        if (cursor != null) {
          cursor.close();
        }
      }
    }
  }
}
```

**Comment by bchavez** [comment]
Maybe, try creating two threads: **Thread A** and **Thread B**. Have **Thread A** listen for changes and later have **Thread B** close the connection. **Thread A** *should* wake up exceptionally from blocking.

Something like:
```
Connection conn;

Main(){
   this.conn = RethinkDB.r.connection().....connect();
   ThreadA.Start(Listener);
   ThreadB.Start(Closer)
}

Listener{
   // the blocking change feed code in your sample code
}

Closer{
   ThreadB.Sleep(2 minutes); //maybe add some changes
   Log("closing connection manually");
   this.conn.close();
   Log("closed.");
   ThreadB.Sleep(3 minutes);
   Log("ThreadB closer done.");
}
```
Quick sanity check would make sure the basic plumbing is working.

**Comment by mschurr** [comment]
I can confirm that closing the connection manually breaks the loop. Program and logs attached.

```
17:45:18.160 [Thread-0] DEBUG d.SimpleTest - Thread A listening for changes...
17:45:18.228 [Thread-0] DEBUG c.r.a.Query - JSON Send: Token: 1 [1,[152,[[15,["messages"]]]],{"db":[14,["chatapp"]]}]
17:45:18.243 [pool-1-thread-1] DEBUG c.r.a.Query - JSON Recv: Token: 1 {"t":3,"r":[],"n":[1]}
17:45:18.373 [Thread-0] DEBUG c.r.a.Query - JSON Send: Token: 1 [2]
17:45:48.159 [Thread-1] DEBUG d.SimpleTest - Thread B: Inserting first change.
17:45:48.161 [Thread-1] DEBUG c.r.a.Query - JSON Send: Token: 2 [1,[56,[[15,["messages"]],[3,[],{"name":"Example","message":"Hello World! (1)","time":0}]]],{"db":[14,["chatapp"]]}]
17:45:48.169 [pool-1-thread-1] DEBUG c.r.a.Query - JSON Recv: Token: 1 {"t":3,"r":[{"new_val":{"id":"438e9428-2f91-45f8-b9cd-170556675f4f","message":"Hello World! (1)","name":"Example","time":0},"old_val":null}],"n":[1]}
17:45:48.175 [pool-1-thread-1] DEBUG c.r.a.Query - JSON Recv: Token: 2 {"t":1,"r":[{"deleted":0,"errors":0,"generated_keys":["438e9428-2f91-45f8-b9cd-170556675f4f"],"inserted":1,"replaced":0,"skipped":0,"unchanged":0}]}
17:45:48.176 [Thread-0] DEBUG d.SimpleTest - Thread A received change: {new_val={name=Example, id=438e9428-2f91-45f8-b9cd-170556675f4f, time=0, message=Hello World! (1)}, old_val=null}
17:45:48.176 [Thread-0] DEBUG c.r.a.Query - JSON Send: Token: 1 [2]
17:46:18.177 [Thread-1] DEBUG d.SimpleTest - Thread B: Inserting second change.
17:46:18.177 [Thread-1] DEBUG c.r.a.Query - JSON Send: Token: 3 [1,[56,[[15,["messages"]],[3,[],{"name":"Example","message":"Hello World! (2)","time":0}]]],{"db":[14,["chatapp"]]}]
17:46:18.179 [pool-1-thread-1] DEBUG c.r.a.Query - JSON Recv: Token: 1 {"t":3,"r":[{"new_val":{"id":"de0f224c-764a-4ea2-a22d-f1e10b0854cf","message":"Hello World! (2)","name":"Example","time":0},"old_val":null}],"n":[1]}
17:46:18.180 [Thread-0] DEBUG c.r.a.Query - JSON Send: Token: 1 [2]
17:46:18.180 [Thread-0] DEBUG d.SimpleTest - Thread A received change: {new_val={name=Example, id=de0f224c-764a-4ea2-a22d-f1e10b0854cf, time=0, message=Hello World! (2)}, old_val=null}
17:46:18.188 [pool-1-thread-1] DEBUG c.r.a.Query - JSON Recv: Token: 3 {"t":1,"r":[{"deleted":0,"errors":0,"generated_keys":["de0f224c-764a-4ea2-a22d-f1e10b0854cf"],"inserted":1,"replaced":0,"skipped":0,"unchanged":0}]}
17:46:48.189 [Thread-1] DEBUG d.SimpleTest - Thread B: Dropping connection.
17:46:48.199 [Thread-0] DEBUG d.SimpleTest - Thread A failed: 
com.rethinkdb.gen.exc.ReqlDriverError: java.util.concurrent.CancellationException
	at com.rethinkdb.net.Cursor.waitOnCursorItems(Cursor.java:102) ~[rethinkdb-driver-2.3.0.jar:na]
	at com.rethinkdb.net.Cursor$DefaultCursor.getNext(Cursor.java:186) ~[rethinkdb-driver-2.3.0.jar:na]
	at com.rethinkdb.net.Cursor.next(Cursor.java:124) ~[rethinkdb-driver-2.3.0.jar:na]
	at demo.SimpleTest2$1.run(SimpleTest2.java:38) ~[classes/:na]
Caused by: java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(Unknown Source) ~[na:1.8.0_11]
	at com.rethinkdb.net.Connection.lambda$close$2(Connection.java:161) ~[rethinkdb-driver-2.3.0.jar:na]
	at com.rethinkdb.net.Connection$$Lambda$1/1784662007.accept(Unknown Source) ~[na:na]
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_11]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:1.8.0_11]
	at com.rethinkdb.net.Connection.close(Connection.java:156) ~[rethinkdb-driver-2.3.0.jar:na]
	at com.rethinkdb.net.Connection.close(Connection.java:136) ~[rethinkdb-driver-2.3.0.jar:na]
	at demo.SimpleTest2$2.run(SimpleTest2.java:69) ~[classes/:na]
17:47:18.192 [Thread-1] DEBUG d.SimpleTest - Thread B: Quiting.
17:47:18.192 [main] DEBUG d.SimpleTest - Workers joined, exiting.
```

```java
package demo;

import static com.rethinkdb.RethinkDB.r;

import java.util.HashMap;
import java.util.concurrent.TimeUnit;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.rethinkdb.net.Connection;
import com.rethinkdb.net.Cursor;

/**
 * Run in the web UI to add a row and get notified:
 * r.db("chatapp").table("messages").insert({"name": "Bob", "time": 0, "message": "Hello!"})
 */
public class SimpleTest2 {
  private static final Logger logger = LoggerFactory.getLogger(SimpleTest.class);
  
  public static void main(String[] args) throws Exception {    
    final Connection conn = r.connection()
        .hostname("localhost")
        .port(28015)
        .db("chatapp")
        .connect();
    
    Thread A = new Thread() {
      @Override
      public void run() {
        try {
          Cursor<HashMap<String, ?>> cursor = null;
          
          try {
            logger.debug("Thread A listening for changes...");
            cursor = r.table("messages").changes().run(conn);
            
            for (HashMap<String, ?> item : cursor) {
              logger.debug("Thread A received change: {}", item);            
            }
          } finally {
            if (cursor != null) {
              cursor.close();
            }
          }
        } catch (Exception e) {
          logger.debug("Thread A failed: ", e);
        }
      }
    };
    
    Thread B = new Thread() {
      public void run() {
        try {
          Thread.sleep(TimeUnit.SECONDS.toMillis(30));
          logger.debug("Thread B: Inserting first change.");
          r.table("messages").insert(
              r.hashMap("name", "Example")
              .with("message", "Hello World! (1)")
              .with("time", 0)).run(conn);
          Thread.sleep(TimeUnit.SECONDS.toMillis(30));
          logger.debug("Thread B: Inserting second change.");
          r.table("messages").insert(
              r.hashMap("name", "Example")
              .with("message", "Hello World! (2)")
              .with("time", 0)).run(conn);
          Thread.sleep(TimeUnit.SECONDS.toMillis(30));
          logger.debug("Thread B: Dropping connection.");
          conn.close();
          Thread.sleep(TimeUnit.SECONDS.toMillis(30));
          logger.debug("Thread B: Quiting.");
        } catch (Exception e) {
          logger.debug("Thread B failed: ", e);
        }
      }
    };
    
    A.start();
    B.start();
    A.join();
    B.join();
    logger.debug("Workers joined, exiting.");
  }
}
```

**Comment by bchavez** [comment]
Hey @mschurr , thanks for that. That helps a lot.

I'm gonna take a shot in the dark on this one. Java skills are rusty, so I need help on this one.

The exception handler in the response pump looks like:

[`Connection.java`:**Line 115**](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L115)
```
try {
    final Response response = this.socket.orElseThrow(() -> new ReqlDriverError("No socket available.")).read();
    final CompletableFuture<Response> awaiter = awaiters.remove(response.token);
    if (awaiter != null) {
        awaiter.complete(response);
    }
} catch (IOException e) {
    awaiterException = e;
    this.close();
    break;
}
```
The handler only handles `IOException e`, but following the call chain for `this.socket.read()` down to [`SocketWrapper.java`](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/SocketWrapper.java#L142)
```
Response read() throws IOException {
    final ByteBuffer header = readBytesToBuffer(12);
    final long token = header.getLong();
    final int responseLength = header.getInt();
    return Response.parseFrom(token, readBytesToBuffer(responseLength).order(ByteOrder.LITTLE_ENDIAN));
}

private ByteBuffer readBytesToBuffer(int bufsize) throws IOException {
    byte[] buf = new byte[bufsize];
    int bytesRead = 0;
    while (bytesRead < bufsize) {
        final int res = this.readStream.read(buf, bytesRead, bufsize - bytesRead);
        if (res == -1) {
            throw new ReqlDriverError("Reached the end of the read stream.");
        } else {
            bytesRead += res;
        }
    }
    return ByteBuffer.wrap(buf).order(ByteOrder.LITTLE_ENDIAN);
}
```

`read()` calls `readBytesToBuffer()`. Seems like `readBytesToBuffer()` can also `throw new ReqlDriverError()` exceptions, not just `IOException`s. Hm...

If something other than a `IOException` was thrown what would happen to the unchecked exception in the top level handler? Would the executor response pump just bail out and never `.close()` for clean up? Maybe make the exception handler handle a more general `Exception e` instead of `IOException e`? 

Sorry if this makes no sense in Java land it's hard to test without my work computer. :crying_cat_face:  @mschurr, if you have the ability to rebuild the driver try making the change and see what happens?

Brian

**Comment by mschurr** [comment]
Hmm. I think you're right. It seems possible for a RuntimeException to be thrown there that doesn't get caught by the catch block (since ReqlError <: RuntimeException), and that is what it looks like gets thrown when the socket reaches EOF. 

I believe in this case the error will get swallowed; the `ExecutorService::submit` returns a future. The swallowed exception, in this case, will be re-thrown as a `ConcurrentExecutionException` with a `getCause()` of `ReqlError` when the future is waited upon - but your code isn't waiting on the future anywhere.

**Comment by bchavez** [comment]
Related #5439.
