### ISSUE TITLE
"Cursor is closed" since upgrading to node 6.0.0.

### ISSUE THREAD

**Issue by iameli** [rethinkdb/rethinkdb#5738]
I wish I had more to add, but I'm not really sure how to track this thing down.

```
/home/root/code/pratty-apps/apps/bellamie/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
ReqlDriverError: Cursor is closed.
    at ReqlDriverError.ReqlError [as constructor] (/home/root/code/pratty-apps/apps/bellamie/node_modules/rethinkdb/errors.js:23:13)
    at new ReqlDriverError (/home/root/code/pratty-apps/apps/bellamie/node_modules/rethinkdb/errors.js:68:50)
    at Feed.IterableResult._promptNext (/home/root/code/pratty-apps/apps/bellamie/node_modules/rethinkdb/cursor.js:128:10)
    at /home/root/code/pratty-apps/apps/bellamie/node_modules/rethinkdb/cursor.js:200:22
    at tryCatcher (/home/root/code/pratty-apps/apps/bellamie/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.fromNode (/home/root/code/pratty-apps/apps/bellamie/node_modules/bluebird/js/main/promise.js:165:30)
    at Feed.<anonymous> (/home/root/code/pratty-apps/apps/bellamie/node_modules/rethinkdb/cursor.js:203:20)
    at Feed._next (/home/root/code/pratty-apps/apps/bellamie/node_modules/rethinkdb/util.js:43:16)
    at Feed.<anonymous> (/home/root/code/pratty-apps/apps/bellamie/node_modules/rethinkdb/cursor.js:268:17)
    at Feed.<anonymous> (/home/root/code/pratty-apps/apps/bellamie/node_modules/rethinkdb/util.js:43:16)
    at Timeout._onTimeout (/home/root/code/pratty-apps/apps/bellamie/node_modules/rethinkdb/cursor.js:421:24)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

I'm getting that error intermittently since switching from node 5.9.1 to node 6.0.0. I don't appear to have any code in that stack trace... let me know if there's anything else you'd like me to do to help track it down. For now I'm just throwing it here to help other folks googling.

**Comment by danielmewes** [comment]
Thanks for the issue report @iameli . Do you remember from which RethinkDB driver version you upgraded?

@iameli Which API functions are you using in your application for iterating over cursors? `each`, `eachAsync`, `eventEmitter`s?

In the 2.3.0 driver, we changed the behavior of cursors a little bit. Reading from a cursor now always generates an error if either the cursor or the underlying RethinkDB connection have previously been closed. In the old version, reading from a cursor after closing the connection (or cursor) would sometimes still work, and only fail if the cursor needed to retrieve additional results.
The new behavior is more consistent, but if your application (unintentionally?) relied on the old behavior, this change could explain the failures you are now seeing.

**Comment by iameli** [comment]
Thanks for the thorough response. I've confirmed that I only encounter the problem upon upgrading to Rethink 2.3.0 -- node 6 doesn't appear to be the culprit. I've changed the title of the issue appropriately.

The server is a relatively straightforward JSON REST API server, with the nice added feature of being able to listen for changes over a websocket. I've excerpted the relevant methods in a Gist [here](https://gist.github.com/iameli/971117560d5a5bc59e342675a936849b).

The only method called on a cursor in the REST bits is `.toArray()`, I can't really imagine what the issue would be there. The only other code that uses Rethink is in that (somewhat messy) `watch` function.

Now that I'm glancing at it, it kind of looks like I might be closing the changefeed twice? I wonder if that's related.

**Comment by danielmewes** [comment]
I don't think closing the cursor twice would cause an error with the `Feed._next` method in the backtrace. My best guess is still that the cursor or connection is closed somewhere while it's still in use.

If that doesn't turn out to be the case, we'll need to investigate this further on the driver side.

**Comment by iameli** [comment]
All right. I won't have a chance to investigate too much further in the
immediate future -- will check back in here if I diagnose further. Y'all
can feel free to close this ticket if you like.
