### ISSUE TITLE
http connection test fails due to different compression header

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5928]
```
>>> Failed connections/r_http.js0.10 with exit code 1 after 0.4 sec + 0.4 sec setup (T+ 33.7 sec)

Using RethinkDB client from: /home/ssd3/daniel/rethinkdb-enterprise/build/packages/js


  Javascript HTTP test -
    GET
AssertionError: Actual result not equal to expected result:
  ACTUAL: "deflate, gzip"
  EXPECTED: "deflate;q=1, gzip;q=0.5"AssertionError: Actual result not equal to expected result:
  ACTUAL: "deflate, gzip"
  EXPECTED: "deflate;q=1, gzip;q=0.5"
    at expect_eq (/home/ssd3/daniel/rethinkdb-enterprise/test/rql_test/connections/r_http.js.httpbin:91:5)
    at /home/ssd3/daniel/rethinkdb-enterprise/test/rql_test/connections/r_http.js.httpbin:108:17
    at tryCatcher (/home/ssd3/daniel/rethinkdb-enterprise/build/packages/js/node_modules/bluebird/js/main/util.js:24:31)
    at Promise.successAdapter (/home/ssd3/daniel/rethinkdb-enterprise/build/packages/js/node_modules/bluebird/js/main/nodeify.js:22:30)
    at Promise._settlePromiseAt (/home/ssd3/daniel/rethinkdb-enterprise/build/packages/js/node_modules/bluebird/js/main/promise.js:563:21)
    at Promise._settlePromises (/home/ssd3/daniel/rethinkdb-enterprise/build/packages/js/node_modules/bluebird/js/main/promise.js:681:14)
    at Async._drainQueue (/home/ssd3/daniel/rethinkdb-enterprise/build/packages/js/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/ssd3/daniel/rethinkdb-enterprise/build/packages/js/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/ssd3/daniel/rethinkdb-enterprise/build/packages/js/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
<<< end Failed: connections/r_http.js0.10
```

I broke this with https://github.com/rethinkdb/rethinkdb/issues/5924 . Will need to update the test.

**Comment by larkost** [comment]
This was fixed in `next` with b08143cc, and `v2.3.x` in 1ec2d3ef.
