### ISSUE TITLE
App crashes when disconnected from internet.

### ISSUE THREAD

**Issue by modirajdeep** [rethinkdb/rethinkdb#6082]
I'm on rethinkdb 2.3.3 on windows. When my laptop disconnects from the internet, my node.js app crashes with this error -
 
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOENT localhost:80
    at Object.exports._errnoException (util.js:1012:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
```
When I try restarting the app I get this error -4

```
{ ReqlDriverError: Could not connect to localhost:28015.
getaddrinfo ENOENT localhost:28015
    at ReqlDriverError.ReqlError [as constructor] (D:\Axelta IOT\test\node_modules\rethinkdb\errors.js:23:13)
    at new ReqlDriverError (D:\Axelta IOT\test\node_modules\rethinkdb\errors.js:68:50)
    at TcpConnection.<anonymous> (D:\Axelta IOT\test\node_modules\rethinkdb\net.js:94:27)
    at TcpConnection.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at TcpConnection.emit (events.js:188:7)
    at Socket.<anonymous> (D:\Axelta IOT\test\node_modules\rethinkdb\net.js:699:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1015:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'ReqlDriverError',
  msg: 'Could not connect to localhost:28015.\ngetaddrinfo ENOENT localhost:28015',
  frames: undefined,
  message: 'Could not connect to localhost:28015.\ngetaddrinfo ENOENT localhost:28015' }
```

However everything works fine when the internet is back. Please help.

**Comment by danielmewes** [comment]
@modirajdeep This looks like a problem with name resolution, and is probably unrelated to RethinkDB.

Can you try hard-coding the address `127.0.0.1` as the host in your node code when calling `r.connect`, instead of using the `localhost` default?

**Comment by modirajdeep** [comment]
@danielmewes Yes it works now. That was the solution. Thank you.
