### ISSUE TITLE
BigchainDB wont start - ReqlNonExistenceError

### ISSUE THREAD

**Issue by jln1989** [rethinkdb/rethinkdb#6187]
I have installed rethinkDB and its running fine without issues. I have started to install bigchainDB by follwing the below link and stuck at step F - **_bigchainDB start_**.

[(https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html)](url)

I have also tried the below command and it says the components are up-to date 
`pip install --upgrade bigchaindb bigchaindb_driver`

**Error information:** 
```
INFO:bigchaindb.processes:Initializing BigchainDB...
INFO:bigchaindb.processes:Starting block
INFO:bigchaindb.processes:Starting voter
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/db/backends/rethinkdb.py", line 373, in get_last_voted_block
    .max(r.row['vote']['timestamp']))['vote']['timestamp']
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/db/utils.py", line 51, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.5/dist-packages/rethinkdb/ast.py", line 123, in run
    return c._start(self, **global_optargs)
  File "/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py", line 625, in _start
    return self._instance.run_query(q, global_optargs.get('noreply', False))
  File "/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py", line 471, in run_query
    raise res.make_error(query)
rethinkdb.errors.ReqlNonExistenceError: Cannot take the max of an empty stream.  (If you passed `max` a field name, it may be that no elements of the stream had that field.) in:
r.table('votes', read_mode='majority').filter(lambda var_1: (r.row['node_pubkey'] == r.expr('545LXU4hufWiEgGM5DxTw2edosmSQsbhrKWz8d96v9jA'))).max(lambda var_2: r.row['vote']['timestamp'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB==0.8.0', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchain.py", line 329, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 95, in start
    return func(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchain.py", line 188, in run_start
    processes.start()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/processes.py", line 33, in start
    vote.start()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/pipelines/vote.py", line 171, in start
    pipeline = create_pipeline()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/pipelines/vote.py", line 155, in create_pipeline
    voter = Vote()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/pipelines/vote.py", line 37, in __init__
    self.last_voted_id = Bigchain().get_last_voted_block().id
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/core.py", line 643, in get_last_voted_block
    return Block.from_dict(self.backend.get_last_voted_block(self.me))
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/db/backends/rethinkdb.py", line 382, in get_last_voted_block
    return self.get_genesis_block()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/db/backends/rethinkdb.py", line 356, in get_genesis_block
    .nth(0))
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/db/utils.py", line 51, in run
    return query.run(self.conn)
  File "/usr/local/lib/python3.5/dist-packages/rethinkdb/ast.py", line 123, in run
    return c._start(self, **global_optargs)
  File "/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py", line 625, in _start
    return self._instance.run_query(q, global_optargs.get('noreply', False))
  File "/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py", line 471, in run_query
    raise res.make_error(query)
rethinkdb.errors.ReqlNonExistenceError: Index out of bounds: 0 in:
r.table('bigchain', read_mode='majority').filter(lambda var_3: (var_3['block']['transactions'][0]['transaction']['operation'] == r.expr('GENESIS'))).nth(0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Anyone else facing the same issue?

Note: Am running this on ubuntu 16.04 LTS and has 16 GB RAM. Both bigchainDB and rethinkDB are latest.

**Comment by jln1989** [comment]
Closing this issue as its related to non availability of genesis block. Thanks to @rhsimplex from gitter for the solution.
