### ISSUE TITLE
Using `branch(null, query)` within `forEach`?

### ISSUE THREAD

**Issue by aleclarson** [rethinkdb/rethinkdb#6252]
```coffee
r.tableList()
.do (existing) ->
  r.expr tables
  .forEach (table) ->
    existing
    .contains table
    .branch null, r.tableCreate table
```

The above code returns this error:
```
ReqlRuntimeError: FOR_EACH expects one or more basic write queries.  Expected type ARRAY but found NULL in:
r.tableList().do(function(var_1) {
    return r.expr([...])
        .forEach(function(var_2) {
            return r.branch(var_1.contains(var_2), null, r.tableCreate(var_2))
                                                   ^^^^                       
        })
})

    at Connection._processResponse (/rethinkdb/lib/connection.js:389:15)
    at Socket.<anonymous> (/rethinkdb/lib/connection.js:208:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

Am I forced to use `Promise.all(tables.map(...))`?

**Comment by AtnNn** [comment]
The error says "FOR_EACH expects one or more basic write queries [...] but found NULL"

`forEach` should happily accept `{}` instead of `null`. I don't know if this is documented anywhere.

**Comment by marshall007** [comment]
Alternatively, you could `.filter` the list of tables before calling `.forEach`.

**Comment by gabor-boros** [comment]
Closing as it was already answered and the docs clearly state that `.forEach` should receive a write function.
