### ISSUE TITLE
Uncatchable ReqlTimeoutError on incorrect database password

### ISSUE THREAD

**Issue by nxtpool** [rethinkdb/rethinkdb#6290]
`
var r = require('rethinkdb');

var connection;

r.connect({
    "host": "localhost",
    "port": 28015,
    "authKey": "",
    "db": "projection"
}, function (err, conn) {
        setTimeout(function(){}, 999999);
});
`
This code throw error
`
{ ReqlAuthError: Wrong password
    at ReqlAuthError.ReqlError [as constructor] (/home/andrey/IdeaProjects/noderethink/node_modules/rethinkdb/errors.js:23:13)
    at ReqlAuthError.ReqlDriverError [as constructor] (/home/andrey/IdeaProjects/noderethink/node_modules/rethinkdb/errors.js:68:50)
    at new ReqlAuthError (/home/andrey/IdeaProjects/noderethink/node_modules/rethinkdb/errors.js:79:48)
    at handshake_error (/home/andrey/IdeaProjects/noderethink/node_modules/rethinkdb/net.js:609:40)
    at Socket.handshake_callback (/home/andrey/IdeaProjects/noderethink/node_modules/rethinkdb/net.js:678:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'ReqlAuthError',
  msg: 'Wrong password',
  frames: undefined,
  message: 'Wrong password' }
`
And I can catch it but then fall with 

`
/usr/bin/node /home/andrey/IdeaProjects/noderethink/app.js

events.js:160
      throw er; // Unhandled 'error' event
      ^
ReqlTimeoutError: Could not connect to localhost:28015, operation timed out.
    at ReqlTimeoutError.ReqlError [as constructor] (/home/andrey/IdeaProjects/noderethink/node_modules/rethinkdb/errors.js:23:13)
    at new ReqlTimeoutError (/home/andrey/IdeaProjects/noderethink/node_modules/rethinkdb/errors.js:156:51)
    at Timeout._onTimeout (/home/andrey/IdeaProjects/noderethink/node_modules/rethinkdb/net.js:519:36)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

Process finished with exit code 1
`

How can I catch it?

**Comment by AtnNn** [comment]
I was able to reproduce that behaviour, it looks like a bug to me.

As a work-around, you can catch error by constructing the connection directly, and adding an event handler. For example:

```
var r = require('rethinkdb');
var connection =  r.net.TcpConnection({
    "authKey": "",
}, function (err, conn) {
        setTimeout(function(){}, 999999);
});

connection.on('error', function(err){ ... });
```

**Comment by risharde** [comment]
Will this one be properly fixed? I experienced this today and thankfully I found this thread.
