### ISSUE TITLE
"lost contact with primary replica" when running from localhost - no errors in console.

### ISSUE THREAD

**Issue by mikemaccana** [rethinkdb/rethinkdb#6429]
**I have recently transitioned DB code from RethinkDB's callbacks to it's Promise based mode**. Since doing this the following error keeps occurring. 

**The error is occurring on localhost with almost no load, during integration testing**.

    Promise {
      <rejected> { ReqlOpIndeterminateError: Cannot perform write: lost contact with primary replica in:
    r.db("appTest").table("people").get("name+unittesting@app.com").delete()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        at ReqlOpIndeterminateError.ReqlError [as constructor] (C:\Users\name\Documents\app\node_modules\rethinkdb\errors.js:23:13)
        at ReqlOpIndeterminateError.ReqlRuntimeError [as constructor] (C:\Users\name\Documents\app\node_modules\rethinkdb\errors.js:90:51)
        at ReqlOpIndeterminateError.ReqlAvailabilityError [as constructor] (C:\Users\name\Documents\app\node_modules\rethinkdb\errors.js:167:56)
        at new ReqlOpIndeterminateError (C:\Users\name\Documents\app\node_modules\rethinkdb\errors.js:189:59)
        at mkErr (C:\Users\name\Documents\app\node_modules\rethinkdb\util.js:177:10)
        at TcpConnection.Connection._processResponse (C:\Users\name\Documents\app\node_modules\rethinkdb\net.js:152:16)
        at TcpConnection.Connection._data (C:\Users\name\Documents\app\node_modules\rethinkdb\net.js:122:12)
        at Socket.<anonymous> (C:\Users\name\Documents\app\node_modules\rethinkdb\net.js:689:32)
        at emitOne (events.js:115:13)
        at Socket.emit (events.js:210:7)
        at addChunk (_stream_readable.js:250:12)
        at readableAddChunk (_stream_readable.js:237:11)
        at Socket.Readable.push (_stream_readable.js:195:10)
        at TCP.onread (net.js:586:20)
      name: 'ReqlOpIndeterminateError',
      msg: 'Cannot perform write: lost contact with primary replica',
      frames: [],
      message: 'Cannot perform write: lost contact with primary replica in:\nr.db("appTest").table("people").get("name+unittesting@app.com").delete()\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' } }

There are no errors in the RethinkDB console.

    ~ $ rethinkdb
    Running rethinkdb 2.3.5-windows (MSC 190023506)...
    Running on 6.2.9200 (Windows 8, Server 2012)
    Loading data from directory C:\Users\name\rethinkdb_data
    Listening for intracluster connections on port 29015
    Listening for client driver connections on port 28015
    Listening for administrative HTTP connections on port 8080
    Listening on cluster address: 127.0.0.1
    Listening on driver address: 127.0.0.1
    Listening on http address: 127.0.0.1
    To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
    Server ready, "DESKTOP_JL59SC6_crm" d6cce03a-3c31-41f0-9f28-759b0bc3c37c
    Removing file C:\Users\name\rethinkdb_data\59743818-2b00-400f-a451-24dc191084d0
    Removing file C:\Users\name\rethinkdb_data\19d7dbf2-7748-4c34-b47a-c7cba52fc68a
    Removing file C:\Users\name\rethinkdb_data\7efdbf92-ab10-4f62-a132-edbdcfd96872
    Removing file C:\Users\name\rethinkdb_data\a114e9b3-6a45-4d09-a18d-dfe39527aa21

The error is in RethinkDB `2.3.5` on Windows 10.

**Comment by AtnNn** [comment]
@mikemaccana Is your RethinkDB instance connected to any others?

**Comment by mikemaccana** [comment]
Nope just a standalone instance running with default config.

**Comment by AtnNn** [comment]
I don't think RethinkDB should report that kind of error if it wasn't in a cluster.

What else is going on on the database when the error occurs? How often do you get that error?

Could you try using the new release candidate to see if it fixes the issue? It is available here https://thanos.atnnn.com/downloads/rc/2.3.6/2/rethinkdb-v2.3.6-0RC2-windows.zip

**Comment by srh** [comment]
Closing as old.  If you're still seeing this and it's possible to get information that would help figure out what's happening, feel free to reopen.
