### ISSUE TITLE
can't build on alpine on s390x

### ISSUE THREAD

**Issue by vikstrous** [rethinkdb/rethinkdb#6441]
It looks like npm is not able to install any packages but we need to install coffee and browserfy to build rethinkdb. It fails with the following error:

```
Error: could not get uid/gid
[ 'nobody', 0 ]

    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:211:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

```

To repro you can use the following PR https://github.com/jlhawn/rethinkdb-docker/pull/3 and replace `alpine:3.4` with `s390x/alpine:3.4` in both dockerfiles and then run `make`.

We might be able to hack around this by building the javascript part separately not on s390x and then combining the results, but I would rather have everything built in a simple dockerfile without having the hack the build system.

Worst case scenario: is there a way to disable the admin ui while building?

**Comment by AtnNn** [comment]
If you `make dist` in an environment that can build the web ui, it will build a source tarball that contains the precompiled web ui and that does not require npm to build.

**Comment by vikstrous** [comment]
I got a little farther with `./configure --allow-fetch`

```
./scripts/gen-version.sh: Warning: could not determine the version, using the default version '2.3.2-fallback'
./scripts/gen-version.sh: Warning: could not determine the version, using the default version '0.0-internal-unknown-fallback-fallback'
    [1/455] FETCH coffee-script_1.10.0
    [2/455] BUILD bluebird_2.9.32
    [3/455] FETCH browserify_13.1.0
    [4/455] FETCH admin-deps_2.0.4
    [5/455] INSTALL-INCLUDE gtest_1.7.0
    [6/455] FETCH re2_2015-11-01
    [7/455] FETCH v8_3.28-s390
    [8/455] CONVERT_PROTOFILE build/drivers/ruby/lib/ql2.pb.rb
    [9/455] CONVERT_PROTOFILE drivers/ruby/lib/ql2.pb.rb
    [10/455] CP ./build/drivers/python/rethinkdb/
    [11/455] CONVERT_PROTOFILE build/drivers/python/rethinkdb/ql2_pb2.py
    [12/455] CONVERT_PROTOFILE drivers/python/rethinkdb/ql2_pb2.py
    [13/455] BUILD coffee-script_1.10.0
    [14/455] CONVERT_PROTOFILE build/drivers/javascript/proto-def.js
    [15/455] BUILD browserify_13.1.0
    [16/455] BUILD admin-deps_2.0.4
    [17/455] PROTOC build/proto/rdb_protocol/ql2.pb.cc
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: rdb_protocol/ql2.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
    [18/455] INSTALL-INCLUDE re2_2015-11-01
    [19/455] CP build/release_system/rethinkdb-gdb.py
    [20/455] CP ./build/drivers/ruby/lib
    [21/455] COFFEE build/drivers/javascript/coffee/util.js
    [22/455] COFFEE build/drivers/javascript/coffee/net.js
    [23/455] COFFEE build/drivers/javascript/coffee/errors.js
    [24/455] COFFEE build/drivers/javascript/coffee/ast.js
    [25/455] COFFEE build/drivers/javascript/coffee/rethinkdb.js
    [26/455] COFFEE build/drivers/javascript/coffee/cursor.js
    [27/455] CC build/release_system/obj/rdb_protocol/ql2.pb.o
    [28/455] BUILD re2_2015-11-01
^[[D    [29/455] CP ./build/packages/js
    [30/455] INSTALL-INCLUDE v8_3.28-s390
+ pkg_copy_src_to_build
+ mkdir -p /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390/build
+ cp -af /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/external/v8_3.28-s390/. /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390/build
+ rm -rf /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390/include
+ mkdir -p /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390/include
++ /usr/bin/c++ -dumpmachine
+ [[ s390x-alpine-linux-musl = \s\3\9\0\x\-\l\i\n\u\x\-\g\n\u ]]
+ cp -RL /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/external/v8_3.28-s390/include/. /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390/include
+ sed -i.bak 's/include\///' /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390/include/libplatform/libplatform.h
+ [[ 0 = 1 ]]
++ niceabspath /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390
++ [[ -d /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390 ]]
++ cd /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390
++ pwd
++ return
+ in_dir /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390/build/third_party/icu/source ./configure --prefix=/rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390 --enable-static --disable-layout
+ local dir=/rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390/build/third_party/icu/source
+ shift
+ cd /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390/build/third_party/icu/source
mk/support/pkg/pkg.sh: line 320: cd: /rethinkdb-cfee565ebb0a1db07619c9008a9b8b37e21be166/build/external/v8_3.28-s390/build/third_party/icu/source: No such file or directory

Full error log: ./build/external/v8_3.28-s390_install-include.log
make[1]: *** [mk/support/build.mk:175: build/external/v8_3.28-s390/include] Error 1
make[1]: *** Waiting for unfinished jobs....

```
Can anyone help me understand this error?

**Comment by john-yan** [comment]
Hello @vikstrous , is the v8_3.28-s390 repository from https://github.com/ibmruntimes/v8?

Before you can build v8 3.28, you need to do "make dependencies" to download denpendencies like icu.

On v8 3.28, we didn't have icu support because icu only works on little-endian at that point.

**Comment by gabor-boros** [comment]
@srh fyi, I'm closing this as https://github.com/rethinkdb/rethinkdb/issues/7071 is already closed and we were able to build for s390x
