### ISSUE TITLE
Web interface sill blank.

### ISSUE THREAD

**Issue by nathan130200** [rethinkdb/rethinkdb#6476]
```log
Running rethinkdb 2.3.6-windows (MSC 190024215)...
Running on 6.1.7600 (Windows 7, Server 2008 R2)
Loading data from directory E:\RethinkDb\rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on cluster addresses: 127.0.0.1, 192.168.56.1, 192.168.1.2, 25.91.132.241, 2620:9b::195b:84f1, fe80::350d:d40:b577:7498%44, fe80::7596:6a4d:16e0:4ef%3, fe80::b026:ec0c:2df:8ef2%4
Listening on driver addresses: 127.0.0.1, 192.168.56.1, 192.168.1.2, 25.91.132.241, 2620:9b::195b:84f1, fe80::350d:d40:b577:7498%44, fe80::7596:6a4d:16e0:4ef%3, fe80::b026:ec0c:2df:8ef2%4
Listening on http addresses: 127.0.0.1, 192.168.56.1, 192.168.1.2, 25.91.132.241, 2620:9b::195b:84f1, fe80::350d:d40:b577:7498%44, fe80::7596:6a4d:16e0:4ef%3, fe80::b026:ec0c:2df:8ef2%4
Server ready, "DESKTOP_B9F5EHE_k46" c124cd8c-84f4-4f46-ab5f-6aa1d46179d2
```

I'm using Windows 10 (64Bits)

![screenshot_47](https://user-images.githubusercontent.com/14365254/29745237-d9ac6042-8a8b-11e7-8719-49842dca9333.png)

**Comment by robertjpayne** [comment]
Can you check the web console for any potential JS/web rendering errors?

**Comment by nathan130200** [comment]
Yes, don't have any erros

**Comment by nathan130200** [comment]
Requests aren't finishing

![image](https://user-images.githubusercontent.com/14365254/30081439-976a0c6e-925d-11e7-9729-0789b5b17c8a.png)

**Comment by nathan130200** [comment]
@robertjpayne Don't working for all browsers that i have on machine:
![image](https://user-images.githubusercontent.com/14365254/30082108-01431c8c-9260-11e7-9963-cd7e88763488.png)

Updated Config:
```config
bind=127.0.0.1
http-port=7070
cores=2
io-threads=64
server-name=Gaming
```

Updated Log:
```txt
WARNING: ignoring --server-name because this server already has a name.
Running rethinkdb 2.3.6-windows (MSC 190024215)...
Running on 6.1.7600 (Windows 7, Server 2008 R2)
Loading data from directory E:\RethinkDb\rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 7070
Listening on cluster addresses: 127.0.0.1, 25.91.132.241
Listening on driver addresses: 127.0.0.1, 25.91.132.241
Listening on http addresses: 127.0.0.1, 25.91.132.241
To fully expose RethinkDB on the network, bind to all addresses by adding `bind=all' to the config file (config.dat).
Server ready, "DESKTOP_B9F5EHE_gpu" 7788b637-81a8-4df3-9645-53f21c839be4
```

**Comment by marshall007** [comment]
@nathan130200 are you running RethinkDB on the same machine you're attempting to connect from? Are you able to connect and execute queries using a client driver?

**Comment by nathan130200** [comment]
Yes! Same machine. I don't tried to execute queries, i now try this.

**Comment by nathan130200** [comment]
Wait. Using NodeJS Example works fine (https://www.rethinkdb.com/docs/install-drivers/javascript/):

```info
$ node index.js

E:\RethinkDb\test\node_modules\bluebird\js\main\async.js:43
        fn = function () { throw arg; };
                           ^
ReqlOpFailedError: Table `test.tv_shows` already exists in:
r.db("test").tableCreate("tv_shows")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    at ReqlOpFailedError.ReqlError [as constructor] (E:\RethinkDb\test\node_modules\rethinkdb\errors.js:23:13)
    at ReqlOpFailedError.ReqlRuntimeError [as constructor] (E:\RethinkDb\test\node_modules\rethinkdb\errors.js:90:51)
    at ReqlOpFailedError.ReqlAvailabilityError [as constructor] (E:\RethinkDb\test\node_modules\rethinkdb\errors.js:167:56)
    at new ReqlOpFailedError (E:\RethinkDb\test\node_modules\rethinkdb\errors.js:178:52)
    at mkErr (E:\RethinkDb\test\node_modules\rethinkdb\util.js:177:10)
    at TcpConnection.Connection._processResponse (E:\RethinkDb\test\node_modules\rethinkdb\net.js:152:16)
    at TcpConnection.Connection._data (E:\RethinkDb\test\node_modules\rethinkdb\net.js:122:12)
    at Socket.<anonymous> (E:\RethinkDb\test\node_modules\rethinkdb\net.js:689:32)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)
```

**Comment by nathan130200** [comment]
But webadmin still don't working

**Comment by chrisvariety** [comment]
Seems like probably an IE issue. Can you try Chrome?

**Comment by nathan130200** [comment]
I Tried in Chrome, Opera, IE and Microsoft Edge same problem (infinite load)

**Comment by marshall007** [comment]
@nathan130200 perhaps it's a firewall? Can you try looking at/tweaking the Windows Firewall rules (or just temporarily disable it entirely)?

**Comment by nathan130200** [comment]
@marshall007 firewall already disabled.

**Comment by sagivf** [comment]
I've seen this before. Currently i'm having the same issues using [nanobox](https://guides.nanobox.io/rethinkdb/production/).
Trying to connect via a tunnel - https://github.com/nanobox-io/nanobox/issues/496#issuecomment-329993488

**Comment by rad1k4l** [comment]
I have same issue
