### ISSUE TITLE
rethinkdb 2.3.6 tests fails on Alpine Linux (x86_64): FAIL interface.artificial_table

### ISSUE THREAD

**Issue by ncopa** [rethinkdb/rethinkdb#6488]
The test interface.artificial_table fails with rethinkdb 2.3.6 on Alpine Linux (x86_64):
````
FAIL interface.artificial_table                                                                                         
Failed 2 tests, passed 1                                                                              
<<< end Failed: polyglot/regression/545.py2.7                                                                                               
Traceback (most recent call last):                                                                                     
  File "/home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/test/interface/artificial_table.py", line 45, in <module>
    subprocess.check_call(command_line)                                                                                                 
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call                                                      
    raise CalledProcessError(retcode, cmd)                                      
subprocess.CalledProcessError: Command '['/home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/test/interface/../rql_test/test-runner', '--driver-port', 'localhost:41941', '--table', 'rethinkdb._debug_scratch', 'polyglot/control', 'polyglot/joins', 'polyglot/match', 'polyglot/mutation/atomic_get_set', 'polyglot/mutation/delete', 'polyglot/mutation/insert', 'polyglot/mutation/replace', 'polyglot/mutation/update', 'polyglot/polymorphi
sm', 'polyglot/regression/309', 'polyglot/regression/453', 'polyglot/regression/522.py', 'polyglot/regression/545', 'polyglot/regression/568', 'polyglot/regression/678', 'polyglot/regression/1155', 'polyglot/regression/11
79', 'polyglot/regression/1468', 'polyglot/regression/2399', 'polyglot/regression/2697', 'polyglot/regression/2709', 'polyglot/regression/2838', 'polyglot/regression/2930']' returned non-zero exit status 1
Command '$RETHINKDB/test/interface/artificial_table.py' returned non-zero exit status 1

````
output of `results/2017-09-06T20:40:31.ogemgJ/interface.artificial_table/stderr`:
````
/home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/test/common/utils.py:62: UserWarning: Supplied JavaScript driver path (JAVASCRIPT_DRIVER) was not valid: /home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/build/packages/js
  warnings.warn('Supplied %s driver path (%s) was not valid: %s' % (name, info['envName'], os.environ[info['envName']]))
/home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/test/rql_test/../common/utils.py:62: UserWarning: Supplied JavaScript driver path (JAVASCRIPT_DRIVER) was not valid: /home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/build/packages/js
  warnings.warn('Supplied %s driver path (%s) was not valid: %s' % (name, info['envName'], os.environ[info['envName']]))
>>> Failed polyglot/control.py2.7 with exit code 1 after 4.4 sec + 0.0 sec setup (T+ 4.6 sec)

/home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/test/common/utils.py:62: UserWarning: Supplied JavaScript driver path (JAVASCRIPT_DRIVER) was not valid: /home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/build/packages/js
  warnings.warn('Supplied %s driver path (%s) was not valid: %s' % (name, info['envName'], os.environ[info['envName']]))
Using RethinkDB client from: /home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/build/drivers/python/rethinkdb/__init__.pyc
Using existing table: rethinkdb._debug_scratch, will be tbl

TEST FAILURE: line 140
    FAILURE:  expected number 2 but got Javascript query `1 + 1` caused a crash in a worker process in:
r.js('1 + 1')
^^^^^^^^^^^^^ (ReqlInternalError)
    SOURCE:   "r.js('1 + 1')"
    EXPECTED: 2
    RESULT:   <ReqlInternalError instance: Javascript query `1 + 1` caused a crash in a worker process in:
              r.js('1 + 1')
              ^^^^^^^^^^^^^ >

TEST FAILURE: line 143
    FAILURE:  expected number 4 but got Javascript query `1 + 1; 2 + 2` caused a crash in a worker process in:
r.js('1 + 1; 2 + 2')
^^^^^^^^^^^^^^^^^^^^ (ReqlInternalError)
    SOURCE:   "r.js('1 + 1; 2 + 2')"
    EXPECTED: 4
    RESULT:   <ReqlInternalError instance: Javascript query `1 + 1; 2 + 2` caused a crash in a worker process in:
              r.js('1 + 1; 2 + 2')
              ^^^^^^^^^^^^^^^^^^^^ >

TEST FAILURE: line 146
    FAILURE:  expected number 3 but got Javascript query `(function(a, b) { return a + b; })` caused a crash in a worker process in:
r.do(1, 2, r.js('(function(a, b) { return a + b; })'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  (ReqlInternalError)
    SOURCE:   "r.do(1, 2, r.js('(function(a, b) { return a + b; })'))"
    EXPECTED: 3
    RESULT:   <ReqlInternalError instance: Javascript query `(function(a, b) { return a + b; })` caused a crash in a worker process in:
              r.do(1, 2, r.js('(function(a, b) { return a + b; })'))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  >

TEST FAILURE: line 149
    FAILURE:  expected number 2 but got Javascript query `(function(x) { return x + 1; })` caused a crash in a worker process in:
r.expr(1).do(r.js('(function(x) { return x + 1; })'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  (ReqlInternalError)
    SOURCE:   "r.expr(1).do(r.js('(function(x) { return x + 1; })'))"
    EXPECTED: 2
    RESULT:   <ReqlInternalError instance: Javascript query `(function(x) { return x + 1; })` caused a crash in a worker process in:
              r.expr(1).do(r.js('(function(x) { return x + 1; })'))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  >

TEST FAILURE: line 152
    FAILURE:  value << <ReqlInternalError instance: Javascript query `(function(x) { return x + "bar"; })` caused a crash in a worker process in:
r.expr('foo').do(r.js('(function(x) { return x + "bar"; })'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  > >> was not the expected: foobar
    SOURCE:   'r.expr(\'foo\').do(r.js(\'(function(x) { return x + "bar"; })\'))'
    EXPECTED: 'foobar'
    RESULT:   <ReqlInternalError instance: Javascript query `(function(x) { return x + "bar"; })` caused a crash in a worker process in:
              r.expr('foo').do(r.js('(function(x) { return x + "bar"; })'))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  >

TEST FAILURE: line 157
    FAILURE:  expected number 3 but got Javascript query `1 + 2` caused a crash in a worker process in:
r.js('1 + 2', timeout=1.2)
^^^^^^^^^^^^^^^^^^^^^^^^^^ (ReqlInternalError)
    SOURCE:   "r.js('1 + 2', timeout=1.2)"
    EXPECTED: 3
    RESULT:   <ReqlInternalError instance: Javascript query `1 + 2` caused a crash in a worker process in:
              r.js('1 + 2', timeout=1.2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^ >

TEST FAILURE: line 161
    FAILURE:  expected error type <class 'rethinkdb.errors.ReqlQueryLogicError'>, got <ReqlInternalError instance: Javascript query `(function() { return 1; })` caused a crash in a worker process in:
r.js('(function() { return 1; })')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ > (ReqlInternalError)
    SOURCE:   "r.js('(function() { return 1; })')"
    EXPECTED: ReqlQueryLogicError(Query result must be of type DATUM, GROUPED_DATA, or STREAM (got FUNCTION).)
    RESULT:   <ReqlInternalError instance: Javascript query `(function() { return 1; })` caused a crash in a worker process in:
              r.js('(function() { return 1; })')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ >

TEST FAILURE: line 164
    FAILURE:  expected error type <class 'rethinkdb.errors.ReqlQueryLogicError'>, got <ReqlInternalError instance: Javascript query `function() { return 1; }` caused a crash in a worker process in:
r.js('function() { return 1; }')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ > (ReqlInternalError)
    SOURCE:   "r.js('function() { return 1; }')"
    EXPECTED: ReqlQueryLogicError(SyntaxError: Unexpected token ()
    RESULT:   <ReqlInternalError instance: Javascript query `function() { return 1; }` caused a crash in a worker process in:
              r.js('function() { return 1; }')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ >

TEST FAILURE: line 168
    FAILURE:  expected number 1 but got Javascript query `(function(a) { return a; })` caused a crash in a worker process in:
r.do(1, 2, r.js('(function(a) { return a; })'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  (ReqlInternalError)
    SOURCE:   "r.do(1, 2, r.js('(function(a) { return a; })'))"
    EXPECTED: 1
    RESULT:   <ReqlInternalError instance: Javascript query `(function(a) { return a; })` caused a crash in a worker process in:
              r.do(1, 2, r.js('(function(a) { return a; })'))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  >

TEST FAILURE: line 171
    FAILURE:  expected number 1 but got Javascript query `(function(a, b, c) { return a; })` caused a crash in a worker process in:
r.do(1, 2, r.js('(function(a, b, c) { return a; })'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  (ReqlInternalError)
    SOURCE:   "r.do(1, 2, r.js('(function(a, b, c) { return a; })'))"
    EXPECTED: 1
    RESULT:   <ReqlInternalError instance: Javascript query `(function(a, b, c) { return a; })` caused a crash in a worker process in:
              r.do(1, 2, r.js('(function(a, b, c) { return a; })'))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  >

TEST FAILURE: line 174
    FAILURE:  expected error type <class 'rethinkdb.errors.ReqlQueryLogicError'>, got <ReqlInternalError instance: Javascript query `(function(a, b, c) { return c; })` caused a crash in a worker process in:
r.do(1, 2, r.js('(function(a, b, c) { return c; })'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  > (ReqlInternalError)
    SOURCE:   "r.do(1, 2, r.js('(function(a, b, c) { return c; })'))"
    EXPECTED: ReqlQueryLogicError(Cannot convert javascript `undefined` to ql::datum_t.)
    RESULT:   <ReqlInternalError instance: Javascript query `(function(a, b, c) { return c; })` caused a crash in a worker process in:
              r.do(1, 2, r.js('(function(a, b, c) { return c; })'))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  >

TEST FAILURE: line 177
    FAILURE:  expected iterable, got Javascript query `(function(a) { return a >= 2; })` caused a crash in a worker process in:
r.expr([1, 2, 3]).filter(r.js('(function(a) { return a >= 2; })'))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  (ReqlInternalError)
    SOURCE:   "r.expr([1, 2, 3]).filter(r.js('(function(a) { return a >= 2; })'))"
    EXPECTED: [2, 3]
    RESULT:   <ReqlInternalError instance: Javascript query `(function(a) { return a >= 2; })` caused a crash in a worker process in:
              r.expr([1, 2, 3]).filter(r.js('(function(a) { return a >= 2; })'))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  >

TEST FAILURE: line 180
    FAILURE:  expected iterable, got Javascript query `(function(a) { return a + 1; })` caused a crash in a worker process in:
r.expr([1, 2, 3]).map(r.js('(function(a) { return a + 1; })'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  (ReqlInternalError)
    SOURCE:   "r.expr([1, 2, 3]).map(r.js('(function(a) { return a + 1; })'))"
    EXPECTED: [2, 3, 4]
    RESULT:   <ReqlInternalError instance: Javascript query `(function(a) { return a + 1; })` caused a crash in a worker process in:
              r.expr([1, 2, 3]).map(r.js('(function(a) { return a + 1; })'))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  >

TEST FAILURE: line 183
    FAILURE:  expected error type <class 'rethinkdb.errors.ReqlQueryLogicError'>, got <ReqlInternalError instance: Javascript query `1` caused a crash in a worker process in:
r.expr([1, 2, 3]).map(r.js('1'))
                      ^^^^^^^^^  > (ReqlInternalError)
    SOURCE:   "r.expr([1, 2, 3]).map(r.js('1'))"
    EXPECTED: ReqlQueryLogicError(Expected type FUNCTION but found DATUM:)
    RESULT:   <ReqlInternalError instance: Javascript query `1` caused a crash in a worker process in:
              r.expr([1, 2, 3]).map(r.js('1'))
                                    ^^^^^^^^^  >

TEST FAILURE: line 186
    FAILURE:  expected error type <class 'rethinkdb.errors.ReqlQueryLogicError'>, got <ReqlInternalError instance: Javascript query `(function(a) {})` caused a crash in a worker process in:
r.expr([1, 2, 3]).filter(r.js('(function(a) {})'))
                         ^^^^^^^^^^^^^^^^^^^^^^^^  > (ReqlInternalError)
    SOURCE:   "r.expr([1, 2, 3]).filter(r.js('(function(a) {})'))"
    EXPECTED: ReqlQueryLogicError(Cannot convert javascript `undefined` to ql::datum_t.)
    RESULT:   <ReqlInternalError instance: Javascript query `(function(a) {})` caused a crash in a worker process in:
              r.expr([1, 2, 3]).filter(r.js('(function(a) {})'))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^  >
Failed 15 tests, passed 62
<<< end Failed: polyglot/control.py2.7
>>> Failed polyglot/mutation/replace.py2.7 with exit code 1 after 11.9 sec + 0.0 sec setup (T+ 86.7 sec)

/home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/test/common/utils.py:62: UserWarning: Supplied JavaScript driver path (JAVASCRIPT_DRIVER) was not valid: /home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/build/packages/js
  warnings.warn('Supplied %s driver path (%s) was not valid: %s' % (name, info['envName'], os.environ[info['envName']]))
Using RethinkDB client from: /home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/build/drivers/python/rethinkdb/__init__.pyc
Using existing table: rethinkdb._debug_scratch, will be tbl

TEST FAILURE: line 83
    FAILURE:  unmatched keys from either side: set([u'first_error'])
    SOURCE:   "tbl.get(1).replace(r.row.merge({'c':r.js('5')}), non_atomic=True)"
    EXPECTED: {'deleted': 0.0, 'errors': 0.0, 'inserted': 0.0, 'replaced': 1, 'skipped': 0.0, 'unchanged': 0.0}
    RESULT:   {'deleted': 0,
               'errors': 1,
               'first_error': 'Javascript query `5` caused a crash in a worker process.',
               'inserted': 0,
               'replaced': 0,
               'skipped': 0,
               'unchanged': 0}
Failed 1 tests, passed 18
<<< end Failed: polyglot/mutation/replace.py2.7
>>> Failed polyglot/mutation/update.py2.7 with exit code 1 after 24.7 sec + 0.0 sec setup (T+ 111.7 sec)

/home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/test/common/utils.py:62: UserWarning: Supplied JavaScript driver path (JAVASCRIPT_DRIVER) was not valid: /home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/build/packages/js
  warnings.warn('Supplied %s driver path (%s) was not valid: %s' % (name, info['envName'], os.environ[info['envName']]))
Using RethinkDB client from: /home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/build/drivers/python/rethinkdb/__init__.pyc
Using existing table: rethinkdb._debug_scratch, will be tbl

TEST FAILURE: line 125
    FAILURE:  unmatched keys from either side: set([u'first_error'])
    SOURCE:   "tbl.get(1).update({'d':r.js('5')}, non_atomic=True)"
    EXPECTED: {'deleted': 0.0, 'errors': 0.0, 'inserted': 0.0, 'replaced': 1, 'skipped': 0.0, 'unchanged': 0.0}
    RESULT:   {'deleted': 0,
               'errors': 1,
               'first_error': 'Javascript query `5` caused a crash in a worker process.',
               'inserted': 0,
               'replaced': 0,
               'skipped': 0,
               'unchanged': 0}
Failed 1 tests, passed 32
<<< end Failed: polyglot/mutation/update.py2.7
>>> Failed polyglot/regression/545.py2.7 with exit code 1 after 0.5 sec + 0.0 sec setup (T+ 338.8 sec)

/home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/test/common/utils.py:62: UserWarning: Supplied JavaScript driver path (JAVASCRIPT_DRIVER) was not valid: /home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/build/packages/js
  warnings.warn('Supplied %s driver path (%s) was not valid: %s' % (name, info['envName'], os.environ[info['envName']]))
Using RethinkDB client from: /home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/build/drivers/python/rethinkdb/__init__.pyc
Using existing table: rethinkdb._debug_scratch, will be tbl

TEST FAILURE: line 8
    FAILURE:  expected number 1 but got Javascript query `(function(x,y){return 1;})` caused a crash in a worker process in:
r.db('rethinkdb').table('_debug_scratch').reduce(r.js('(function(x,y){return 1;})'))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  (ReqlInternalError)
    SOURCE:   'tbl.reduce(r.js("(function(x,y){return 1;})"))'
    EXPECTED: 1
    RESULT:   <ReqlInternalError instance: Javascript query `(function(x,y){return 1;})` caused a crash in a worker process in:
              r.db('rethinkdb').table('_debug_scratch').reduce(r.js('(function(x,y){return 1;})'))
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  >

TEST FAILURE: line 13
    FAILURE:  expected dict, got <ReqlInternalError instance: Javascript query `(function(x,y){return {id:x["id"] + y["id"]};})` caused a crash in a worker process in:
r.db('rethinkdb').table('_debug_scratch').reduce(r.js('(function(x,y){return {id:x["id"] + y["id"]};})'))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  > (ReqlInternalError)
    SOURCE:   'tbl.reduce(r.js("(function(x,y){return {id:x[\\"id\\"] + y[\\"id\\"]};})"))'
    EXPECTED: {'id': 3}
    RESULT:   <ReqlInternalError instance: Javascript query `(function(x,y){return {id:x["id"] + y["id"]};})` caused a crash in a worker process in:
              r.db('rethinkdb').table('_debug_scratch').reduce(r.js('(function(x,y){return {id:x["id"] + y["id"]};})'))
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  >
Failed 2 tests, passed 1
<<< end Failed: polyglot/regression/545.py2.7
Traceback (most recent call last):
  File "/home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/test/interface/artificial_table.py", line 45, in <module>
    subprocess.check_call(command_line)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ncopa/aports/community/rethinkdb/src/rethinkdb-2.3.6/test/interface/../rql_test/test-runner', '--driver-port', 'localhost:41941', '--table', 'rethinkdb._debug_scratch', 'polyglot/control', 'polyglot/joins', 'polyglot/match', 'polyglot/mutation/atomic_get_set', 'polyglot/mutation/delete', 'polyglot/mutation/insert', 'polyglot/mutation/replace', 'polyglot/mutation/update', 'polyglot/polymorphism', 'polyglot/regression/309', 'polyglot/regression/453', 'polyglot/regression/522.py', 'polyglot/regression/545', 'polyglot/regression/568', 'polyglot/regression/678', 'polyglot/regression/1155', 'polyglot/regression/1179', 'polyglot/regression/1468', 'polyglot/regression/2399', 'polyglot/regression/2697', 'polyglot/regression/2709', 'polyglot/regression/2838', 'polyglot/regression/2930']' returned non-zero exit status 1
Command '$RETHINKDB/test/interface/artificial_table.py' returned non-zero exit status 1
````

**Comment by robertjpayne** [comment]
I think this is probably failing because of v8 on alpine linux. Can you try to run some node.js stuff in general?

Alpine isn't a supported platform but it would be nice to get it working there.
