### ISSUE TITLE
Request Update To Allow Builds With VS2017

### ISSUE THREAD

**Issue by kklouzal** [rethinkdb/rethinkdb#6531]
In reference to [this issue](https://github.com/rethinkdb/rethinkdb/issues/6529)
I am requesting the configure script be updated to allow building with VS2017 (the compiler I use)
The current ./configure script is unable to locate MSBUILD after properly setting the path (CMD can access MSBUILD and inside cgywin I can access MSBUILD but the configure script cannot)

The next step in troubleshooting the referenced issue is to compile myself from source and test as multiple windows users using the provided rethinkdb.zip have the same 'bad password' issue.

Thank you all for your time.

**Comment by srh** [comment]
Hey, I'll look into this.  Obviously this is a must-do issue.

**Comment by srh** [comment]
I'm currently working on this.  Here's what I've got for the configure line:

```
./configure \
  MSBUILD='/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/msbuild.exe' \
  VCVARSALL='/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build/vcvarsall.bat'
```

It seems to be getting over problems of being unable to access MSBUILD.  I don't know why that didn't work automatically.  Maybe it didn't before, when I got it working on VS 2015, and I can't remember.

The next problem I encountered was that it wanted a VC 2015 v140 toolset installed.  You can add that as a feature in the VS installer.

The next problem I'm encountering is that `with_vs_env`, a function in mk/support/pkg/pkg.sh, is running the command in C:/Users/sam/source, as made evident by manually running

```
env -u MAKE -u MAKEFLAGS cmd /c "C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\AUXILI~1\Build\VCVARS~1.BAT" "x64" "&&" "pwd"
```

So the current problem is that curl, or libcurl, won't build.

**Comment by srh** [comment]
That problem in `with_vs_env` was fixed by making the `cmd` call explicitly cd to the current working directory.

The next build failure is that gclient sync fails.

```
+ pkg_depends_env
++ pkg_depends
++ true
+ pkg_fetch
+ pkg_make_tmp_fetch_dir
++ mktemp -d /home/sam/rethinkdb/external/v8_4.7.80.23.fetch-XXXXXXXX
+ tmp_dir=/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX
+ git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git /home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools
Cloning into '/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools'...
+ PATH='/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools:/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files/CMake/bin:/cygdrive/c/Program Files/nodejs:/cygdrive/c/Users/sam/AppData/Local/Microsoft/WindowsApps:/cygdrive/c/Users/sam/AppData/Roaming/npm:/cygdrive/c/Python27'
+ in_dir /home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX gclient config --unmanaged https://chromium.googlesource.com/v8/v8.git
+ local dir=/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX
+ shift
+ cd /home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX
+ gclient config --unmanaged https://chromium.googlesource.com/v8/v8.git
Bootstrapping cipd client for windows-amd64 from https://chrome-infra-packages.appspot.com/client?platform=windows-amd64&version=git_revision:d2677a4477e59cb7de00f1fb8a00e96b1aaeb927...
+ in_dir /home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX git clone https://chromium.googlesource.com/v8/v8.git
+ local dir=/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX
+ shift
+ cd /home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX
+ git clone https://chromium.googlesource.com/v8/v8.git
Cloning into 'v8'...
++ in_dir /home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/v8 git rev-parse refs/tags/4.7.80.23
++ local dir=/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/v8
++ shift
++ cd /home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/v8
++ git rev-parse refs/tags/4.7.80.23
+ v8_commit=a10202d1aa3cbaa3b550401bebbe34119b2d20b2
+ in_dir /home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX gclient sync --revision v8@a10202d1aa3cbaa3b550401bebbe34119b2d20b2
+ local dir=/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX
+ shift
+ cd /home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX
+ gclient sync --revision v8@a10202d1aa3cbaa3b550401bebbe34119b2d20b2

v8/build/gyp (ERROR)
----------------------------------------
[0:00:10] Started.
[0:00:10] 

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/gyp.git /home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/v8/build/_gclient_gyp_H3HGtF' in '/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX'
[0:00:10] Cloning into '/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/v8/build/_gclient_gyp_H3HGtF'...
[0:00:11] Receiving objects:   0% (1/17992)   
[0:00:11] Receiving objects:  10% (1800/17992)   
[0:00:13] Receiving objects:  96% (17355/17992), 7.06 MiB | 3.48 MiB/s   
[0:00:13] remote: Total 17992 (delta 12669), reused 17992 (delta 12669)        
[0:00:13] Receiving objects: 100% (17992/17992), 7.06 MiB | 3.48 MiB/s   
[0:00:13] Resolving deltas:   0% (0/12669)   
[0:00:14] Resolving deltas:  10% (1284/12669)   
[0:00:15] Resolving deltas:  79% (10017/12669)   
[0:00:15] Resolving deltas: 100% (12669/12669)   
[0:00:19] Checked out 01528c7244837168a1c80f06ff60fa5a9793c824 to a detached HEAD. Before making any commits
in this repo, you should use 'git checkout <branch>' to switch to
an existing branch or use 'git checkout origin -b <branch>' to
create a new branch for your work.
[0:00:19]
----------------------------------------
Traceback (most recent call last):
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient.py", line 2681, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient.py", line 2667, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient.py", line 2422, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient.py", line 1499, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient_utils.py", line 1059, in run
    self.item.run(*self.args, **self.kwargs)
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient.py", line 902, in run
    self.ParseDepsFile()
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient.py", line 697, in ParseDepsFile
    gclient_eval.Exec(deps_content, global_scope, local_scope, filepath)
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient_eval.py", line 211, in Exec
    _visit_in_module(stmt)
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient_eval.py", line 195, in _visit_in_module
    value = _gclient_eval(node.value, global_scope, filename=filename)
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient_eval.py", line 175, in _gclient_eval
    return _convert(node_or_string)
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient_eval.py", line 148, in _convert
    for k, v in zip(node.keys, node.values))
  File "/usr/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient_eval.py", line 148, in <genexpr>
    for k, v in zip(node.keys, node.values))
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient_eval.py", line 148, in _convert
    for k, v in zip(node.keys, node.values))
  File "/usr/lib/python2.7/collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 571, in update
    for key, value in other:
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient_eval.py", line 148, in <genexpr>
    for k, v in zip(node.keys, node.values))
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient_eval.py", line 167, in _convert
    return _convert(node.left) + _convert(node.right)
  File "/home/sam/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX/depot_tools/gclient_eval.py", line 169, in _convert
    return _convert(node.left) % _convert(node.right)
TypeError: not all arguments converted during string formatting
```

You can get this in isolation by running

```
[~/rethinkdb/external/v8_4.7.80.23.fetch-3NeaCZdX]
$ ./depot_tools/gclient sync --revision v8@a10202d1aa3cbaa3b550401bebbe34119b2d20b2
```
