### ISSUE TITLE
rethinkdb restore fails under windows.

### ISSUE THREAD

**Issue by Kodehawa** [rethinkdb/rethinkdb#6584]
That's it.
Running `rethinkdb restore` on Windows 10 Fall Creators Update ends up with the following output:

```
C:\Users\Yomura\Documents\rethinkdb-2.3.5>rethinkdb restore rethinkdb_dump_2017-12-28T10_58_21.tar.gz

C:\Users\Yomura\Documents\rethinkdb-2.3.5>Unzipping archive file...
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python\Python36-32\Scripts\rethinkdb-restore-script.py", line 11, in <module>
    load_entry_point('rethinkdb==2.3.0.post6', 'console_scripts', 'rethinkdb-restore')()
  File "c:\program files (x86)\python\python36-32\lib\site-packages\rethinkdb\_restore.py", line 268, in main
    run_rethinkdb_import(options)
  File "c:\program files (x86)\python\python36-32\lib\site-packages\rethinkdb\_restore.py", line 248, in run_rethinkdb_import
    sub_dir = do_unzip(temp_dir, options)
  File "c:\program files (x86)\python\python36-32\lib\site-packages\rethinkdb\_restore.py", line 186, in do_unzip
    f.extractall(members=members)
  File "c:\program files (x86)\python\python36-32\lib\tarfile.py", line 2007, in extractall
    numeric_owner=numeric_owner)
  File "c:\program files (x86)\python\python36-32\lib\tarfile.py", line 2049, in extract
    numeric_owner=numeric_owner)
  File "c:\program files (x86)\python\python36-32\lib\tarfile.py", line 2111, in _extract_member
    os.makedirs(upperdirs)
  File "c:\program files (x86)\python\python36-32\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "c:\program files (x86)\python\python36-32\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: '.\\rethinkdb_dump_2017-12-28T10:58:21'
```

Same command and file under linux works perfectly.

**Comment by srh** [comment]
It looks like it's generating some path with "\\" there.  In Linux it might be doing "//", but that's OK on Linux.

**Comment by Kodehawa** [comment]
Anyway of getting around this? I want to test some queries under the production's db amounts, but I cannot if I cannot restore the dump I made of the production database some days ago on my development machine.

**Comment by srh** [comment]
You could look in _restore.py and find where it's constructing the path.

**Comment by srh** [comment]
Presumably before line 186, in do_unzip, or somewhere else in that stack trace.

**Comment by biapar** [comment]
@srh So, Is't a bug?

**Comment by srh** [comment]
Yes. A fix would be nice.

**Comment by ShadowJonathan** [comment]
It's a bug with assuming which environment python lives in, constructing paths from `pathlib` would help, as it automatically and easily abstracts that away
