### ISSUE TITLE
Android and java.util.Base64 issue

### ISSUE THREAD

**Issue by teddybee** [rethinkdb/rethinkdb#6604]
I would like to use this db on android, but I got an exception when I want to authenticate a user:

```
java.lang.NoClassDefFoundError:` Failed resolution of: Ljava/util/Base64;
                                                                                        at com.rethinkdb.net.Crypto.<clinit>(Crypto.java:30)
                                                                                        at com.rethinkdb.net.Crypto.makeNonce(Crypto.java:115)
                                                                                        at com.rethinkdb.net.Handshake$InitialState.<init>(Handshake.java:44)
                                                                                        at com.rethinkdb.net.Handshake.<init>(Handshake.java:266)
                                                                                        at com.rethinkdb.net.Connection.<init>(Connection.java:61)
                                                                                        at com.rethinkdb.net.Connection$Builder.connect(Connection.java:421)
                                                                                        at com.suddensparks.wirelessimulogger.data.repositories.AuthRepository.loginUser(AuthRepository.java:29)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" on path: DexPathList[[zip file "/data/app/com.suddensparks.wirelessimulogger-2/base.apk"],nativeLibraryDirectories=[/data/app/com.suddensparks.wirelessimulogger-2/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
                                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
```

On android there is no java.util.Base64 lib, instead I should use the android.util.Base64
[https://developer.android.com/reference/android/util/Base64.html](https://developer.android.com/reference/android/util/Base64.html)

**Comment by srh** [comment]
I recommend making a fork of the Java driver (just copy out all of drivers/java to a separate repo) and making a version that works for Android.

**Comment by AndroBerdin** [comment]
Hey, have you solved the problem ? Im getting same error on runtime.

**Comment by srh** [comment]
@AndroBerdin The driver is still a Java driver that needs Java 8.  You can fork the driver for Android, or submit a patch that implements base64 encoding/decoding without dependence on java.util.Base64.

**Comment by adriantodt** [comment]
Since the Java driver now lives in https://github.com/rethinkdb/rethinkdb-java. Android 8.0 and Android Studio natively support Java 8, so open a ticket there instead if it doesn't work. This issue can be closed.
