### ISSUE TITLE
Uncaught ReqlDriverError

### ISSUE THREAD

**Issue by sathishkumarsoundharajan** [rethinkdb/rethinkdb#6718]
Can someone let me know why this error occurs ?

**Note: i have already found the stack path and found that we have try_catch added for it. still it is throwing an error and making my service restart.**

``` 21|example-s | Uncaught ReqlDriverError:
21|example-s |     at ReqlDriverError.ReqlError [as constructor] (/opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/errors.js:23:13)
21|example-s |     at new ReqlDriverError (/opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/errors.js:68:50)
21|example-s |     at Socket.handshake_callback (/opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/net.js:629:23)
21|example-s |     at <error: TypeError: Cannot read property 'name' of undefined>
21|example-s |     at <error: TypeError: Cannot read property 'name' of undefined>
21|example-s |     at <error: TypeError: Cannot read property 'name' of undefined>
21|example-s |     at <error: TypeError: Cannot read property 'name' of undefined>
21|example-s |     at <error: TypeError: Cannot read property 'name' of undefined>
21|example-s | ----------------------------------------
21|example-s |     at EventEmitter.on
21|example-s |     at makeWrappedCallback (/opt/services/dev/builds/example-service/v3.784.5/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
21|example-s |     at Socket.object.(anonymous function) [as on] (/opt/services/dev/builds/example-service/v3.784.5/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
21|example-s |     at Socket.Readable.on (_stream_readable.js:687:35)
21|example-s |     at Socket.<anonymous> (/opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/net.js:700:32)
21|example-s |     at Socket.g (events.js:292:16)
21|example-s |     at Socket.<anonymous> (/opt/services/dev/builds/example-service/v3.784.5/node_modules/long-stack-traces/lib/long-stack-traces.js:76:33)
21|example-s |     at emitNone (events.js:86:13)
21|example-s |     at Socket.emit (events.js:185:7)
21|example-s |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:10)
21|example-s | ----------------------------------------
21|example-s |     at EventEmitter.on
21|example-s |     at makeWrappedCallback (/opt/services/dev/builds/example-service/v3.784.5/node_modules/long-stack-traces/lib/long-stack-traces.js:65:26)
21|example-s |     at Socket.object.(anonymous function) [as on] (/opt/services/dev/builds/example-service/v3.784.5/node_modules/long-stack-traces/lib/long-stack-traces.js:51:38)
21|example-s |     at Socket.Readable.on (_stream_readable.js:687:35)
21|example-s |     at Socket.once (events.js:302:8)
21|example-s |     at new TcpConnection (/opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/net.js:527:20)
21|example-s |     at /opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/net.js:963:18
21|example-s |     at /opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/net.js:978:12
21|example-s |     at tryCatcher (/opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
21|example-s |     at Promise._resolveFromResolver (/opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:483:31)
21|example-s |     at new Promise (/opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/node_modules/bluebird/js/main/promise.js:71:37)
21|example-s |     at Function.<anonymous> (/opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/net.js:945:10)
21|example-s |     at Function.connect (/opt/services/dev/builds/example-service/v3.784.5/node_modules/rethinkdb/util.js:43:16)
21|example-s |     at /opt/services/dev/builds/example-service/v3.784.5/node_modules/ecom-tools-lib/lib/health-types/rethink-health.js:35:26
21|example-s |     at next (native)
21|example-s |     at onFulfilled (/opt/services/dev/builds/example-service/v3.784.5/node_modules/co/index.js:65:19)
21|example-s |     at /opt/services/dev/builds/example-service/v3.784.5/node_modules/co/index.js:54:5
21|example-s |     at co (/opt/services/dev/builds/example-service/v3.784.5/node_modules/co/index.js:50:10)
21|example-s |     at RethinkHealth.getConnectionStatus (/opt/services/dev/builds/example-service/v3.784.5/node_modules/ecom-tools-lib/lib/health-types/rethink-health.js:30:12)
21|example-s |     at /opt/services/dev/builds/example-service/v3.784.5/node_modules/ecom-tools-lib/lib/health-types/base-health.js:45:31
21|example-s |     at next (native)
21|example-s |     at onFulfilled (/opt/services/dev/builds/example-service/v3.784.5/node_modules/co/index.js:65:19)
21|example-s |     at /opt/services/dev/builds/example-service/v3.784.5/node_modules/co/index.js:54:5
21|example-s |     at co (/opt/services/dev/builds/example-service/v3.784.5/node_modules/co/index.js:50:10)
21|example-s |     at RethinkHealth.getStatus (/opt/services/dev/builds/example-service/v3.784.5/node_modules/ecom-tools-lib/lib/health-types/base-health.js:43:12)
21|example-s |     at /opt/services/dev/builds/example-service/v3.784.5/node_modules/ecom-tools-lib/lib/routes/health-route-handler.js:34:36
21|example-s |     at next (native)
21|example-s |     at onFulfilled (/opt/services/dev/builds/example-service/v3.784.5/node_modules/co/index.js:65:19)
21|example-s |     at process._tickDomainCallback (internal/process/next_tick.js:135:7) ```

**Comment by sathishkumarsoundharajan** [comment]
Anyone ?

**Comment by ronzeidman** [comment]
Try using my driver (rethinkdb-ts), there you should be able to catch the exception. The error seems to be you are trying to get a property call 'name' in an undefind object, you can either check if the object exists, add `.default(...)` to the end of the expression or make sure that every object has this property

**Comment by sathishkumarsoundharajan** [comment]
@ronzeidman Nope this is not my application error, this is triggering from rethinkdb

**Comment by sathishkumarsoundharajan** [comment]
@ronzeidman Thanks for answering.

**Comment by sathishkumarsoundharajan** [comment]
Team, please provide some pointers on how to debug this issue. Looks like it is rethinkdb driver issue to me. please provide some pointers

**Comment by grandquista** [comment]
https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/errors.coffee

Line 2. I would guess node got upgraded recently 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by grandquista** [comment]
It’s an uncaught TypeError. Not ReQLError in the trace. And something is failing about the server handshake, so there’s going to be more after this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sathishkumarsoundharajan** [comment]
@grandquista thanks for the response. the pointed the github link is in coffee script. But mine is running on old version  "rethinkdb": "^2.3.2"

**Comment by sathishkumarsoundharajan** [comment]
Is this infra issue ? If it is infra issue this error making my service restart, kind of un handled error. Is there is solution to handle this ? @grandquista / Or Someone ?

**Comment by grandquista** [comment]
The solution is downgrade node, or use the new driver

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AGuyNamedJens** [comment]
With an NPM package called rethinkdb-ts it keeps erroring on rethinkDB… which is also a rethinkdb drive error..


 ReqlDriverError: The connection was closed before the query could be completed
