### ISSUE TITLE
Error restoring a database

### ISSUE THREAD

**Issue by Dwigoric** [rethinkdb/rethinkdb#6725]
This is the output that I receive when trying to restore (on root):
```
Extracting archive file...
  Done (0 seconds)
Traceback (most recent call last):
  File "/usr/local/bin/rethinkdb-restore", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/_restore.py", line 284, in main
    do_restore(options)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/_restore.py", line 255, in do_restore
    sources = _import.parse_sources(options)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/_import.py", line 1444, in parse_sources
    primary_key, indexes, write_hook = parse_info_file(info_path)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/_import.py", line 1346, in parse_info_file
    return primary_key, indexes, write_hook
UnboundLocalError: local variable 'write_hook' referenced before assignment
```

RethinkDB version:
```
rethinkdb 2.3.6.srh.1~0bionic (CLANG 6.0.0 (tags/RELEASE_600/final))
```

The python driver is at version 2.4.1.

**Comment by srh** [comment]
It looks like the driver only works if the metadata is in the format returned by RethinkDB 2.4.  It looks like this is unintentional.  If you know a little Python you could edit the function parseInfoFile in `_import.py` to work around the issue.

**Comment by Dwigoric** [comment]
Sorry, I have no Python experience whatsoever. How would I edit the file?

**Comment by srh** [comment]
You should use the 2.3.6 version of the Python driver.

But if you don't want to do that, first you find the file -- I don't know where it's located off-hand, but you've got `_import.py` somewhere on your system. In that file on line 1346 you can see a use of write_hook that references it before assignment.  I think you could replace that usage with the value `None`.

Of course, editing an installed package on your system this way is hackish and kind of nutty -- so if you can, I'd install version 2.3.6 or earlier of the package.

**Comment by Dwigoric** [comment]
I'll do the first, however I'll leave this issue open since it is indeed an issue with the current version. Thanks for your reply!

**Comment by JKBCarbon** [comment]
I had exactly same problem. I downgraded Python driver using `sudo pip install "rethinkdb==2.3.0.post6" --force-reinstall`. It resolved the issue. 

To check if everything is ok, run `rethinkdb restore --help`. If help information is displayed then `restore` will work fine.

**Comment by heathweaver** [comment]
> I had exactly same problem. I downgraded Python driver using `sudo pip install "rethinkdb==2.3.0.post6" --force-reinstall`. It resolved the issue.
> 
> To check if everything is ok, run `rethinkdb restore --help`. If help information is displayed then `restore` will work fine.

It worked for me, but I had to do 'sudo pip3 install --force-reinstall "rethinkdb==2.3.0.post6"'

**Comment by biapar** [comment]
Windows?

**Comment by Dwigoric** [comment]
Ubuntu Linux 18.04.2

**Comment by gabor-boros** [comment]
I'm moving this issue to the python driver's repository. Side note: since I'm now aware of this issue I can fix this 😄
