### ISSUE TITLE
Getting [Error 107] Transport endpoint is not connected error

### ISSUE THREAD

**Issue by f1ps1** [rethinkdb/rethinkdb#6945]
Here is some information about my system:
- Running 32-bit Raspbian on a Raspberry Pi B3 (`Linux raspberrypi 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux`)
- RethinkDB version 2.4.1 (CLANG 7.0.1)
- 3 Threads, 2 IO Threads
- 1GB cache

The RethinkDB server is being started by a .service file looking like the following:
```service
[Unit]
Description=RethinkDB is a NoSQL database
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=root
ExecStart=rethinkdb --server-name jarvis --bind 0.0.0.0 --cores 3 --io-threads 2 --cache-size 1024 --log-file /jarvis/server/logs/jarvis-rethinkdb.log --daemon
StandardOutput=append:/jarvis/server/logs/jarvis-rethinkdb-output.log
StandardError=append:/jarvis/server/logs/jarvis-rethinkdb-error.log

[Install]
WantedBy=multi-user.target
```

I use the following short python script to manage DB access (`mydb` already exists):

```python
import types
from rethinkdb import RethinkDB


class Database:
    @staticmethod
    def get() -> list:
        r = RethinkDB()
        con = r.connect(db="mydb")
        con.check_open = types.MethodType(Database.auto_reconnect, con) 
        # above line taken from #6302  
        con.noreply_wait()
        return [r, con]

    @staticmethod
    def auto_reconnect(self):
        if self._instance is None or not self._instance.is_open():
            self.reconnect()

```

That's how I use this script:

```python
from Database import Database
r, con = Database.get()

```

And I get the following errors after a random time (most of the time after I ran ~10 queries, then making a pause and then getting these errors):

```python
>>> r.db("rethinkdb").table_list().run(con)
['cluster_config', 'current_issues', 'db_config', 'jobs', 'logs', 'permissions', 'server_config', 'server_status', 'stats', 'table_config', 'table_status', 'users']
>>> r.db("rethinkdb").table("status").run(con)
[Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/ast.py", line 146, in run
    return c._start(self, **global_optargs)
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/net.py", line 749, in _start
    return self._instance.run_query(q, global_optargs.get("noreply", False))
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/net.py", line 566, in run_query
    res = self._read_response(query)
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/net.py", line 590, in _read_response
    self._header_in_progress = self._socket.recvall(12, deadline)
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/net.py", line 492, in recvall
    raise ReqlDriverError("Connection is closed.")
rethinkdb.errors.ReqlDriverError: Connection is closed.  

>>> r.db("rethinkdb").table("stats").run(con)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/net.py", line 500, in sendall
    offset += self._socket.send(data[offset:])
AttributeError: 'NoneType' object has no attribute 'send'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/ast.py", line 146, in run
    return c._start(self, **global_optargs)
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/net.py", line 745, in _start
    self.check_open()
  File "/home/pi/.local/lib/python3.7/site-packages/jarvis/Database.py", line 47, in auto_reconnect
    self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/net.py", line 693, in reconnect
    self.close(noreply_wait)
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/net.py", line 727, in close
    return instance.close(noreply_wait, noreply_wait_token)
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/net.py", line 555, in close
    self.run_query(noreply, False)
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/net.py", line 561, in run_query
    self._socket.sendall(query.serialize(self._parent._get_json_encoder(query)))
  File "/usr/local/lib/python3.7/dist-packages/rethinkdb/net.py", line 514, in sendall
    "Error sending to %s:%s - %s" % (self.host, self.port, str(ex))
rethinkdb.errors.ReqlDriverError: Error sending to localhost:28015 - 'NoneType' object has no attribute 'send'  

>>> r.db("rethinkdb").table("stats").run(con)
<rethinkdb.net.DefaultCursor object at 0x75d49170 (done streaming):
# and it works again  
```

I have about 5 client connections open at the same time (that's what `rethinkdb.stats` says)
Why am I getting these errors?

**Comment by f1ps1** [comment]
I forgot to mention that: 

When I remove the `con.check_open = types.MethodType(Database.auto_reconnect, con)` part from my script, the connection runs into timeout saying 
```
[Errno 107] Transport endpoint is not connected
rethinkdb.errors.ReqlDriverError: Connection is closed.
```

and does not reconnect, so I'm not able to run any queries after that.

**Comment by AlexanderNitsch** [comment]
Could be related to the errors I experienced. I commented on #6449

**Comment by evgeniyy2003** [comment]
Hi,
I have the same issue on import a large file (~20G). `[Error 107] Transport endpoint is not connected error`.
Any workaround?
