### ISSUE TITLE
rethinkdb dump error

### ISSUE THREAD

**Issue by philchass** [rethinkdb/rethinkdb#6997]
Mac Pro M1 2020
OS Big Sur 11.6

RethinkDB : 2.4.0-8-g07da06-dirtyWeb UI Settings
Python : 3.7.9

rethinkdb dump -e test -f test.tgz

→ ERROR
`Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.7.9/bin/rethinkdb-dump", line 5, in <module>
    from rethinkdb._dump import main
  File "/Users/xxx/.pyenv/versions/3.7.9/lib/python3.7/site-packages/rethinkdb/__init__.py", line 93, in <module>
    r = RethinkDB()
  File "/Users/xxx/.pyenv/versions/3.7.9/lib/python3.7/site-packages/rethinkdb/__init__.py", line 32, in __init__
    from rethinkdb import (
  File "/Users/xxx/.pyenv/versions/3.7.9/lib/python3.7/site-packages/rethinkdb/_dump.py", line 35, in <module>
    from rethinkdb import _export, utils_common
  File "/Users/xxx/.pyenv/versions/3.7.9/lib/python3.7/site-packages/rethinkdb/_export.py", line 23, in <module>
    import ctypes
  File "/Users/xxx/.pyenv/versions/3.7.9/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'`

**Comment by lsabi** [comment]
This error is due to the `_ctypes` module linkage missing in your python installation and system. It is not related with the database itself.

Searching for the error reported by the python interpreter shows the following answer

[https://www.pythonpool.com/modulenotfounderror-no-module-named-_ctypes-solved/](https://www.pythonpool.com/modulenotfounderror-no-module-named-_ctypes-solved/)

which relies on

[https://github.com/pyenv/pyenv/issues/1768#issuecomment-871602950](https://github.com/pyenv/pyenv/issues/1768#issuecomment-871602950)
