### ISSUE TITLE
RethinkDB doesn't build on a non-unicode locale

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#703]
```
$ LANG=C make
[...]
    [242/246] HANDLEBARS build/release/rethinkdb_web_assets/js/template.js
Traceback (most recent call last):
  File "./scripts/build_handlebars_templates.py", line 50, in <module>
    text = f.read()
  File "/usr/lib64/python3.2/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1196: ordinal not in range(128)
```

**Comment by danielmewes** [comment]
Outdated. This is working.
